Code cleanup
laravel/framework pull request #16168
Opened 2016-10-29 16:13 UTC by PleaseDontKillMe

It's not much, but I just want to see if people here are actually merging pull requests :)

2016-10-29 16:47 UTC, browner12 requested changes
imports should be done shortest to longest, so your change in `HandleQueuedMessage.php` will not be approved.

2016-10-29 17:55 UTC, GrahamCampbell commented
Thanks. Left some comments for you.

2016-10-29 17:55 UTC, GrahamCampbell requested changes

2016-10-29 17:55 UTC, GrahamCampbell commented on src/Illuminate/Queue/SyncQueue.php
> -     * @return void
Please do not delete this.

2016-10-29 17:55 UTC, GrahamCampbell commented on src/Illuminate/Mail/Jobs/HandleQueuedMessage.php
> +use Illuminate\Support\Str;
Please don't move these.

2016-10-29 17:55 UTC, GrahamCampbell commented on src/Illuminate/Database/Connectors/ConnectionFactory.php
> -use PDO;
I think this was already fixed? Please rebase. :)

2016-10-30 15:12 UTC, taylorotwell commented
Some of these changes are invalid. Resubmit with corrections if you would like.

2016-10-30 15:12 UTC, closed without merging

2016-11-03 15:02 UTC, PleaseDontKillMe commented
I believe autoformat from PhpStorm moved these imports for me. I always used imports in alphabetical order (why shortest to longest?)

2016-11-03 15:04 UTC, browner12 commented
that's just the convention Laravel has taken.

2016-11-03 15:29 UTC, PleaseDontKillMe commented
Does it matter, after all? Nothing bad happens if they're not in that "order" right? So why do you guys follow it?

2016-11-03 15:46 UTC, browner12 commented
no, it doesn't matter from a code execution standpoint.

why should we put them in alphabetical order? should we use spaces or tabs? should curly braces be on the same line or next?   none of these really matter, just a convention Laravel has picked to follow to make their code consistent.

2016-11-03 15:49 UTC, PleaseDontKillMe commented
imports have nothing to do with code consistency. I use what PhpStorm autoformat enforces, you just click Ctrl+Alt+L and there you go. No more consistency problems.

2016-11-03 15:55 UTC, browner12 commented
and someone else's editor autoformats it a different way.

enough bikeshedding, focus on the important stuff.

2016-11-03 16:08 UTC, PleaseDontKillMe commented
So why bother with it?