Create seeders when creating Models or Migrations
laravel/framework pull request #16177
Opened 2016-10-29 23:58 UTC by jwcobb

Add `--seeder` to `artisan make:migration` or `artisan make:model` to create a matching Seeder. This was discussed in [laravel/internals Issue 13](https://github.com/laravel/internals/issues/13). A matching PR for laravel/docs will be following.

2016-10-30 10:40 UTC, GrahamCampbell commented
Thanks for the PR. I've left a minor review comment. :)

2016-10-30 10:40 UTC, GrahamCampbell requested changes

2016-10-30 10:40 UTC, GrahamCampbell commented on src/Illuminate/Database/Console/Migrations/MigrateMakeCommand.php
> +use Illuminate\Support\Str;
Please order imports by length/

2016-10-31 14:05 UTC, taylorotwell commented
I kinda want to avoid heading this direction because it sort of tends to bloat over time. For example, next why would't we add an option to the model command to create a seeder as well? Then we would be able to create a migration, a resource controller, a plain controller, and a seeder all from the make:model command. I would prefer to keep them slightly more separate.

2016-10-31 14:05 UTC, closed without merging

2016-10-31 14:38 UTC, browner12 commented
yah, i'm really starting to regret sending that PR for creating a controller along with the models, because i knew this is what would happen. 

maybe the solution is remove all of these 'nicety' options and encourage users to create a custom console command called something like `make:all`.  Then within that command, the user could define exactly what they wanted.

```php
public function handle()
{
    $this->call('make:controller');
    $this->call('make:seeder');
    $this->call('make:migration');
}
```