[5.3] Return early when chunk size is less than zero
laravel/framework pull request #16206
Opened 2016-11-01 07:27 UTC by jstoone

I found that this PR might be relevant after working on spatie/laravel-collection-macros#13, and figured it might be relevant for the core. It is very much an edge-case.

### The problem
Many use `chunk()` as a way to split their collection into parts, so that it's easier to create columns of content. But if the `$size` is dynamically calculated, it may occur that the result of the calculation is 0.
If `array_chunk()` is given a value less than 1, it will throw an error. This will, from my point of view, generate a lot of unnecessary empty checks in peoples views.

### The solution
If the `chunk()` method would return early if the given chunk size was == 0,

2016-11-01 12:55 UTC, GrahamCampbell requested changes

2016-11-01 12:55 UTC, GrahamCampbell commented on src/Illuminate/Support/Collection.php
> +            return $this;
You should return a new instance, not the same one please.

2016-11-01 15:05 UTC, taylorotwell commented
Honestly to me it *should* throw an error? If you're passing 0 into chunk it definitely shouldn't return the current collection. That doesn't make any sense to me. If anything it should return an empty new collection as Graham said.

2016-11-01 15:20 UTC, jstoone commented
I totally see your point(s).

In either case I think it would be nice to see it handled in another way. It's not always directly obvious when getting an exception/error from `array_chunk`.

I'll change the comments mentioned in the review by @GrahamCampbell. If you feel like throwing an error @taylorotwell, I think it would be more appropriate to message that the error is from within Collection::chunk.

I hope that makes sense.

2016-11-01 15:26 UTC, GrahamCampbell requested changes

2016-11-01 15:26 UTC, GrahamCampbell commented on src/Illuminate/Support/Collection.php
> +        if ($size == 0) {
We should throw an invalid argument exception for less than 0 also.

2016-11-01 15:26 UTC, jstoone commented on src/Illuminate/Support/Collection.php
> +            return $this;
It now returns a new instance instead.

2016-11-01 15:34 UTC, jstoone commented on src/Illuminate/Support/Collection.php
> +        if ($size == 0) {
This has now been added, together with a test.

2016-11-01 18:47 UTC, merged

2016-11-02 07:04 UTC, vlakoff commented
Maybe a similar change could be applied to Query\Builder and Eloquent\Builder's `chunk` and `chunkById` methods.