[5.4] Allow passing relative view path to @include
laravel/framework pull request #16218
Opened 2016-11-01 22:47 UTC by themsaid

In reference to https://github.com/laravel/internals/issues/183

This PR allows the following:

```
// In view blog/posts/post.blade.php

@include('>sidebar')
```

This is equivalent to:

```
@include('blog.posts.sidebar')
```

2016-11-02 00:49 UTC, JosephSilber commented
@themsaid curious why you settled on the `>` character. I personally like the `:` more.

2016-11-02 05:07 UTC, prateekkathal commented
I agree with @JosephSilber `:` looks much cleaner... A `~` can also be used 😄

2016-11-02 05:25 UTC, jhoff requested changes
Added a few comments to the code changes. I feel like a different character just doesn't feel right. What if the expression just started with a period? Could that be used as the indicator?

2016-11-02 05:25 UTC, jhoff commented on src/Illuminate/View/Compilers/BladeCompiler.php
> +            if (Str::startsWith($expression, $quote)) {
`startsWith` already accepts an array as the second "needles" argument:

```
if (Str::startsWith($expression, ["'", '"'])) {
    $expression = substr($expression, 1, -1);
}
```

2016-11-02 05:25 UTC, jhoff commented on src/Illuminate/View/Compilers/BladeCompiler.php
> +    private function viewBase()
This whole method is kinda hard to grok TBH...

2016-11-02 05:25 UTC, jhoff commented on src/Illuminate/View/Compilers/BladeCompiler.php
> +        if ($this->view && Str::startsWith($stripped = $this->stripQuotes($expression), '>')) {
This could probably be refactored a bit to be more legible.

2016-11-02 06:12 UTC, themsaid commented
@JosephSilber added the delimiter as a clss constant for easy change since I was sure we might get many other suggestions as well 😃 
https://github.com/laravel/framework/pull/16218/files#diff-ee25397bd547c885a2e12e8894938b8cR19

2016-11-02 14:40 UTC, ericbarnes commented
Is it not possible from the coding side to just use the more familiar syntax? 

```
@include('./sidebar')
```

2016-11-02 18:03 UTC, JosephSilber commented
Dots and slashes are identical in blade includes, so that would be very confusing.

2016-11-02 18:24 UTC, jhoff commented
Why not just a dot?

```
@include('.sidebar')
```

2016-11-02 19:08 UTC, JosephSilber commented
A dot would be converted to a leading slash, which usually indicates an absolute path, not a relative one.

2016-11-08 22:30 UTC, taylorotwell commented
I'm going to hold off on this for now. I was actually able to implement it just within the Blade compiler itself without any other changes but there is no good way to support it for the `@each` directive and that will cause confusion and be inconsistent.

2016-11-08 22:30 UTC, closed without merging