Allow schedule:run to run as a daemon.
laravel/framework pull request #16436
Opened 2016-11-16 17:57 UTC by tback

Adds an option --loop so the scheduler will run forever. Triggering events once every 60 seconds by default.
Adds an option --interval so the interval can be adapted.

I added this option because it is handy in kubernetes. By running the event scheduler in a loop it can be a well behaved pod.

This is my first contribution to this project. I read the contribution guidelines, but I might have missed something.

2016-11-16 18:23 UTC, fernandobandeira commented on src/Illuminate/Console/Scheduling/ScheduleRunCommand.php
> +        if (! is_int($interval) && $interval <= 0) {
Is this necessary? If the $interval is <= 0  then it will default to 1 anyway.

And also shouldn't it use || instead of &&?

2016-11-16 18:53 UTC, GrahamCampbell requested changes

2016-11-16 18:53 UTC, GrahamCampbell commented on src/Illuminate/Console/Scheduling/ScheduleRunCommand.php
> +            //pause for a minimum of one second.
Please add a space character between the slashes and the comment body.

2016-11-16 18:56 UTC, tback commented on src/Illuminate/Console/Scheduling/ScheduleRunCommand.php
> +        if (! is_int($interval) && $interval <= 0) {
You're right. That was wrong. `is_int` on a string confused me. 

Fixed it.

2016-11-16 19:11 UTC, tback commented on src/Illuminate/Console/Scheduling/ScheduleRunCommand.php
> +            exit(1);
Fixed in 2f9e6c09d110a7bed32c0ae3fa6fdcc07043e369

2016-11-16 19:11 UTC, tback commented on src/Illuminate/Console/Scheduling/ScheduleRunCommand.php
> +            //pause for a minimum of one second.
Fixed in adc8a0dd99a7dcb8d3191a390e3be234eab039c4

2016-11-16 19:12 UTC, tback commented on src/Illuminate/Console/Scheduling/ScheduleRunCommand.php
> +            $sleep_time = max(1, $interval - (time() - $start));
Fixed in a6a86a84018cac78a203b97b9daa8f788d0c818f

2016-11-16 19:12 UTC, tback commented on src/Illuminate/Console/Scheduling/ScheduleRunCommand.php
> +    private function doScheduleDueEvents()
Fixed in 9b1c31faf593252cac39609e11a54e8d44500f68

2016-11-16 19:14 UTC, tback commented on src/Illuminate/Console/Scheduling/ScheduleRunCommand.php
> +
Fixed in 40ed862fc9b4243e33c8dbaee40c3e82e542c128. This was force push integrating changes requested by style ci.

2016-11-16 19:18 UTC, tback commented
Requested changes should be done. Sorry for the mess.

2016-11-16 20:54 UTC, taylorotwell commented
This may lead to some undefined behavior. What if one of the tasks takes 2 minutes to run? Now you're actually running the scheduler every two minutes instead of every 1 minute, etc.

2016-11-16 22:14 UTC, tback commented
@taylorotwell 
I wasn't aware schedule:run has those strict requirements. I therefore removed the interval option, explained the requirement in --daemon help and log an error if this ever happens.

I use schedule:run only to dispatch jobs to workers, so this should not be a problem. People who use schedule:run for long running job will probably have a hard time setting up a reliable daemon with systemd or supervisor as well. I reckon those people will stay with cron anyway.

2016-11-17 13:55 UTC, taylorotwell commented
Probably a better way to do this entirely and still recreate the exact behavior of how cron would work would be to fire off `php artisan schedule:run &` so that the process is started in the background as a new process, then sleep for 60 seconds, then do it again, etc.

2016-11-17 22:12 UTC, tback commented
That would create operations problems in it's own. I'm quite happy with my solution for the time being. I just released it as a package: https://github.com/tback/laravel-scheduledaemon

2016-11-17 22:12 UTC, closed without merging