[5.4] Add Caster Classes
laravel/framework pull request #16460
Opened 2016-11-18 06:16 UTC by faustbrian

This makes use of classes for casting models instead of using a switch statement for each single type to perform some action on the value.

``` php
<?php

class Invoice extends Eloquent
{
    protected $casts = [
        'amount_due' => 'money'
    ];

    protected $customCasters = [
        'money' => \App\Casters\MoneyCaster::class
    ];
}
```

``` php
<?php

class MoneyCaster extends AbstractCaster
{
    public function as($value)
    {
        return $value;
    }

    public function from($value)
    {
        return Money((int) $value);
    }
}
```

2016-11-18 10:32 UTC, DuckThom requested changes
`as` Is a reserved keyword in php and cannot be used as function name.

http://php.net/manual/en/reserved.keywords.php

2016-11-18 14:46 UTC, taylorotwell commented
This is essentially similar to the original model cast PR I already submitted. We may re-open that one if interest continues.

2016-11-18 14:46 UTC, closed without merging

2016-11-18 15:07 UTC, CristianLlanos commented
@taylorotwell I believe this approach is bit different to your proposal [#13706](https://github.com/laravel/framework/pull/13706). In your proposal we can only cast attributes into classes whereas with this alternative we can use it to transform attributes to whatever value we want. For example, decoding from base64 string [#16450](https://github.com/laravel/framework/pull/16450). It will be up to the developer to take care of value objects if that's what they need/want; but this PR is not about casting attributes into objects, it's more generic.

2016-11-18 15:13 UTC, CristianLlanos commented
@JosephSilber, I think this gives us the freedom we needed.

2016-11-18 15:14 UTC, faustbrian commented
@taylorotwell As @CristianLlanos pointed out this implementation is kept quite generic and opposed to your PR this leaves the developer free hand as to what he wants to do with the value passed to the caster.

2016-11-26 07:53 UTC, faustbrian commented
@CristianLlanos Moved the PR to a package https://github.com/faustbrian/Eloquent-Castable.