Fix to prevent recursive where clause addition for chunkById
laravel/framework pull request #16498
Opened 2016-11-22 02:18 UTC by soundsgoodsofar

Noticed during a recent meetup presentation that when running chunkById, the id where clause gets appended over and over again.  (Ie you get queries like `SELECT * FROM my_table WHERE id > 50 AND id > 100 AND id > 150 AND ...).

For smaller datasets this isn't a big deal, but as the whole point of chunkById is dealing with increasingly larger datasets, this seems problematic.  Eventually you'll run into query length limits somewhere.  Even if you don't, transmitting so much useless data hurts my sense of performance.

This change is intended to "tag" the chunking where clause so it gets replaced each iteration instead of appended.  I couldn't find anywhere that relies on the Builder where member variable to be numerically indexed, so I don't believe this will be an issue.  Still, I'm not intimately familiar with this framework.

Also, this prevents the usage of more exotic id columns with chunkById.  Frankly I think that's desirable--I would restrict it further to only allowing use of indexed columns if I could.  If there's disagreement with this, another option would be to make the `where` function a wrapper around an internal function that also accepts a tag parameter.

2016-11-22 14:26 UTC, taylorotwell commented
Can you show me some code I can use to recreate the issue?

2016-11-22 15:07 UTC, vlakoff commented
I can reproduce this issue, good catch.

2016-11-22 15:14 UTC, vlakoff commented
Alternatively, maybe the `$this->wheres` property could be "pre-filtered", like it's done above for the `$this->orders` property. Did you try it?

2016-11-22 16:13 UTC, taylorotwell commented
Can someone just share the code I need to reproduce this?

2016-11-22 16:51 UTC, vlakoff commented
Just use this on any table you have available:
```php
\DB::enableQueryLog();

$count = 0;
\DB::table('users')->chunkById(1, function () use (&$count) {
    if (++$count > 2) return false;
});

var_dump( \DB::getQueryLog() );
```

2016-11-22 20:48 UTC, soundsgoodsofar commented
Thanks vlakoff, yes that's the issue.  Especially bad with low chunk sizes.

Sure, there are many ways to solve this so up to you guys how you prefer to tackle it.  I figured I'd just offer one of the simpler solutions.  I hesitate on running the where clauses through a pre-filter though--eliminating basic redundancies wouldn't be too bad, but I could see that quickly snow balling into some crazy finite state machine to optimize wheres.  The SQL engine query optimizer already does that sort of stuff anyway, and it seemed a little overkill for this situation.

Also the chunkById issue is a bug, but I can see other cases where the ability to tag where clauses would be a useful feature and not a matter of optimizing away redundancy.  For example, it might be nice to cycle through a set of enumerated values in a where clause without creating an entirely new query each loop.

Another option would also be to change the existing `where` function to be a wrapper to another that accepts a tag parameter (default null), allowing any variety of where clauses to be labeled for future modification/removal.  Not sure if this aligns with the product vision though, so I didn't go that route.

2016-11-23 14:21 UTC, taylorotwell commented
I don't understand why we're having to fix these problems now. Did chunk always have this problem. Was the problem just introduced? If so, how and why and can we revert that change instead of introducing some new key into the wheres clause? Who knows what other consequences that will have.

2016-11-23 15:02 UTC, vlakoff commented
I think some people just gained interest in this previously rarely used method.

My PRs were about usability (#16180, #16283) and adding tests (#16263, #16359), the main target being https://github.com/laravel/internals/issues/103.

But here we have a real bug. It's probably present since the first implementation of `chunkById`.

2016-11-23 15:14 UTC, vlakoff commented
Just in case, ping @mzur, as you have authored #14499 and #14711 maybe you have some insight.

Also ping @nunomazer as you authored #13604 (didn't you encounter the same issue with the "where" clause?)

2016-11-23 16:18 UTC, taylorotwell commented
So this big under discussion in this PR was not introduced with *any* recent PR, but has existed since chunk was introduced?

2016-11-23 17:20 UTC, vlakoff commented
It seems so. Not `chunk` but the later `chunkById`.

2016-11-23 17:23 UTC, mzur commented
Yes, this where clause exists since v5.2.27 when `chunkById` was [introduced](https://github.com/laravel/framework/commit/69ab867050c79d30101cc8edbe6b465274f3cc39).

2016-11-24 22:47 UTC, GrahamCampbell requested changes

2016-11-24 22:47 UTC, GrahamCampbell commented on src/Illuminate/Database/Query/Builder.php
> +     */
missing return annotation

2016-11-24 22:47 UTC, GrahamCampbell commented on src/Illuminate/Database/Query/Builder.php
> +     * Subsequent calls override existing limit.
Missing newline.

2016-11-24 22:47 UTC, GrahamCampbell commented on src/Illuminate/Database/Query/Builder.php
> -                    ->orderBy($column, 'asc')
Please restore this whitespace.

2016-11-26 07:32 UTC, derekmd commented
This `chunkById` method behavior since 5.2 wouldn't have been noticed because its output is idempotent.

* Chunk 1: `WHERE id > 0`
* Chunk 2: `WHERE id > 0 AND id > 100`
* Chunk 3: `WHERE id > 0 AND id > 100 AND id > 200`
* Chunk 4: `WHERE id > 0 AND id > 100 AND id > 200 AND id > 300`
* Chunk 5: `WHERE id > 0 AND id > 100 AND id > 200 AND id > 300 AND id > 400`

The result set for each chunk will be the same after the fix when only the last clause in the above iterations is applied.

* Chunk 1: `WHERE id > 0`
* Chunk 2: `WHERE id > 100`
* Chunk 3: `WHERE id > 200`
* Chunk 4: `WHERE id > 300`
* Chunk 5: `WHERE id > 400`

Its severity is mild as the fix only affects query performance once 100+ chunks are hit.

2016-11-28 17:31 UTC, soundsgoodsofar commented
@derekmd no argument with the mild statement.  This will indeed not affect the majority of users and it is idempotent (aside from when you exceed buffer limits and start to fatal).

However I wouldn't want laravel to become known for "doesn't scale".  These types of issues will contribute towards that reputation.

2016-11-28 21:06 UTC, vlakoff commented
Don't forget about a different fix I have [suggested above](https://github.com/laravel/framework/pull/16498#issuecomment-262267084). I bet it would be a better solution:

> Alternatively, maybe the `$this->wheres` property could be "pre-filtered", like it's done above for the `$this->orders` property.

2016-11-28 23:14 UTC, soundsgoodsofar commented
@vlakoff it seems to me that a filter at that lower level should be general purpose.  And I would be worried about trying to write a general purpose optimizer to accurately recognize and eliminate redundant where clauses.  Taking that to the extreme you'd essentially be writing a SQL query optimizer.  It will also certainly be worse performance-wise.

Possible I misunderstand what you mean though.

2016-11-28 23:16 UTC, soundsgoodsofar reviewed
Should all be good now

2016-11-29 00:24 UTC, vlakoff commented
I disagree when you say it's about optimizing the query, no, what we have here is a bug.

About my fix, I think it integrates better in the codebase. Your fix is introducing named where clauses. Though it would be great to get some feedback about the possible fixes.

2016-11-29 14:51 UTC, taylorotwell commented
@vlakoff if you have a better implementation of a fix then submit it.

2016-11-29 17:06 UTC, soundsgoodsofar commented
@vlakoff but how would you implement a general-purpose order-by filter at the lower level?  Are you talking about inspecting each order by clause to see if it is subsumed by another one?  That feels an awful lot like an NP-complete FSM waiting to happen if you do it in a way that isn't just a very naive approach targeting this specific case.

Maybe I misunderstand, as @taylorotwell said maybe send a PR?

2016-12-04 19:26 UTC, taylorotwell commented
@soundsgoodsofar possible to write a test for this?

2016-12-07 17:12 UTC, taylorotwell commented
Fixed: https://github.com/laravel/framework/commit/53f97a014da380dc85fb4b0d826475e562d78dcc

Would appreciate if y'all can confirm.

2016-12-07 17:12 UTC, closed without merging

2016-12-07 17:13 UTC, taylorotwell commented
I will make same fix to Eloquent query builder.

2017-01-12 11:26 UTC, jralph commented
I noticed this has been fixed, will this be released into `illuminate/database` at some point, as this is still at 5.3.23 at some point? Could really do with this fix in Lumen!