Allow to add condition using model key
laravel/framework pull request #16540
Opened 2016-11-24 20:10 UTC by mnabialek

If you want to add condition to get model by key as far as I know there is no way to do it so simple right now.

You need to use `where('id',5)` for example:

```
Model::where('id',5)->where('something_else',6)->first();
```

so you need to use `where` condition and remember the key (sometimes it's not `id`).

Using helper method `byKey` you can now simplify this.

This is quite useful when using `value` method.

For example:

```
return ($model = Model::find(1)) ? $model->value('name') : null
```

vs

```
return $model->byKey(1)->value('name')
```

2016-11-25 11:44 UTC, fernandobandeira commented
I think this should be renamed to ``` whereKey ```. here's why:

```php
return $model->byKey([1,3,5,7])->keyBy('unique_field');
```

IDK, the name is so similar so i think we should change it since it's an entirely different behavior...

2016-11-25 11:53 UTC, GrahamCampbell requested changes

2016-11-25 11:53 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Builder.php
> +     * @param  mixed  $id
not mixed?

2016-11-25 14:07 UTC, taylorotwell commented
Why not just `whereKey`?

2016-11-25 14:16 UTC, mnabialek commented on src/Illuminate/Database/Eloquent/Builder.php
> +     * @param  mixed  $id
What do you mean? $id can be array or int, mixed used here same as for `find` method

2016-11-25 14:22 UTC, mnabialek commented
@taylorotwell Good point, updated method name

2016-11-25 14:33 UTC, mnabialek commented
@taylorotwell About method name change, I'm just thinking - won't it cause side effects? What if someone has `key` column in table? Now (without this PR) they can use `whereKey('something')` what would be converted to `where('key', 'something')` but now after adding `whereKey` method it would be resolved to for example `where('id', 'something')` so it might break existing app. So probably we should either stick to `byKey` method name or use other method name. What do you think?

2016-11-26 02:05 UTC, taylorotwell commented
I think `whereKey` makes the most sense. Can you send this to master branch since technically it could be breaking? Thanks.

2016-11-26 02:05 UTC, closed without merging