Add partition collection method
laravel/framework pull request #16627
Opened 2016-12-02 08:11 UTC by freekmurze

The partition method returns a collection with two elements. Items in the first element did pass the given `$callback`, items in the second element did not.

Here's an example:

```php
collect(range(1, 10))->partition(function ($i) {
    return $i <= 5;
});

// returns a new collection
// first element is a collection with items 1,2,3,4,5
// second element is a collection with items 5,6,7,8,9,10
```

2016-12-02 13:36 UTC, taylorotwell commented on src/Illuminate/Support/Collection.php
> +        return new static($partitions);
Shouldn't you just return the plain array so you can separate them using `lists`?

2016-12-02 21:23 UTC, GrahamCampbell commented
Looks cool. It should be noted that the strict definition of a partition requires it to be non-empty, though, I guess it's probably ok in practical terms.

2016-12-02 21:23 UTC, GrahamCampbell requested changes

2016-12-02 21:23 UTC, GrahamCampbell commented on src/Illuminate/Support/Collection.php
> +     * Returns an array with two elements. Items in the first element did pass
Please format like the other phpdoc, then looks good. 👍

2016-12-02 21:35 UTC, freekmurze commented on src/Illuminate/Support/Collection.php
> +     * Returns an array with two elements. Items in the first element did pass
I'm afraid I don't see the formatting problem. Could you tell what's wrong with the current formatting?

2016-12-02 21:39 UTC, GrahamCampbell commented on src/Illuminate/Support/Collection.php
> +     * Returns an array with two elements. Items in the first element did pass
Short descriptions must be "sort". Exactly one sentence and one line. The rest must be seperated.

2016-12-02 22:57 UTC, freekmurze commented on src/Illuminate/Support/Collection.php
> +     * Returns an array with two elements. Items in the first element did pass
Got it, thanks for clarifying

2016-12-03 15:55 UTC, merged

2016-12-05 02:18 UTC, JosephSilber commented on src/Illuminate/Support/Collection.php
> +        return new static($partitions);
Actually, `list` works on collections, so I think we should definitely return a collection.

Really no collection method should ever return a plain array. You don't ever want to break the chain.