Add transpose to \Illuminate\Support\Collection
laravel/framework pull request #17029
Opened 2016-12-28 18:16 UTC by DrowningElysium

I was hoping to get the transpose method in the Collection class as this would make formatting data from a form easier. 
An example in how this is easier can be seen in [this post](https://adamwathan.me/2016/04/06/cleaning-up-form-input-with-transpose/) of Adam Wathan.

I have taken some inspiration from #14433, so some credits go to the people who contributed to it.

2016-12-28 18:30 UTC, GrahamCampbell commented
The transpose function has already been rejected, because it can be added as a macro?

2016-12-28 18:31 UTC, GrahamCampbell requested changes

2016-12-28 18:31 UTC, GrahamCampbell commented on src/Illuminate/Support/Collection.php
> +     * turning the rows into columns and the columns into rows.
Please format this correctly.

2016-12-28 18:31 UTC, GrahamCampbell commented on src/Illuminate/Support/Collection.php
> +            throw new \LengthException('Collection is not multidimensional with at least one child each!');
Please import this,

2016-12-28 18:46 UTC, DrowningElysium commented
I thought there were some issues with the implementation or something. That's why I made a PR as I think I fixed those.

2016-12-29 03:17 UTC, taylorotwell commented
Going to leave this as a macro option for now.

2016-12-29 03:17 UTC, closed without merging