Change how frequencies are tested for schedule
laravel/framework pull request #17086
Opened 2017-01-02 23:14 UTC by alexbowers

A change to how schedules are tested for their expression.

I opted to not use mocks, since Cache is not required for the tests to happen.

This, unfortunately, requries PHP 7.0+ to be done in this way, so if you wish to have support for the 5.6+, then this will be required:

```php
$this->event = new Event(
    m::mock('Illuminate\Contracts\Cache\Repository'),
    'php foo'
);
```

If https://github.com/laravel/framework/pull/17084 gets accepted, then this test is required:

```
/**
 * @test
 */
function every_x_minutes()
{
    $this->assertEquals("*/6 * * * * *", $this->event->everyXMinutes(6)->getExpression());
}
```

If https://github.com/laravel/framework/pull/17085 gets accepted, then this test is required:
```
/**
 * @test
 */
function weekends()
{
    $this->assertEquals("* * * * 0,6 *", $this->event->weekends()->getExpression());
}
```

2017-01-02 23:16 UTC, GrahamCampbell requested changes

2017-01-02 23:16 UTC, GrahamCampbell commented on tests/Console/Scheduling/FrequencyTest.php
> +    function every_minute()
this does't match the style of our other tests

2017-01-02 23:17 UTC, alexbowers commented on tests/Console/Scheduling/FrequencyTest.php
> +    function every_minute()
Ah, correct you are. I'll change them to match the format.

2017-01-02 23:18 UTC, GrahamCampbell commented on tests/Console/Scheduling/FrequencyTest.php
> +    function every_minute()
Thanks. Not that there's anything wrong with that format, it looks pretty nice, but, just not for laravel/frameworks tests please. :)

2017-01-02 23:28 UTC, alexbowers commented on tests/Console/Scheduling/FrequencyTest.php
> +    function every_minute()
Yeah, its my macro for creating tests. I use it for my personal tests, and out of habit used them here. My mistake, should have noticed that :)

2017-01-02 23:29 UTC, alexbowers commented
@GrahamCampbell Made that change. Thoughts on https://github.com/laravel/framework/pull/17086/files#diff-ff04bb655c1b51776934f8e56cdeb527R19 ?

2017-01-03 03:36 UTC, taylorotwell commented
So these new tests require PHP 7?

2017-01-03 03:38 UTC, alexbowers commented
@taylorotwell Not anymore. The original commit did, and I would strongly like to alter how the test works in Laravel 5.5+ when PHP 7.0+ is a requirement to eliminate an unnecessary mock, but for now, it works in PHP 5.6+

2017-01-03 03:45 UTC, alexbowers commented
There is a test written for the `weekends` that just got merged in too, I can apply that test tomorrow to this PR.

2017-01-03 14:03 UTC, merged

2017-01-03 14:07 UTC, alexbowers commented
@taylorotwell Please can you add in the test in my first message above for `weekends`, or should I submit it as a separate PR?