[5.4] Environment providers
laravel/framework pull request #17329
Opened 2017-01-13 20:25 UTC by BenCavens

With this PR a developer is able to register environment specific providers straight from within the `config/app.php` file.

```php
'providers' => [
    ...
    App\Providers\EventServiceProvider::class,
    App\Providers\RouteServiceProvider::class,
],

// Providers for local env only
'providers-local' => [
    \Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
],
```

The providers array from /config/app.php contains all serviceproviders required for your application.
But this list is environment-agnostic which means it will register all providers no matter which environment it's running in.

There are however some scenarios where packages are meant to only run on local or test devices, not on production. E.g. the [IdeHelper](https://github.com/barryvdh/laravel-ide-helper) package. This could be accomplished via the following:

```php
// Within your AppServiceProvider
if(app()->environment !== 'production')
{
    app()->register(LocalServiceProvider::class);
}
```

## Usage
- With this PR a developer is able to assign providers to a specific environment inside the `config/app.php` file where all providers reside. In addition to the default providers array you can add environment specific ones.  
- They must follow the naming convention: `providers-<environment>`. E.g. providers-local.
By adding a service provider to the e.g. providers-local array, you assert it is registered in the local environment and nowhere else.
- It is possible to add multiple provider lists. One for each environment.

## Example:
```php
'providers' => [
    ...
    App\Providers\EventServiceProvider::class,
    App\Providers\RouteServiceProvider::class,
],

'providers-local' => [
    \Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class,
],

'providers-staging' => [
    \MetricsServiceProvider::class,
],
```

## Notes
- This is a minor features that is fully backwards compatible. No breaking changes are introduced with this PR. Environment providers can be omitted entirely or left empty to maintain current registration logic. 
- There is currently no similar logic suggested for the aliases listing. 
- Should this proposal get accepted, It's our opinion that no additional boilerplate is needed for the config/app.php file (such as an empty `providers-local` array for instance). This feature can be launched 'under the radar'.
- As a developer, you still need to make sure that your code works in every environment and avoid dependencies in environments where you omitted the provider to be registered.

2017-01-13 21:29 UTC, GrahamCampbell requested changes

2017-01-13 21:29 UTC, GrahamCampbell commented on tests/Foundation/FoundationEnvironmentProvidersTest.php
> +        $app = m::mock('\Illuminate\Foundation\Application[registerProviders]');
No leading slash please.

2017-01-13 21:29 UTC, GrahamCampbell commented on tests/Foundation/FoundationEnvironmentProvidersTest.php
> +        $app = m::mock('\Illuminate\Foundation\Application[registerProviders]');
Same.

2017-01-13 21:30 UTC, GrahamCampbell commented
I'm 👎 here since this is already achievable using conditionals in the config file. Remember, that you config file is just a php file.

2017-01-14 07:42 UTC, BenCavens commented
You can indeed achieve the same effect by conditionals and maybe in this regard the PR is redundant. But it could help make the code more explicit and less cluttered.

2017-01-14 19:08 UTC, closed without merging

2017-01-25 16:51 UTC, sebastiaanluca commented
Been using my own package for this in all my projects to date to disable having local and development providers enabled in production, but in a clean way without excessive conditionals.

See https://github.com/sebastiaanluca/laravel-conditional-providers