Eloquent QueriesRelationships withCount now properly uses alias
laravel/framework pull request #17418
Opened 2017-01-19 12:22 UTC by pdscopes

Currently if you provide an alias when using `withCount` the function still adds "_count" to the end of the relation. This is frustrating to two ways:

1. I often use camelCase rather than snake_case for JSON responses which means I have to write extra logic to loop through the retrieved data and rename the relation.
2. I don't always want "count" at the end of the count, e.g. I might use "cardinality", this means I have to write extra logic to loop through the retrieved data and rename the relation.

Relates to my comments here:
https://github.com/illuminate/database/commit/2cae4734f9084b742ab764f9bbf13bbef17e16ba

> Your allowance for aliases is a very nice addition to the withCount function, however you force my count to have "_count" regardless whether I used the alias. Furthermore you force snake case to the alias name when I can specify that my model should not have snake attributes.
> 
> This is frustrating when I was camelCase in my JSON responses since I have to loop through the response to rename the property.

2017-01-19 14:23 UTC, taylorotwell commented
Tests fail.

2017-01-19 15:40 UTC, pdscopes commented
**FYI**: this is, _unfortunately_, a backwards incompatible change because people who use `withCount` with an alias provided will receive a change of property name in their models, e.g. `$query->withCount('foo as foo_bar')` will receive `foo_bar` in their model rather than `foo_bar_count`.

2017-01-19 18:14 UTC, GrahamCampbell requested changes

2017-01-19 18:14 UTC, GrahamCampbell commented on .idea/php.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file.

2017-01-25 13:48 UTC, taylorotwell commented
This will probably have to be re-submitted to master (5.5) since we didn't get a chance to merge it into the 5.4 release.

2017-01-25 13:48 UTC, closed without merging