[5.4] Added HasOneThrough and BelongsToThrough relationships
laravel/framework pull request #17417
Opened 2017-01-19 12:09 UTC by pdscopes

I have created a HasOneThrough and BelongsToThrough Eloquent relationships.

This was originally made in #16599 then improved upon in #16719 and #16812. Linked to #8721.

2017-01-19 18:15 UTC, GrahamCampbell requested changes

2017-01-19 18:15 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php
> +     * @param string      $related           Class name of related Model
Please remove all comments from this part of the phpdoc, we don't use this style. If anything is unclear, add a note in the "long description" part of the phpdoc.

2017-01-20 09:20 UTC, GrahamCampbell requested changes

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php
> +     *
please remove this extra line

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php
> +     * @param string $related
please put exactly 2 spaces either side of the word string

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php
> +     *
etc

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> + * @author Peter Scopes <peter.scopes@gmail.com>
we don't use author annotations

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> + * <code>
Please remove the whole class comment and instead PR to the docs repo.

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> +     */
missing return void

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> +     * @param string                                $farParentKey Foreign key to parent
cs

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> +     * @param Builder|null $query
cs

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> +     */
missing return

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> +     *
cs

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> +     * @param  array                                    $models   Parent models
cs

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> +     * @param  \Illuminate\Database\Eloquent\Collection $results  Related models
cs everywhere, going to stop commenting

2017-01-20 09:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/HasOneThrough.php
> +     * @param         $parentForeignKey
innvalid syntax

2017-01-27 15:50 UTC, pjona commented on src/Illuminate/Database/Eloquent/Relations/BelongsToThrough.php
> +    public function get($columns = ['*'])
Here we can add type hinting: `public function get(array $columns = ['*'])`

2017-01-27 15:50 UTC, pjona commented on src/Illuminate/Database/Eloquent/Relations/HasOneThrough.php
> +    public function get($columns = ['*'])
This same here (Type hinting).

2017-02-08 10:38 UTC, GrahamCampbell requested changes

2017-02-08 10:38 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php
> +    protected function performJoin(Builder $query = null)
please revert this breaking change

2017-02-08 15:52 UTC, pdscopes commented on src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php
> +    protected function performJoin(Builder $query = null)
In all of the relationships or just BelongsToMany.php?

2017-02-08 19:36 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php
> +    protected function performJoin(Builder $query = null)
Please only make the changes strictly needed for this PR. Please send that typehint change to the master branch, since it's breaking.

2017-02-08 21:23 UTC, riesjart commented on src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php
> +    protected function performJoin(Builder $query = null)
Out of curiosity, can you explain/hint why this is breaking?

2017-02-11 12:28 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php
> +    protected function performJoin(Builder $query = null)
Adding a typehint to a non-private method is a breaking change.

2017-03-16 16:58 UTC, taylorotwell commented
This a little out of date now. getRelationQuery I believe needs to be renamed and have its parameters updated.

2017-03-24 19:31 UTC, taylorotwell commented
Going to hold off on adding this for now. It's out of date.

2017-03-24 19:31 UTC, closed without merging

2017-07-26 09:13 UTC, Arkhas commented
Will this relation will be update to make it to 5.5 ?

2023-03-22 17:24 UTC, decadence commented
@mshamaseen https://github.com/staudenmeir/belongs-to-through