allow multiple manifest files for mix helper
laravel/framework pull request #17759
Opened 2017-02-03 17:47 UTC by SeoFood

If you have multiple laravel mix files (for backend and frontend) you can't use it with the helper.

Example mix File:
```
mix.setPublicPath('./public/admin')
mix.js('./js/app.js', '/js')
```

The mix-manifest.json is successfully saved in /public/admin/

Now you can add it in you blade Template with 
`<script src="{{ adminmix('js/app.js', 'admin') }}"></script>`

It works with Hot Reload too and not breaking things.

2017-02-03 19:07 UTC, GrahamCampbell commented on src/Illuminate/Foundation/helpers.php
> +     * @param string $path
please fix cs :)

2017-02-03 19:08 UTC, GrahamCampbell requested changes

2017-02-03 19:08 UTC, GrahamCampbell commented on src/Illuminate/Foundation/helpers.php
> +                "Unable to locate Mix file: {$path}. Please check your " .
please revert all these cs changes

2017-02-03 19:08 UTC, GrahamCampbell commented on src/Illuminate/Foundation/helpers.php
> -                    ? new HtmlString("http://localhost:8080{$manifest[$path]}")
please revert all these cs changes

2017-02-03 19:08 UTC, GrahamCampbell commented on src/Illuminate/Foundation/helpers.php
> +        if ( ! array_key_exists($path, $manifest)) {
please revert all these cs changes

2017-02-03 23:15 UTC, SeoFood commented
sorry about that

2017-02-03 23:16 UTC, GrahamCampbell requested changes

2017-02-03 23:16 UTC, GrahamCampbell commented on src/Illuminate/Foundation/helpers.php
> +     * @param string $path
Please revert the changes to this line, and match the cs of the next line.

2017-02-03 23:16 UTC, GrahamCampbell commented on src/Illuminate/Foundation/helpers.php
> +            ? new HtmlString("http://localhost:8080{$manifest[$path]}")
Please revert the indentation changes here.

2017-02-04 00:02 UTC, GrahamCampbell requested changes

2017-02-04 00:02 UTC, GrahamCampbell commented on src/Illuminate/Foundation/helpers.php
> +     * @param  string $path
still a missing space after the word string in both cases

2017-02-04 00:02 UTC, GrahamCampbell commented on src/Illuminate/Foundation/helpers.php
> +     * @param  string $path
there should be exactly 2 space characters

2017-02-04 15:26 UTC, merged

2017-02-09 00:14 UTC, brunogaspar commented
@SeoFood How did you ended up doing for your multiple mix files to be executed?

You have one `webpack.mix.js` and then require the other ones in this one?

2017-02-09 00:20 UTC, SeoFood commented
@brunogaspar No I have multiple `webpack.mix.js`for the frontend and for the backend because they use different webpack configs vendors and so on.

This is my Directory Structure for the admin:
![image](https://cloud.githubusercontent.com/assets/2766011/22763544/e347e7ba-ee65-11e6-90d4-5a85728e344e.png)

For the frontend is use it as it is.

2017-02-09 00:23 UTC, brunogaspar commented
Ah right, makes sense, because i was trying to use the `require()` to require the individual files aswell on the main `webpack.mix.js` and only the frontend assets where being compiled.

Your way kinda makes sense as well, since you can have individual dependencies.

Thanks for the fast reply 👍