[5.4] [Proposal] Allow custom pivot models to support global scopes and soft deletes
laravel/framework pull request #17833
Opened 2017-02-08 20:20 UTC by BrandonShar

Since 5.4 introduced using custom pivot table models, I thought it would be a good time to bring back up the concept of adding soft deletes and global scopes to BelongsToMany relationships.

This PR allows you to define global scopes and use SoftDeletes on your custom pivot table model and have them apply to your BelongsToMany relationships when you define the relationship with the new using syntax.

This PR doesn't include tests, because I know that Taylor has been against this previously so I didn't want to go through an entire submission process before this was discussed. I have the tests partially written and will commit them pending approval.

2017-02-08 22:24 UTC, GrahamCampbell requested changes

2017-02-08 22:24 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php
> +     * @param \Illuminate\Database\Query\Builder (optional)
incorrect syntax

2017-02-08 22:24 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/MorphToMany.php
> +    protected function newPivotQuery(Builder $query = null)
missing phpdoc

2017-02-08 22:24 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/Pivot.php
> +        if ($this->instantiatedAsModel) {
hmm, to me, this screams the need for class extension, to avoid runtime mimicry of what should really be a superclass

2017-02-08 22:25 UTC, BrandonShar commented on src/Illuminate/Database/Eloquent/Relations/Pivot.php
> +        if ($this->instantiatedAsModel) {
Good suggestion. I agree that this doesn't quite feel right.

2017-02-08 22:27 UTC, BrandonShar commented on src/Illuminate/Database/Eloquent/Relations/Pivot.php
> +        if ($this->instantiatedAsModel) {
The problem stems from Pivot breaking substitution with Model... I'll propose some rearranging of the Pivot class to prevent the need for this.

2017-02-08 23:12 UTC, BrandonShar commented
@GrahamCampbell thanks for the feedback. I'm going to open a separate PR with a refactoring of the Pivot class while I wait for feedback on this proposal.

2017-02-09 00:22 UTC, BrandonShar commented
@GrahamCampbell made the changes you asked for and slightly changed the logic for determining whether to call pivot functions or base model functions that feels less "hacky".

There shouldn't be anything breaking here that would prevent this from being considered in 5.4  If it's definitely only being considered for 5.5 though, I'll make a few PHP7 syntax changes (mainly just the null coalesce operator instead of array_key_exists)

2017-02-09 14:31 UTC, taylorotwell commented
No plans on adding this. I really don't want to over-complicate things.

2017-02-09 14:31 UTC, closed without merging

2017-02-10 02:29 UTC, BrandonShar commented
Understood, thanks for taking a look.

2017-09-10 18:13 UTC, p3ym4n commented
any one planning to add this as a package? or something to make it work unofficially ?

2020-05-04 14:47 UTC, mwargan commented
How are we on this 3 years later? Still can't use Global Scopes on pivot tables?