[5.5] Ensure Arrayable and Jsonable (...) returns a JsonResponse.
laravel/framework pull request #17875
Opened 2017-02-10 16:01 UTC by lucasmichot

For now only a normal Response, mimicing a JsonResponse is returned; this enforces a JsonResponse to be returned.

---

A much more performant way to achieve #17869 /cc @taylorotwell

2017-02-10 17:13 UTC, taylorotwell commented
What is the actual benefit of this?

2017-02-10 17:33 UTC, lucasmichot commented
They are many, in a normal Response, you cannot get and set the encoding option, you cannot set the callback either. 
Within your API middlewares you can never be sure to always expect a JsonResponse too.

2017-02-10 20:07 UTC, taylorotwell commented
I really feel like instead of all this header business you should just check for Arrayable or Jsonable in the `prepareResponse` method of the router.

2017-02-12 11:11 UTC, lucasmichot commented
@taylorotwell , the check is now done in the Router https://github.com/laravel/framework/pull/17875/commits/a7edae88f802b81c7b5e9c4ce98c494273ef8896.

2017-02-12 21:38 UTC, GrahamCampbell commented
👎 This forces people to use json at the router level.

2017-02-12 21:39 UTC, GrahamCampbell commented
What if they wanted a streamed json resource too?

2017-02-13 02:27 UTC, taylorotwell commented
@GrahamCampbell I don't follow. We were returning `Response` before and this just changes Arrayable and Jsonable to convert to `JsonResponse` if a more explicit response type is not provided? Can you give an example of what you mean?

2017-02-14 19:35 UTC, taylorotwell commented
@GrahamCampbell ?

2017-02-16 14:45 UTC, GrahamCampbell requested changes

2017-02-16 14:45 UTC, GrahamCampbell commented on src/Illuminate/Routing/Router.php
> +            if ($response  instanceof Arrayable ||
too many spaces

2017-02-16 14:45 UTC, GrahamCampbell commented
Ah, right, probably fine then.

2017-02-21 14:46 UTC, merged