Improve the dd helper function
laravel/framework pull request #17904
Opened 2017-02-12 21:46 UTC by phroggyy

This PR does two things:

1. If `app.debug` is set to false (which will be default in production), a warning is logged with a message and the calling file and line, adding the supposed `dd` output to the logging context.
2. Display the calling file and line in the start of the regular output, making it easier to know where your `dd` was called from, in case you accidentally left it in there

2017-02-12 23:02 UTC, fernandobandeira commented
Hmm with this it'll still call a ``` die(1) ``` and will result into a blank page, maybe you should also execute ``` die() ``` only in the debug mode, so at least it's fully disabled...

2017-02-12 23:10 UTC, phroggyy commented
@fernandobandeira the idea is to have the behaviour unaltered. The idea is **not** to alter the outcome, as I don't think `dd` should be _disabled_, the idea is rather to not print sensitive information. I personally would be in favour of having it be a proxy for logging, similar to the warning log I added, and not `die`ing, but I think that is quite a large change to make, much larger than this.

2017-02-13 00:42 UTC, GrahamCampbell requested changes

2017-02-13 00:42 UTC, GrahamCampbell commented on src/Illuminate/Support/helpers.php
> +        if (config('app.debug')) {
Bad idea to couple to the config system like that.

2017-02-13 00:53 UTC, rizqidjamaluddin commented on src/Illuminate/Support/helpers.php
> +        if (config('app.debug')) {
What do you think would be a more appropriate toggle? I agree that it's a hidden dependency/coupling, but isn't `app.debug` also how laravel decides when the exception handler should display the exception details vs "something went wrong"? I think it makes sense to  use the same rule.

2017-02-13 02:21 UTC, taylorotwell commented
Rather than doing this I think I would rather just let people define their own dump helpers if they need this behavior.

2017-02-13 02:21 UTC, closed without merging

2017-02-13 11:00 UTC, rizqidjamaluddin commented
I was _just_ handling a security situation last night because of a stray `dd` being left behind and never caught by tests, accidentally leaking key information that resulted in a severe breach. And I know for certain that "I left a `dd` in by accident" is a very common mistake that can also be frustrating to track down. It seems to me that not disclosing internal data in production would be a sensible security default, similar to how exceptions and their stack traces don't get shown on production settings.

Granted, it's trivial to extend the function or replace it, but good defaults and all, eh. It's sort of breaking, though, for people actually using `dd` for "spit out JSON and exit request".

2017-02-13 11:11 UTC, phroggyy commented
With regards to it being breaking @rizqidjamaluddin that was something I considered too. My reasoning for targeting 5.4 was "I might as well try to get a security thing in as early as possible", with the worst case scenario being moving it to 5.5. That said, I would like @taylorotwell to reconsider this, at least for 5.5 since, as mentioned, good defaults and all.

2017-02-13 11:17 UTC, crynobone commented
Should be possible to just override `VarDumper::$handler` from service provider, and have the logic executed there.

https://github.com/symfony/var-dumper/blob/master/VarDumper.php#L41

2017-02-13 11:18 UTC, phroggyy commented
@crynobone the current `dd` function does not resolve the `Dumper` from the IoC container, it executes `(new Dumper)->dump`