Added UUID validation rule
laravel/framework pull request #18008
Opened 2017-02-20 08:54 UTC by robinvdvleuten

Hi there,

I've added a validation rule to check for a valid UUID. It's very common nowadays to use UUIDs as unique identifiers and it's looks very handy to me to have common validation support for this in the Laravel framework. 
The [ramsey/uuid](https://github.com/ramsey/uuid) library is already a dependency of the Laravel framework so I've added it as extra dependency to the subtree split. You can even think of adding it to the "suggested" packages so you have to install it yourself when using the validation component as standalone.

2017-02-20 11:11 UTC, lucasmichot commented on src/Illuminate/Validation/Concerns/ValidatesAttributes.php
> +     * @param string  $attibute
Maybe a good opportunity to fix this docblock too.

2017-02-20 11:56 UTC, GrahamCampbell requested changes

2017-02-20 11:56 UTC, GrahamCampbell commented on src/Illuminate/Validation/composer.json
> +        "ramsey/uuid": "~3.0",
👎 Should be added to the suggest block only please.

2017-02-20 12:02 UTC, robinvdvleuten commented on src/Illuminate/Validation/composer.json
> +        "ramsey/uuid": "~3.0",
Consider it done 😄

2017-02-20 13:39 UTC, taylorotwell commented
There are different types of UUIDs. Suggest using custom validator extension.

2017-02-20 13:39 UTC, closed without merging

2017-02-20 13:42 UTC, robinvdvleuten commented
@taylorotwell The `isValid()` method has support for multiple variants of UUIDs, as mentioned in the [docblock](https://github.com/ramsey/uuid/blob/master/src/Uuid.php#L94).

2017-04-05 14:18 UTC, jbruni commented
Suggestion taken from https://github.com/webpatser/laravel-uuid/issues/5#issuecomment-275031149:

```php
Validator::extend('uuid', function ($attribute, $value, $parameters, $validator) {
    return (bool) preg_match('/^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$/', $value);
});
```