Don't fail if no file to email
laravel/framework pull request #18247
Opened 2017-03-07 21:29 UTC by jamesalton

Avoid failing because we can't open the file to email.

This prevents the following error:
```
[2017-03-07 20:44:56] production.ERROR: ErrorException: file_get_contents(/web/LaravelLogs/check-approved-2017-03-07T13:44:55-07:00.
log): failed to open stream: No such file or directory in /web/vendor/laravel/framework/src/Illuminate/Console/Scheduling/Event.php:408
```

To replicate the error, delete the zero length file in the $schedule method chain's `->after(function())`.

2017-03-08 00:20 UTC, GrahamCampbell requested changes

2017-03-08 00:20 UTC, GrahamCampbell commented on src/Illuminate/Console/Scheduling/Event.php
> +        } catch (Exception $e) {
Probably a bad idea to catch all like this.

2017-03-08 13:30 UTC, taylorotwell commented
1) this is to wrong branch. 2) we should just use a simple file_exists. I will fix it on the right branch.

2017-03-08 13:30 UTC, closed without merging

2017-03-09 19:10 UTC, jamesalton commented
Thanks @taylorotwell