[5.4] Fluent partial resource routes
laravel/framework pull request #18393
Opened 2017-03-17 14:57 UTC by salomoni

Discussed in https://github.com/laravel/internals/issues/412

In 5.4 you can register routes more fluently e.g.

```php
Route::name('users.index')->get('users', 'UserController@index');
```

It would be nice to get same behaviour for registering partial resource routes e.g. 

```php
Route::resource('users', 'UserController')->only('index', 'show');

Route::resource('comments', 'CommentController')->except('destroy');

Route::resource('posts', 'PostController')->only(
    'index', 'show', 'store', 'update', 'destroy'
);
```

2017-03-19 01:50 UTC, JosephSilber commented
This relies heavily on GC.

Is it guaranteed to run before the actual route is matched? Or before the routes are cached?

2017-03-19 15:50 UTC, GrahamCampbell commented
@JosephSilber is correct. This implement is not guaranteed to be correct.

2017-03-19 15:50 UTC, GrahamCampbell commented
👎

2017-03-20 09:37 UTC, salomoni commented
Implemented now in the other way proposed https://github.com/laravel/internals/issues/412#issuecomment-280303057

Now `only` and `except` removes registered routes from the `RouteCollection`.

2017-03-23 14:27 UTC, taylorotwell commented
If the PHP manual is correct, then yes the implementation is guranteed to be correct:

"The destructor method will be called **as soon as there are no other references to a particular object**"

2017-03-23 14:45 UTC, JosephSilber commented
I doubt that is to be taken so literal.

There's no way for the runtime to know that there are no longer any references to an object. The only way to know that is at the end of a GC cycle.

2017-03-23 15:12 UTC, GrahamCampbell commented
I don't think the PHP manual is correct. It is up to the garbage collector to look for objects with a zero refcount.

2017-03-23 15:27 UTC, taylorotwell commented
So you're going to submit a PR to the PHP documentation to fix it? It states it very specifically in several places :)

2017-03-23 15:27 UTC, taylorotwell commented
And if this is the case, should we take ANYTHING in the PHP manual literally? If so, why?

2017-03-23 15:40 UTC, browner12 commented
I'll add my two cents from personal experience, I've had less than stellar results when dealing with destructors. It seemed to be very difficult to rely on when it was run.

2017-03-25 00:44 UTC, taylorotwell commented
I would actually be very interested if someone can show a situation where it is not run as soon as there are no other references to the object.

2017-03-25 01:52 UTC, GrahamCampbell commented
> I would actually be very interested if someone can show a situation where it is not run as soon as there are no other references to the object like the documentation states.

By its very nature, it's non-deterministic, so, it's hard to provide an example and make any guarantees about when garbage collection will take place.

2017-03-25 01:59 UTC, GrahamCampbell commented
That said, I was unable to get PHP to call these destructors in an "incorrect" order: https://3v4l.org/qUD51. Maybe there's an ordering by the garbage collector, just due to the implementation specifics?

2017-03-25 02:10 UTC, GrahamCampbell commented
There are definitely user error cases I can think of though. Will write an example.

2017-03-25 02:12 UTC, GrahamCampbell commented
Here we go: https://3v4l.org/ihpuf.

The application runs to completion, before the route gets registered,

2017-03-25 02:15 UTC, GrahamCampbell commented
In terms of the PR, I actually already have a big problem with it, the `register` method is not supposed to return anything, but now it does...

(and if the programmer actually leaves a reference to the returned value somewhere, they are screwed)

2017-03-25 02:16 UTC, GrahamCampbell commented
For that reason, I think this should be a 5.5 change, because it changes the contract.

2017-03-25 02:17 UTC, GrahamCampbell commented
An implementation to avoid using destructors, would be for the registra to keep a queue of pending routes, and call some resolve method on them all, before we try to match anything.

2017-03-30 13:26 UTC, salomoni commented
Thank you @GrahamCampbell for your time!

I implemented this once again based on your suggestion.

2017-04-06 18:22 UTC, taylorotwell commented
This really was cleaner using destructors tbh, even though some are scared they aren't called when the PHP docs say they are called. Graham's code example is not really reflective of an actual Laravel routes file.

2017-04-06 19:31 UTC, GrahamCampbell commented
> Graham's code example is not really reflective of an actual Laravel routes file.

There's no reason to assume that people do routing in that way. I don't always.

2017-04-06 19:32 UTC, GrahamCampbell commented
This solution is robust. And I don't think it's any worse than the destructor way tbh.

2017-04-06 19:33 UTC, GrahamCampbell requested changes

2017-04-06 19:33 UTC, GrahamCampbell commented on src/Illuminate/Contracts/Routing/Registrar.php
> +     * @return \Illuminate\Routing\PendingResourceRegistration
this PR should target 5.5, because this is a breaking change to the interface, requiring implementations to return this object

2017-04-06 19:45 UTC, taylorotwell commented
Is this not changing the entire order of when your routes are registered though? Now the resource routes aren't *actually* registered until a later time and that makes a difference when registering things.

2017-04-06 19:46 UTC, taylorotwell commented
Also I still haven't seen an actual case that won't work with the destructor approach. 😬

2017-04-06 20:05 UTC, GrahamCampbell commented
> Also I still haven't seen an actual case that won't work with the destructor approach.

Yeh, u have. :trollface: That example where I showed the variable living beyond the scope we wanted it to. I mean, I could write a laravel app that demonstrates it, but I can't really be arsed.

The point is, that if a route remains referenced, after routing happens, then it won't have ever been registered. It's likely people would do this by mistake, but it's very hard for them to debug, if they don't understand the internals.

2017-04-06 20:29 UTC, JosephSilber commented
The point here is more than that. Even if you don't have a reference to it anymore, there's no guarantee when GC will run.

PHP's docs be damned.

2017-04-06 20:37 UTC, GrahamCampbell commented
> there's no guarantee when GC will run.

While that is true, I haven't been to actually get PHP to not garbage collect in time in my testing to try to break it.

2017-04-06 20:40 UTC, JosephSilber commented
@GrahamCampbell that's not enough to actually build a feature on top of.

2017-04-06 20:47 UTC, GrahamCampbell commented
> that's not enough to actually build a feature on top of.

I agree, that's why I asked for this to be implemented without using that, and it now has been.

2017-04-07 19:53 UTC, salomoni commented on src/Illuminate/Contracts/Routing/Registrar.php
> +     * @return \Illuminate\Routing\PendingResourceRegistration
A newbie question: does this require any actions by me? My first PR 🥇

2017-04-08 08:45 UTC, salomoni commented
The resources are currently registered only once so calling `only` or `except` methods after registration has no effect.

Should they?

Pending resources could just be marked as registered and exception thrown if tried to limit/exclude methods afterwards.

Registering resources in the RouteCollection each time needed is a little overkill imo. There might e.g. be several `route('users.index')` calls  in the templates.

2017-04-10 14:23 UTC, taylorotwell commented
If you want to re-submit this using the original, simple approach I suggested go for it. I can't really subscribe to the view that the PHP documentation is not to be trusted because then we can't program anything in this language at all to be honest. I will function as if the documentation is true. If it is not, it should be fixed.

2017-04-10 14:23 UTC, closed without merging

2017-04-10 16:32 UTC, GrahamCampbell commented
For what it's worth 👎 On the original approach. This new approach is much better IMO. (ultimately, do what taylor says tho, he da boss)