[5.4] Added a way to validate user credentials using the TokenGuard
laravel/framework pull request #19095
Opened 2017-05-07 17:29 UTC by kevinvdburgt

When only using the TokenGuard in a Laravel project, you are unable to authenicate yourself. This might be an idea how to authenticate yourself using the TokenGuard.

2017-05-07 18:28 UTC, tillkruss requested changes

2017-05-07 18:28 UTC, tillkruss commented on tests/Auth/AuthTokenGuardTest.php
> +    // }
Mind adding tests here?

2017-05-07 19:09 UTC, kevinvdburgt commented on tests/Auth/AuthTokenGuardTest.php
> +    // }
Sure :) , i will add those later today!

2017-05-07 20:25 UTC, ntzm commented on src/Illuminate/Auth/TokenGuard.php
> +    protected function hasValidCredentials($user, $credentials)
You can type-hint array for $credentials here

2017-05-08 03:41 UTC, kevinvdburgt commented on src/Illuminate/Auth/TokenGuard.php
> +    protected function hasValidCredentials($user, $credentials)
Thanks! i will add those type-hinting 👍

2017-05-08 12:43 UTC, taylorotwell commented
I don't know what you mean by "unable to authenticate yourself". Can you explain in much more detail what you are trying to do?

2017-05-09 07:34 UTC, kevinvdburgt commented
@taylorotwell when only using the token driver, you can only validate the `api_token` but not the user credentials without the (for example) session driver.

With the addition i can validate the user credentials by email and password:
```php
$credentials = $request->only(['email', 'password']);
$guard = $request->guard;

$validated = Auth::guard($guard)->validateCredentials($credentials);
```

2017-05-09 09:17 UTC, phroggyy commented
@kevinvdburgt not sure what you mean... If you use email and password, you shouldn't use the token guard. The entire point of the token guard is to authenticate with a token, or am I missing something?

2017-05-09 09:20 UTC, kevinvdburgt commented
@phroggyy That is true, but how can you create the token in the first place with only the token driver (for building a RESTful application), without using the session driver?

2017-05-09 12:43 UTC, taylorotwell commented
I don't think this is the right approach.

2017-05-09 12:43 UTC, closed without merging

2017-05-09 12:46 UTC, kevinvdburgt commented
@taylorotwell Do you have the right approach maybe, or something in that direction :) ?