Support for standard object (stdClass)
laravel/framework pull request #19840
Opened 2017-06-30 14:29 UTC by wffranco

Support convertion of standard objects to json

2017-06-30 14:42 UTC, jhoff requested changes

2017-06-30 14:42 UTC, jhoff commented on src/Illuminate/Http/Response.php
> +use stdClass;
use statements should be ordered by length.

2017-06-30 15:22 UTC, tillkruss commented
Mind adding a test for this?

2017-06-30 18:55 UTC, taylorotwell commented
Just do `return (array) $object;` from your controller.

2017-06-30 18:55 UTC, closed without merging

2017-11-21 08:06 UTC, wffranco commented
Sorry for the delay in responding.
@jhoff I did not know that rule, thanks for that.

@taylorotwell the problem is converting data to JSON, and your solution don't work in many cases, I will try to explain it fast.

Suppose you have one JSON attribute in a model that can get that structure: `{"a":"test","b": 5}`
This attribute have a getter: `return json_decode($value);`, that return a standard object (stdClass)

PHP always transform associative arrays in objects. Only empty arrays `[]` and ordered numeric arrays will be treated as arrays. Numeric arrays with missing numbers will be objects.

So I got 2 problems when I needed the full data to JSON.

- First problem: Empty array `[]` or casting empty objects `(array) $object` will return array instead of object.
- Second problem: Handling nested objects or collections, this could need a lot of mapping or mutations to get the proper results.

With that little fix they could be transformed properly.

In fact, casting `(object) $array` fix problems with some empty arrays that could be objects.