[5.5] Migrate drop command
laravel/framework pull request #20516
Opened 2017-08-11 15:55 UTC by lkmadushan

Command to drop all database tables at once.

I will refactor migrate:fresh command to use this if this gets accepted :)

2017-08-11 17:05 UTC, m1guelpf requested changes

2017-08-11 17:05 UTC, m1guelpf commented on src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php
> +        $this->app->singleton('command.migrate.rollback', function ($app) {
The singleton should be 'command.migrate.drop'

2017-08-11 18:26 UTC, srmklive commented
No need for it in my opinion. You can accomplish the same task with `migrate:reset`.

2017-08-11 18:40 UTC, lkmadushan commented
@srmklive This can be useful if someone wants to drop all tables at once without going through any UI. migrate:reset could throw errors some situations.

2017-08-11 18:50 UTC, browner12 commented
can you explain the use case for dropping all the tables, but *not* migrating after that?

2017-08-12 17:42 UTC, lkmadushan commented
@browner12 no idea. but hope this will be helpful for DatabaseMigrations when testing

2017-08-14 19:35 UTC, taylorotwell commented
No plans to add at this time.

2017-08-14 19:35 UTC, closed without merging