[5.5] Eloquent model without updated_at field
laravel/framework pull request #21178
Opened 2017-09-13 22:10 UTC by linaspasv

Since Laravel 5.0 many found a simple method to have eloquent models without updated_at field. Unfortunatelly this is not a thing in Laravel 5.5 anymore ( #19627 #21045 #20901 #20930 ...)

e.g. how it was used before Laravel 5.5

```php
class MyModel extends Model
{
    const UPDATED_AT = null;
}
```

I do understand it's not an official method but since we do lack flexibility on the subject, please, leave this behaviour as it was working before...

2017-09-13 22:39 UTC, antonkomarev requested changes
Why do we need nested conditional statement when `&&` could be used?
```php
if (static::UPDATED_AT !== null && ! $this->isDirty(static::UPDATED_AT)) {
    $this->setUpdatedAt($time);
}
```

2017-09-14 11:49 UTC, themsaid commented
This was proposed in https://github.com/laravel/framework/pull/20930 and rejected.

Just referencing.

2017-09-14 12:06 UTC, linaspasv commented
@themsaid correct but I see too many people, including me, were using like so before the Laravel 5.5. This PR doesn't add any new behaviour like proposed in #20930 , just brings back the use-case of Laravel 5.0-5.4 for the time being.

2017-09-14 12:39 UTC, merged

2017-09-14 12:42 UTC, linaspasv commented
@taylorotwell thanks!

2017-09-20 12:14 UTC, segadora commented
This will conflict with `SoftDeletes`

https://github.com/laravel/framework/blob/5bd7c77352b9dacbb3e22ad32da232febbca8e3c/src/Illuminate/Database/Eloquent/SoftDeletes.php#L69-L72

It should also be supported there.

2017-09-20 22:57 UTC, linaspasv commented
@segadora thank you for spotting this!

@slarmehr many are using null for UPDATED_AT, so maybe empty check could cover both cases (otherwise it's a breaking change), you might try to file a PR for letting use false too. I do agree false might feel a bit more natural.

2017-09-20 23:00 UTC, salarmehr commented
@segadora Thanks for your comment. My comment mainly refer to a defect in Model class structure itself.

2017-09-20 23:53 UTC, a-komarev commented
@linaspasv As I remember I've tried to change this value to false and got same result.

2017-09-21 09:22 UTC, segadora commented
@linaspasv I will agree with a empty check.

2017-09-29 13:03 UTC, a-komarev commented
@pdbreen it would be better to turn off timestamps for such case and manage them manually as you proposed.