Make request accessible in password reset responses
laravel/framework pull request #21662
Opened 2017-10-13 23:29 UTC by hafezdivandari

It's necessary to access `$request` for customization of `sendResetResponse()` in `\Illuminate\Foundation\Auth\ResetsPasswords` and `sendResetLinkResponse()` in `\Illuminate\Foundation\Auth\SendsPasswordResetEmails`.

2017-10-14 09:01 UTC, m1guelpf commented
This is breaking and should go to master

2017-10-14 09:14 UTC, GrahamCampbell requested changes

2017-10-14 09:14 UTC, GrahamCampbell commented on src/Illuminate/Foundation/Auth/SendsPasswordResetEmails.php
> +     * @param  \Illuminate\Http\Request
Missing param name. :)

2017-10-14 09:46 UTC, hafezdivandari commented on src/Illuminate/Foundation/Auth/SendsPasswordResetEmails.php
> +     * @param  \Illuminate\Http\Request
Missing param names added.

2017-10-15 15:01 UTC, gabriel-caruso commented
@hafezdivandari Rebase your branch, it would avoid many commits to `master` :smile:

2017-10-20 13:01 UTC, taylorotwell commented
Honestly you can just use the `request()` helper rather than us making this breaking change.

2017-10-20 13:01 UTC, closed without merging