[5.5] Check if ability is defined using resource method
laravel/framework pull request #21845
Opened 2017-10-27 16:46 UTC by mputkowski

This PR fixes bug with policies which doesn't work properly with abilities registered using "Resource Gates" due to special format of it (eg. `posts.view`).

Mentioned bug occurs because "callable check" always returns false when ability is defined by resource.
```
if (! is_callable([$policy, $this->formatAbilityToMethod($ability)])) {
   return false;
}
```
For example, let's assume that ability is `posts.view`, this statement checks if `posts.view` method is callable instead of checking method associated with registered ability (which makes sense). Method `resolvePolicyCallback` returns false, rest of code isn't executed and as a result before method can't be called.

### Solution
Gate have to check type of ability, properly get method name and then make sure if method is callable.

2017-10-28 04:04 UTC, tillkruss requested changes

2017-10-28 04:04 UTC, tillkruss commented on src/Illuminate/Auth/Access/Gate.php
> +        $callback = strpos($ability, '.')
Can you make the `strpos()` check strict, please?

2017-10-28 14:20 UTC, taylorotwell commented
Can someone explain this more clearly?

2017-10-28 16:26 UTC, mputkowski commented
@taylorotwell Generally it refers to docs ([upgrade guide](https://laravel.com/docs/5.5/upgrade)).

> The before method of a policy class will not be called if the class doesn't contain a method with name matching the name of the ability being checked.

```php
Gate::resource('name', 'App\Policies\ExamplePolicy', [
   'ability' => 'method',
]);
```
So when we register ability using resource method it will have format  `name.ability`. As we all know we aren't able to create function named `name.ability` due PHP limitations.

> A valid function name starts with a letter or underscore, followed by any number of letters, numbers, or underscores.

### Steps To Reproduce
First create model `php artisan make:model Example`

Define abilities in `AuthServiceProvider` (boot method)
```php
Gate::define('ability', 'App\Policies\ExamplePolicy@ability');

// It will be tested later
//Gate::resource('name', 'App\Policies\ExamplePolicy', [
//   'ability' => 'ability',
//]);
```
Map policy in `policies` array
```php
protected $policies = [
   'App\Example' => 'App\Policies\ExamplePolicy',
];
```
Create `ability` and `before` methods in `ExamplePolicy` class
```php
public function ability(User $user, \App\Example $example)
{
   dd('ability is called');
}

public function before(User $user, $ability)
{
   dd('before is called');
}
```
In any controller (e.g. `HomeController`)
```php
$ability = Gate::allows('ability', new \App\Example);
```
After all, you should see `before is called` in browser. Let's switch to `resource` method.
```php
//Gate::define('ability', 'App\Policies\ExamplePolicy@ability');

// It will be tested later
Gate::resource('name', 'App\Policies\ExamplePolicy', [
   'ability' => 'ability',
]);
```
Now you have to change ability in `allows` method
```php
$ability = Gate::allows('name.ability', new \App\Example);
```
After refresh you'll see `ability is called` instead of `before is called`.
### Solution
I had to change first if-statement in `resolvePolicyCallback` method because it's not working with resource abilities (`is_callable([App\Policies\ExamplePolicy::class, 'name.ability'])` will always return false).
```php
if (! is_callable([$policy, $this->formatAbilityToMethod($ability)]))
```
In this PR Gate checks "type of ability" (registered with resource or define methods). If ability is registered using resource - `$callback` will be set to `$this->abilities[$ability]` (each item in array contains callback so it can be used to check if it's callable, `dd()` this array will give you more details).

If you have any questions just ask.

2017-10-29 08:49 UTC, themsaid requested changes
Now the policy method will never get called, also if the ability isn't defined a `Undefined index` exception will be thrown from `$this->abilities[$ability]`, currently if the ability is not defined the gate will just return `false`.

I'm also worried that this would be considered a breaking change, people relying on the fact that `before` is not called when the ability is defined in a certain way might start having troubles.

I recommend that you re-attempt this on the master branch, so we can make sure it works before next release and announce the change in behaviour.

2017-10-29 14:11 UTC, mputkowski commented
@themsaid So this PR didn't entirely fix policies, the problem persists... I have to find better way.

I'll try to fix this in next weekend because I'm a little bit busy. Have I to create new PR or pull changes here?

2017-10-29 14:12 UTC, themsaid commented
@mputkowski a new PR targeting master would be better imo.

2017-10-29 14:12 UTC, closed without merging