[5.5] Add assertValidationErrors and assertJsonCount to TestResponse
laravel/framework pull request #21917
Opened 2017-11-01 20:45 UTC by Gimcrack

This commit adds two assert helpers to the TestResponse class.

# assertValidationErrors( string|array $keys )
Asserts that the given key(s) are in the **`errors`** key of the Json response.

## Sample use case - validating a new user
``` 
// UserController@store
$request->validate([
    'first_name' => 'required',
    'last_name' => 'required'
]);

// Feature/UserTest
$this->post('users', [
    'first_name' => null,
    'last_name' => null
]);

$this
  ->response()
  ->assertValidationErrors(['first_name','last_name']);

// sample response
array:2 [
  "message" => "The given data was invalid."
  "errors" => array:2 [
    "first_name" => array:1 [
      0 => "The first_name field is required."
    ],
    "last_name" => array:1 [
      0 => "The last_name field is required."
    ]
  ]
]

// the test passes
```

# assertJsonCount( int $count )
Asserts that the response data has the expected count.

##  Sample use case - getting a user resource index

```
// Feature/UserTest
/** @test */
public function it_can_get_a_listing_of_users()
{
    $users = factory(User::class,3)->create();

    $this->get("users");

    $this->response()
        ->assertStatus(200)
        ->assertJsonCount(3);
}
```

2017-11-02 01:07 UTC, thecrypticace commented
I really like `assertJsonCount`. It's a good option for when you need to assert that you received only N records in an array. `assertJson` deals in fragments so it is unable to cover this case and `assertExactJson` can end up being too verbose if you're asserting on targeted data.

However, this does not work as expected if all your responses have a top-level data key (or something similar) How about adding an optional key (w/ a default value of `null`) It would allow assertions on data like so:

```php
$response->assertJsonCount(3, "data")
$response->assertJsonCount(9, "data.*.contacts")
```

You should be able to assertCount on the result of `data_get($this->json(), $key)` as, iirc, `data_get` will return the original array if you pass `null`

2017-11-02 01:25 UTC, carusogabriel requested changes
Fix this PHP Docblocks and you're ready to go :smile:

2017-11-02 01:25 UTC, gabriel-caruso commented on src/Illuminate/Foundation/Testing/TestResponse.php
> +     *
This should be:
```php
/**
 * Assert that the response json has the expected count.
 *
 * @param int $count
 * @return $this
 */
```

2017-11-02 01:25 UTC, gabriel-caruso commented on src/Illuminate/Foundation/Testing/TestResponse.php
> +     *
This should be:
```php
/**
 * Assert that the response has validation errors for the given keys.
 *
 * @param string|array $keys
 * @return $this
 */
```

2017-11-02 05:23 UTC, Dylan-DPC commented
I think it is better to have a provision for custom validation messages and localisation

2017-11-02 12:43 UTC, taylorotwell commented
I agree that assertJsonCount isn't very helpful without being able to provide a key.

2017-11-03 00:12 UTC, Gimcrack commented
@taylorotwell Good catch. Now if you are using pagination or similar you can specify a key.
```
$this->response()->assertJsonCount(3, 'data');
```

2017-11-03 04:37 UTC, gabriel-caruso commented
Rebase your commits to a single one 😊

If you don’t know how: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

2017-11-03 05:35 UTC, Dylan-DPC commented
@gabriel-caruso there is an option to squash while merging the PR. So Taylor can take care of that

2017-11-03 05:44 UTC, gabriel-caruso commented
@Dylan-DPC Oh, I didn’t know about this option 😱😍

2017-11-06 21:51 UTC, merged

2017-11-09 19:48 UTC, mvdnbrk commented
In the [release notes](https://github.com/laravel/framework/releases/tag/v5.5.20) this is mentioned as added `assertValidationErrors`. Taylor changed this to `assertJsonValidationErrors`. :smile: