[5.5] Add GCM support to encrypter
laravel/framework pull request #21963
Opened 2017-11-05 18:20 UTC by bukka

This PR adds support for AES GCM  ciphers with 128 or 256 bit key. The default is still the same (CBC) so it should be fine for 5.5 I guess (not sure what the rules are thought so happy to create a PR for 5.6 only).

I added GCM support to openssl ext in 7.1 so it's available only for PHP version higher or equal to 7.1.

2017-11-05 21:21 UTC, GrahamCampbell requested changes

2017-11-05 21:21 UTC, GrahamCampbell commented on tests/Encryption/EncrypterTest.php
> +        $this->onlyForAead();
Just use the `@requires PHP 7.1` annotation.

2017-11-05 21:21 UTC, GrahamCampbell commented on tests/Encryption/EncrypterTest.php
> +        $this->onlyForAead();
And drop the extra method. :)

2017-11-05 21:43 UTC, taylorotwell commented
No plans to add this to the core.

2017-11-05 21:43 UTC, closed without merging

2017-11-05 21:59 UTC, GrahamCampbell commented
What are the benefits of GCM? Maybe make a package, and see if i gets traction?

2017-11-06 11:03 UTC, bukka commented
@GrahamCampbell I think that the main benefit is a better performance in this context. The GCM doesn't need an extra MAC creation / validation as it's all done when applying mode during encryption / decryption. All is fully handled by `openssl_encrypt` / `openssl_decrypt`.

@taylorotwell I'd be interested to know the reason why you prefer not to have it in the core. Is it just because you prefer to have a very thin encrypter with a single alg supported? Or would you prefer a different more extendable implementation? I'm also wondering what are your thoughts about more standard output format like JWE which would also allow additional key protection?

2017-12-14 15:17 UTC, davidstanley01 commented
@taylorotwell why no plans for this?

2021-08-20 11:33 UTC, Krisell commented
@bukka I'm sorry this discussion didn't move on. GCM support was recently added to Laravel but with some minor issues, that your PR solved. I used your PR as inspiration for a new to fix the issues: https://github.com/laravel/framework/pull/38475

Thank you for this work back in 2017!