[Database] Autowire migrations
laravel/framework pull request #21999
Opened 2017-11-07 21:55 UTC by abellion

This PR makes use of the container to autowire the migrations instances.

2017-11-07 22:58 UTC, ntzm commented on src/Illuminate/Database/Migrations/Migrator.php
>       * @param  \Illuminate\Filesystem\Filesystem  $files
Needs adding to DocBlock

2017-11-07 23:00 UTC, browner12 commented
is there any immediate benefit from this? or is it more for consistency?

2017-11-07 23:52 UTC, GrahamCampbell requested changes

2017-11-07 23:52 UTC, GrahamCampbell commented on src/Illuminate/Database/Migrations/Migrator.php
> +use Illuminate\Container\Container;
Probably should use the contact here instead.

2017-11-08 07:00 UTC, sisve commented
We've had migrations that weren't resolved from the container for several years now, why do we need it now? When do you need to resolve services to modify your database schema?

2017-11-08 08:25 UTC, deleugpn commented
I know it's almost irrelevant, but this brings a performance impact as the Reflector will be used to instantiated migration classes. The reason I bring this up is that if there is no upside at all for this, we can see a tiny downside.

Also, tests are failing.

2017-11-08 09:30 UTC, abellion commented
For consistency yes, and because we use MondoDB as our primary data storage and for some reasons we need services from the container. I think the performance impact is so tiny it shouldn't be a problem. I'm going to fix the tests.

2017-11-08 10:33 UTC, sisve commented
Let's talk about breaking changes. What are we talking about here? In which scenarios will things blow up? Can third party packages be compatible with the current Migrator class _and_ these new changes at the same time?

2017-11-08 10:38 UTC, deleugpn commented
I agree. Talk about performance is pointless if there is a visible improvement. I only brought it up because we cannot see the improvement here. It would be nice to know how you're setting up MongoDB with migrations and how this solve that.

@sisve I don't think there's any breaking changes here. If we assume that nobody is binding the migration classes into the container, this will auto-wire the class regularly.
If somebody is binding it to the container, the container will just resolve the bound one, which seems the intended behavior. The reason I think nobody is binding it is because the migrator was not resolving it anyway.

2017-11-08 10:51 UTC, abellion commented
Actually our own use case is related to MongoDB services, but I can imagine it's far from being the only one. I just don't see what's the benefit of NOT having these class autowired ?

BC layer should not be a problem as the class were constructed without any arguments (ie. an exception would be thrown). Except for default parameters I guess, but the container is taking care of them.

2017-11-08 10:54 UTC, sisve commented
@deleugpn @abellion You're changing a method signature (Migrator::__construct). How would anyone that has derived from the class and implemented their own constructor be compatible with current and next version of the Migrator if there are two different parent::__construct to call?

2017-11-08 13:58 UTC, closed without merging

2017-11-08 17:05 UTC, abellion commented
@taylorotwell @GrahamCampbell Can you explain why it has been closed ?

2017-11-08 17:28 UTC, browner12 commented
all we currently see in this PR is change for change's sake.  can you explain your use case, and what the benefit of this would actually be?

2017-11-08 18:33 UTC, abellion commented
We are using an internal tool do deal with MongoDB, that needs to be autowired.
Today we use the `app()` function to get the services, but it feels weird and inconsistant. 

> Actually our own use case is related to MongoDB services, but I can imagine it's far from being the only one. I just don't see what's the benefit of NOT having these class autowired ?

2017-11-08 18:33 UTC, abellion commented
We are using an internal tool do deal with MongoDB, that needs to be autowired.
Today we use the `app()` function to get the services, but it feels weird and inconsistant. 

> Actually our own use case is related to MongoDB services, but I can imagine it's far from being the only one. I just don't see what's the benefit of NOT having these class autowired ?