[5.5] Fix SQLite delete for complex delete statements
laravel/framework pull request #22298
Opened 2017-12-04 16:03 UTC by abdumu

Current SQLite delete implementation lack the support for complex statement like joins, or limits. This may lead to serious loss of data.

Current approach of SQLite delete: 

`> App\Post::latest('id')->limit(1)->delete();`
`=> 48 (deleted rows)`

`=> "query" => "delete from "posts""`

new approach:

`> App\Post::latest('id')->limit(1)->delete();`
`=> 1 (deleted rows)`

`=>  "query" => "delete from "posts" where "rowid" in (select "posts"."rowid" from "posts" order by "id" desc limit 1)"`

Also, this fixes the https://github.com/laravel/framework/pull/22239 for SQLite.

2017-12-04 21:37 UTC, deleugpn commented on src/Illuminate/Database/Query/Grammars/SQLiteGrammar.php
> +        // We use select statment as a subquery to overcome this delimma.
Typo

2017-12-04 21:38 UTC, deleugpn commented
Cool solution.

2017-12-05 07:26 UTC, themsaid commented
Since it's sqlite it's pretty easy to add integration tests, please add a test in `tests/Integration/Database` with the cases this PR fixes.

2017-12-05 07:26 UTC, themsaid requested changes
Since it's sqlite it's pretty easy to add integration tests, please add a test in tests/Integration/Database with the cases this PR fixes.

2017-12-05 08:16 UTC, ntzm commented on src/Illuminate/Database/Query/Grammars/SQLiteGrammar.php
> +            return trim(
I don't think this `trim` is needed

2017-12-06 14:08 UTC, merged