[5.6] Use valid property when assigning threads for ArgonHasher
laravel/framework pull request #22674
Opened 2018-01-06 14:19 UTC by mnabialek

I might be wrong but it seems that `setProcessors` method should use `processors` property and not unexisting `threads` property. @morloderex  You can take a look to confirm as you were creating this class in https://github.com/laravel/framework/pull/21885

2018-01-06 14:33 UTC, deleugpn commented
If that's the case, should we also rename the parameter?

2018-01-06 15:08 UTC, mnabialek commented
Well, we could then it should be decided whether processors or threads is used and it means multiple changes in this class

2018-01-06 15:51 UTC, morloderex commented
Yes you are right. Unfortunalty there is a typo in my original pr.
I also think that @mnabialek  is right we should change the parameter name in the process.

2018-01-06 15:57 UTC, taylorotwell commented
Please make it all match then.

2018-01-06 16:06 UTC, mnabialek commented
Updated to `threads` to avoid confusion when looking at http://php.net/manual/en/function.password-hash.php

2018-01-06 16:08 UTC, GrahamCampbell requested changes

2018-01-06 16:08 UTC, GrahamCampbell commented on src/Illuminate/Hashing/ArgonHasher.php
>       * @param $options
That line is also invalid phpdoc, unrelated to this PR, but might as well be fixed up.

2018-01-06 16:13 UTC, morloderex commented
@mnabialek I think processors here makes more sense. Its just like when @taylorotwell is using rounds instead of cost.

2018-01-07 08:46 UTC, mnabialek commented
@GrahamCampbell I've updated phpdoc

2018-01-07 14:56 UTC, merged