[5.5] Make sure string is passed to hash_equals
laravel/framework pull request #22718
Opened 2018-01-09 20:04 UTC by mnabialek

As mentioned in https://github.com/laravel/framework/issues/22717 if `hash_equals` get non-string we might get for example:

> hash_equals(): Expected known_string to be a string, boolean given

so it's better to cast token to string here

2018-01-09 21:29 UTC, GrahamCampbell requested changes

2018-01-09 21:29 UTC, GrahamCampbell commented on src/Illuminate/Auth/EloquentUserProvider.php
> +        $rememberToken = (string) $model->getRememberToken();
I don't think this is the correct fix. Surely the correct fix is to fix `getRememberToken` to always return a string?

2018-01-09 22:07 UTC, mnabialek commented
@GrahamCampbell I agree but it could be then breaking change in such case so I think it's safer to do it here

2018-01-09 22:34 UTC, GrahamCampbell commented
It's not a breaking change, it's a bug fix.

2018-01-10 05:37 UTC, sisve commented
I agree with @GrahamCampbell, `$user->getRememberToken()` should only return string or null. (The docblocks only mention the string). It should never return a boolean.

2018-01-10 08:21 UTC, mnabialek commented
Ok, I'm closing this and added https://github.com/laravel/framework/pull/22724 instead

2018-01-10 08:21 UTC, closed without merging