fix file name for empty extension
laravel/framework pull request #23009
Opened 2018-02-02 23:04 UTC by betterapp

On Windows system php can't write file when there is no extension.

2018-02-03 21:12 UTC, GrahamCampbell requested changes

2018-02-03 21:12 UTC, GrahamCampbell commented on src/Illuminate/Http/FileHelpers.php
> +        return $path.$hash.(empty($extension) ? '' : '.'.$extension);
The following may be cleaner:

```php
    $hash = $this->hashName ?: $this->hashName = Str::random(40);
    $extension = $this->guessExtension();
    $suffix = $extension ? ".{$extension}" : '';
 
    return $path.$hash.$suffix;
```

2018-02-03 21:41 UTC, taylorotwell commented
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

2018-02-03 21:41 UTC, closed without merging

2018-02-05 18:57 UTC, betterapp commented
I understand but problem is that when uploaded file's extension will be NULL then I get error.
I have reported it. What about this ?
https://github.com/laravel/framework/issues/23008