Handling dot notation in getValue in Validator
laravel/framework pull request #23395
Opened 2018-03-05 17:24 UTC by lk77

Hello,

i propose this change to handle dot notation in validator data.
In parseData function, each '.' is replaced by a '->', and therefore validation does not work with dot notation data.

I understand that dot notation is removed to not interfere with the use of dot notation in the validation,
but i think we should handle it in getValue function, by replacing on the fly  '->'  to '.' in the attribute, to undo change make by parseData.

thanks.

2018-03-05 18:44 UTC, sisve commented
This looks weird and broke tests. Could you submit a code change that works with existing tests, _and_ add more tests for your use-case?

2018-03-05 19:45 UTC, tillkruss commented
Please add tests.

2018-03-05 19:45 UTC, tillkruss requested changes

2018-03-05 19:45 UTC, tillkruss commented on src/Illuminate/Validation/Validator.php
> +
Please add tests

2018-03-05 20:42 UTC, closed without merging

2018-03-06 07:59 UTC, lk77 commented
For me the tests are wrong, this should not work with existing test,
because the tests are expecting that the validation will fail because '.' have been replaced with '->'