Fix dot notation in JSON translations
laravel/framework pull request #23392
Opened 2018-03-05 15:45 UTC by VRuzhentsov

Not sure in destination branch, because it was implemented in 5.4, and still was not fixed, even in 5.5 LTS
(I am using 5.5 for now)

2018-03-05 18:46 UTC, sisve commented
Could you update this PR with some tests? I would like to see that the old format is still supported to make sure this change does not break stuff.

2018-03-05 19:46 UTC, tillkruss requested changes

2018-03-05 19:46 UTC, tillkruss commented on src/Illuminate/Translation/Translator.php
> +        $line = Arr::get($this->loaded['*']['*'][$locale], $key) ?? null;
Please add tests.

2018-03-05 20:42 UTC, closed without merging

2018-03-06 09:08 UTC, VRuzhentsov commented
#23405