[5.7] Add queue payload customization feature
laravel/framework pull request #23606
Opened 2018-03-18 22:21 UTC by AaronJan

## Goal

Allow developer to customize payload of queue job.

## Why

Developer using message queue to decouple logic into different services, some of these services may not be PHP application.

Here is how a Redis queue payload looks like:

```
{\"displayName\":\"App\\\\Jobs\\\\TestQueue\",\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"maxTries\":null,\"timeout\":null,\"timeoutAt\":null,\"data\":{\"commandName\":\"App\\\\Jobs\\\\TestQueue\",\"command\":\"O:18:\\\"App\\\\Jobs\\\\TestQueue\\\":7:{s:6:\\\"\\u0000*\\u0000job\\\";N;s:10:\\\"connection\\\";N;s:5:\\\"queue\\\";N;s:15:\\\"chainConnection\\\";N;s:10:\\\"chainQueue\\\";N;s:5:\\\"delay\\\";N;s:7:\\\"chained\\\";a:0:{}}\"},\"id\":\"SNjXfGlL1QdB3G3CyCnfXI3pHjC2kNK8\",\"attempts\":0}
```

Use NodeJS to generating this? No way.

To achieve communication between different languages, the only way is customizing payload (in an out) to a simpler JSON (or other format) without the overhead, like this:

```json
{
    "productId": 1,
    "cost": "151.15"
}
```

Just let another adapter to translate this back to job handler (using payload, connection name and queue name, it's possible).

And that's what I did [for my project (using RabbitMQ)](https://github.com/AaronJan/Laravel-Rabbit).

## Changes

* I added a `PayloadSerializer` interface to handle serialization that is hard-coded originally.

* Allow developer configure `PayloadSerializer` in `config/queue.php` (Connection => PayloadSerializer).

* Backward compatible.

## Discussion

This is a huge change, but maybe few developers are really need this feature.

What are you think about this? 😃

2018-03-18 22:36 UTC, GrahamCampbell requested changes

2018-03-18 22:36 UTC, GrahamCampbell commented on src/Illuminate/Queue/RedisQueue.php
> +     * @param  string                              $default
Please keep 2 spaces in thr phpdoc for param annotations, like it was before, everywhere.

2018-03-18 22:36 UTC, GrahamCampbell commented on src/Illuminate/Queue/RedisQueue.php
> +        $this->redis      = $redis;
Please don't align these.

2018-03-19 00:40 UTC, taylorotwell commented
Honestly *way* to many changes. Something like this should be able to be accomplished easier.

2018-03-19 00:40 UTC, closed without merging

2018-03-19 01:00 UTC, AaronJan commented
@taylorotwell I knew this would happen, faster than I expect.. 😧 

I accept this, but how to accomplish this exactly?

2018-03-19 01:05 UTC, AaronJan commented
@GrahamCampbell 
Thanks for the reviews, I forgot to change my format setting.

Do you use PhpStorm? How to accomplish this?

> Please keep 2 spaces in thr phpdoc for param annotations, like it was before, everywhere.

2018-03-19 13:25 UTC, francislavoie commented
FWIW I'd really love to see this implemented in some form or another.

https://github.com/laravel/ideas/issues/1007

2018-03-19 14:20 UTC, AaronJan commented
@francislavoie 

Finally I'm not alone. 😄 

`Serializable` only gives some flexibility, by introducing `PayloadSerializer` gives you full control of payload.

You can serialize job to some really simple and readable JSON string (even protobuf), so other program language can process it, or you can unserialize it back, and return the essential attributes like this:

```php
<?php

public function unserialize($raw, $connectionName, $queueName)
{
    $parameters = json_decode($raw);

    if ($connectionName === '' && $queueName === '') {
        $jobClass = 'a';
    } else {
        $jobClass = 'b';
    }

    return [
        'displayName' => 'My RabbitMQ Job',
        'job'         => 'Illuminate\Queue\CallQueuedHandler@call',
        'data'        => [
            'commandName' => $jobClass,
            'command'     => serialize(new $jobClass($parameters['product_id'])),
        ],
    ];
}

```

Last serialize part is a little bit nasty, but I think we can figure it out.

But if Taylor doesn't approve this, This is just a proposal for the future people. 🤔 Fix those tests isn't easy. I spent my whole night for this.. But I'd love to.

2018-03-19 14:54 UTC, AaronJan commented on src/Illuminate/Queue/RedisQueue.php
> +        $this->redis      = $redis;
Code style updated.