[5.6] Adds new comparison validation rules to compare two fields against each other.
laravel/framework pull request #23807
Opened 2018-04-04 18:28 UTC by Alymosul

This PR adds two new validation rules `greater_than` & `less_than`, those two new rules will be used to compare two fields against each other, the two rules are different than `max/min` rules because the two fields under validation must be of the same type also they passed parameter cannot be a hard coded value..

An example:
Supposedly we have a form that takes two input min_salary & max_salary...

```
$rules = [
'min_salary' => 'less_than:max_salary',
'max_salary' => 'greater_than:min_salary'
];
```

The above rules will enforce the min_salary to respect the max_salary value and vice versa.

2018-04-05 00:45 UTC, Alymosul commented
Sure! Just waiting for Taylor’s decision.

2018-04-08 05:38 UTC, carusogabriel requested changes

2018-04-08 05:38 UTC, carusogabriel commented on src/Illuminate/Validation/Concerns/ValidatesAttributes.php
> +    protected function requireSameTypeValues($first, $second)
Missing `@return` and `@throws`

2018-04-10 17:01 UTC, devcircus commented
Compared to all existing validation rules, the naming suggests you could indeed do the following:
```php
$rules = [
'salary' => 'greater_than:36000',
'fees' => 'less_than:3500'
];
```
I understand there's 'min' and 'max', but this will be a major source of confusion in the future. IMO we need to back up and try again. I like the idea, but not the implementation or naming.

Personally, I think a custom rule in your project or a small package with similar functionality would be the best place for this.

2018-04-10 23:37 UTC, devcircus commented
Forgive me. After re-reading, the actual implementation seems fine.

2018-04-17 12:38 UTC, taylorotwell commented
I agree it may be beneficial to allow specifying an integer number the field must be greater than. Also, what about the eventual "can we have greater than or equal to?"

2018-04-17 12:49 UTC, Alymosul commented
I think we can have greater than or equal as a separate validation rule, but i think if we will allow specifying an integer number then it overlaps with the 'max' rule, the core of this rule is the comparison against another field... so what do you think about that?

2018-04-26 13:30 UTC, taylorotwell commented
Feel free to submit when it can take integers and handles "equal to"... personally I would just shorten the rules to something like `gt:field` and `gte:field` etc.

2018-04-26 13:30 UTC, closed without merging