Throw on trying to drop foreign keys in SQLite
laravel/framework pull request #24052
Opened 2018-04-29 16:43 UTC by JanisE

SQLite doesn't support dropping foreign keys (you would need to re-create the table).

See https://github.com/laravel/framework/issues/24041

2018-04-29 16:47 UTC, GrahamCampbell requested changes

2018-04-29 16:47 UTC, GrahamCampbell commented on src/Illuminate/Database/Schema/Blueprint.php
> +            if ($this->commandsNamed(['dropForeign'])->count() > 1) {
Should be `> 0` surely?

2018-04-29 16:50 UTC, JanisE commented
Yes, sorry In my test sample I had several `dropForeign` requests, that's why it worked for me...

2018-04-29 19:13 UTC, merged

2018-09-06 00:06 UTC, okdewit commented
I think this change should be retroactively added to the 5.7 upgrade guide.

A lot of people run their tests using Sqlite, with the main product using MySQL or Postgres, utilizing the same migrations, with full knowledge that the FK commands are no-ops. After this change, all migrations fail.

2019-11-25 21:57 UTC, mchekin commented
@JanisE 
@GrahamCampbell 

Excuse me for my curiosity, but ...

Why not just fix the implementation, instead of throwing the exception?

As mentioned by @staudenmeir 
https://github.com/laravel/framework/issues/24041#issuecomment-385181689

There is a proper way to drop foreign key in SQLite by recreating the table:
https://www.techonthenet.com/sqlite/foreign_keys/drop.php