adding simple @mixin for validations.
laravel/framework pull request #24139
Opened 2018-05-07 18:37 UTC by Artistan

example, \Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables::$app->loadEnvironmentFrom

makes the validations and testing complete in IDEs.

2018-05-07 19:03 UTC, GrahamCampbell requested changes

2018-05-07 19:03 UTC, GrahamCampbell commented on src/Illuminate/Contracts/Foundation/Application.php
> +use Illuminate\Foundation\Application as App;
Imports have a runtime performance cost. Better to just write the FQCN in the phpdoc.

2018-05-07 19:05 UTC, GrahamCampbell commented
Hmm, I don't think this is actually correct. If this contract doesn't have these function in it, then it's correct that the IDE should complain. Adding this mixin is just hiding and error that still exists.

2018-05-07 21:43 UTC, closed without merging

2018-05-08 14:51 UTC, Artistan commented
Good point @GrahamCampbell - thanks.