Added lazy service provider configuration
laravel/framework pull request #24294
Opened 2018-05-23 16:18 UTC by ed-fruty

Now, if even my application don't interacts with `view` (API for example), `view` will still be created by IoS.
This is because `PaginationServiceProvider` uses `loadViewsFrom` method, which call `view` service.

Such behavior already with `translator`. 

And any other service provider can do the same.

The main thing is do not boot services until it needs.

This PR checks, if service was already resolved, then it apply callback right now. 
But if it not loaded yet, subscribes to service resolving and apply callback, when it will be ready.

2018-05-23 16:21 UTC, browner12 commented
is this different than 'deferred' providers?

2018-05-23 16:35 UTC, ed-fruty commented
@browner12 , yes it different. Service provider can be not deferred, but it does not have to initialize other services that may not be needed.

Type `php artisan tinker` and after that `app()->resolved('view')`. It will be `true`, and do you really need it, that `view` is resolved always ? and you can't control that, because any provider can load it using `loadViewsFrom`.

2018-05-23 19:47 UTC, taylorotwell commented
In a standard Laravel application with a single database query how much of a performance impact does this make (before / after)?

2018-05-24 07:26 UTC, ed-fruty commented
The question is not about performance degree.
We can load all defined services (queue, db etc.) force, ant it will add 0,001-0,002 sec, but the question is `why` ? if we can not do this.

let's imagine we have two group of routes in out application: `api` and `web`.
My `web` group render views and uses namespaces, view composers, view creators.
When I want to add new view composer for example, I need to do something like:

```php
class AppServiceProvider
{
   public function boot()
   {
          View::composer('my.view', Composer::class);
   }
}
```

View Composers/ creators/ namespaces can be a lot. And they applies for any of route groups (web/api).
I can't use `afterResolving` method for `view` service, because it was already resolved.

With this PR we can do lazy view configuration, like:

```php
class AppServiceProvider
{
   public function boot()
   {
       $this->app->afterResolving('view', function (Factory $view) { 
             $view->addNamespace('namespace', 'path');
             $view->composer('view', Composer::class);
       });
   }
}
```
And it will setup `view` only when needs to render something. It doesn't apply any side affect for my `api` part of application.

2018-05-24 13:13 UTC, taylorotwell commented
All those tests you added could basically be removed I think. There is too much mocking to be useful at testing anything.

2018-05-25 05:44 UTC, ed-fruty commented
Done.

And maybe it will be useful to update docs and change (Validator extending/View composers/ etc. ) examples from directly calling services to using `afterResolving` ?

2018-05-26 09:50 UTC, GrahamCampbell requested changes

2018-05-26 09:50 UTC, GrahamCampbell commented on src/Illuminate/Support/ServiceProvider.php
> +     */
missing return annotation

2018-05-28 13:13 UTC, taylorotwell commented
I just don't see a big point in changing these things unless we have clear performance before / after comparisons.

2018-05-28 13:13 UTC, closed without merging

2018-06-07 10:43 UTC, ed-fruty commented
@freekmurze , @GrahamCampbell , @sisve 
Guys, what do you think about this?