[5.7] Optimize Collection::mapWithKeys
laravel/framework pull request #24656
Opened 2018-06-21 16:24 UTC by dmitrybubyakin

Benchmark (100,000 iterations):
```
Old method: 4.133s
New method: 3.175s
---
Old method: 3.754s
New method: 2.975s
---
Old method: 3.773s
New method: 3.246s
```

https://gist.github.com/dmitrybubyakin/6bdcc7c0ee7eaffdae699d61017214ee

15-25% faster.

2018-06-21 19:39 UTC, derekmd commented
This would change the behavior from a merge to an append. Right now it's possible for a later `mapWithKeys()` iteration to overwrite the key of a previous iteration. This would make the first keyed value to always be used.

2018-06-21 22:20 UTC, tillkruss requested changes
Please add tests for overwriting keys.

2018-06-22 02:04 UTC, vlakoff commented
Beware of numeric keys, and order of overwriting.

Working solutions might be:
```php
$result = $callback($value, $key) + $result;
$result = array_replace($result, $callback($value, $key));
```

Note `array_replace()` seems to just be the same as `+` with reversed overwriting order, but probably significantly slower (function call overhead).

So, on the principle, why not changing to the `+` operator, if it's properly benchmarked and tested.

2018-06-22 02:08 UTC, vlakoff commented
Refs #16564 and https://github.com/laravel/framework/pull/16552#issuecomment-263155024

2018-06-22 02:17 UTC, vlakoff commented
More importantly: https://github.com/laravel/framework/pull/16552#issuecomment-263143006

> Also take care of preserving the array order (not the same as the numerical indexes). To verify this, a foreach on the result should iterates the items in the same order.

That would be quite a subtle BC break... I haven't checked the proposal here about this. And tests should be added for this, if there are not yet.

2018-06-22 05:35 UTC, vlakoff commented
The added test seems to be worth it, but I guess your new code is slower than current code, isn't it?

2018-06-22 05:38 UTC, dmitrybubyakin commented
@vlakoff @tillkruss Added tests for overwriting keys. 

Benchmark (100,000 iterations):
```
Old method: 3.782s
New method: 2.757s
---
Old method: 4.678s
New method: 3.075s
---
Old method: 4.173s
New method: 3.014s
```

28 - 35% now.

2018-06-22 05:49 UTC, dmitrybubyakin commented
@vlakoff I made some changes, so my new code is faster than the previous code. But there is more memory usage.

2018-06-22 05:57 UTC, vlakoff commented
I see about memory usage. This should be measured as well. With your code here, we get a *huge* `array_replace()` call with many parameters!

Have you tried my simple `$result = $callback($value, $key) + $result;`?

2018-06-22 06:19 UTC, sisve commented
While the current implementation says "The callback should return an associative array with a single key/value pair", it supports a callback returning multiple entries. Is this something that is still supported, or are we dropping that support?

2018-06-22 06:37 UTC, dmitrybubyakin commented
@vlakoff Yes, I have. `$result = $callback($value, $key) + $result;` is much slower than the old code.

@sisve We are nothing dropping.

2018-06-22 07:05 UTC, dmitrybubyakin commented
@vlakoff 

```
10000 iterations over 100 items, strlen 10:
Old method: time 371ms, memory: 2.00Mb
New method: time 307ms, memory: 2.00Mb
----
10000 iterations over 100 items, strlen 100:
Old method: time 382ms, memory: 2.00Mb
New method: time 294ms, memory: 2.00Mb
----
10000 iterations over 100 items, strlen 1000:
Old method: time 376ms, memory: 2.00Mb
New method: time 298ms, memory: 2.00Mb
----

10000 iterations over 1000 items, strlen 100:
Old method: time 3.682s, memory: 2.00Mb
New method: time 2.987s, memory: 4.00Mb
----
100 iterations over 10000 items, strlen 1000:
Old method: time 603ms, memory: 22.00Mb
New method: time 597ms, memory: 26.00Mb
----
10 iterations over 100000 items, strlen 1000:
Old method: time 1.065s, memory: 181.50Mb
New method: time 988ms, memory: 221.51Mb
----
```

2018-06-22 07:23 UTC, vlakoff commented
I tried to reproduce the performance increase, but on my machine your code is actually a bit slower...

```php
$nb = 100;

$data = range(1, 1000);

$callback = function ($value, $key) {
    return [$key => $value];
};


$t1 = microtime(true);
for ($ii = $nb; $ii--; ) {

    $result = [];
    foreach ($data as $key => $value) {
        $assoc = $callback($value, $key);
        foreach ($assoc as $mapKey => $mapValue) {
            $result[$mapKey] = $mapValue;
        }
    }

}
$t2 = microtime(true);
for ($ii = $nb; $ii--; ) {

    $values = array_map($callback, $data, array_keys($data));
    $result = array_replace(...$values);

}
$t3 = microtime(true);

echo $t2 - $t1;
echo "\n";
echo $t3 - $t2;

echo "\n\n";
echo $t2 - $t1 == 0 ? 'N/A' : ($t3 - $t2) * 100 / ($t2 - $t1);
```

Both methods seem to be O(n).

2018-06-22 07:29 UTC, dmitrybubyakin commented
@vlakoff on my machine (php 7.2.6):

```
0.01982307434082
0.012885093688965

65.000481093043%
```

2018-06-22 07:33 UTC, vlakoff commented
Yeah, I had tested on a old PHP 5 box. On PHP 7, both codes are much faster, and yours seems to be faster indeed.

2018-06-22 07:36 UTC, vlakoff commented
Again on my box, above a certain amount of items, your code gets suddenly slower. I guess there is some memory exhaustion, which breaks scalability.

2018-06-22 07:43 UTC, dmitrybubyakin commented
@vlakoff 

https://3v4l.org/YuZn8/perf#perfomance
https://3v4l.org/kone1/perf#perfomance

2018-06-22 07:54 UTC, vlakoff commented
I can confirm on 3v4l.org that on large data (try 10000, 50000...), your code performs slower and uses more memory. There seems to be a threshold at which execution speed seems to fall down, and memory usage difference seems to gradually increase with data size.

For me scalability is the most important by far, even if it means slower (yet acceptable) execution speed of smaller datasets. Memory usage shouldn't be neglected too.

2018-06-22 13:03 UTC, closed without merging

2018-06-22 13:42 UTC, vlakoff commented
Just as a reminder, some possible subtle BC breaks have been highlighted on this thread, and unit tests may be added for these.

2018-06-24 11:49 UTC, vlakoff commented
@dmitrybubyakin I suggest you open a new PR, for just adding this unit test concerning numeric keys overwriting.

The other cases I mentioned (callback returning multiple rows, preservation of array order) are actually already covered by tests.