Give die a status code when the env file is not valid
laravel/framework pull request #24904
Opened 2018-07-19 21:59 UTC by austinkregel

The purpose of this PR is to address the rather rare case when the `.env` file is invalid. This could pop up when one of the lines has a key but no value, and it's followed by a comment. An example line might look like:

```
CUSTOM_VALUE=                # This is a value to be used for tests
```
Having a value like this causes the `die` method to be called and thus kills the app, but since previously there was a string in the place of a status code, it would exit with a `0` status code despite the process actually being killed.

For some CI platforms any application that closes with a `0` status code is considered to be successful. Which means our tests pass even though our tests never actually run.

This PR aims to address this false positive by forcing the `die` method to have a status code that isn't text, thus making the program exit with a non-zero status. 

Personally I feel like there should also be a similar `echo` and `die` in the `InvalidPathException` that is just discarded, but that may not be needed since it was previously ignored.

2018-07-19 22:08 UTC, jpuck commented
Why does Laravel just `die`? Seems like there should be a more elegant solution here.

But I definitely agree it should exit with a non-zero return code. Otherwise build/deploy scripts assume all tests pass.

2018-07-19 22:36 UTC, nathanheffley requested changes
Can you remove the catch for the InvalidPathException since it isn't what is actually causing issues with CI?

2018-07-20 16:58 UTC, taylorotwell commented
I don't think we need to just start dieing on a patch release.

2018-07-20 16:58 UTC, closed without merging

2018-07-20 17:35 UTC, jpuck commented
@taylorotwell I'm not sure if you noticed, but that is the current behavior. For an `InvalidFileException`, it just dies (with a successful return code). However, this fixes the return code, so CI builds don't just pass without running tests.

As for the `InvalidPathException` I agree that's a breaking change and should be removed from this PR. @austinkregel can you please remove that and submit a new PR, or maybe this one can be re-opened?

2018-07-20 17:37 UTC, NathanHeffley commented
@taylorotwell the code already dies if the .env is is invalid, this just changes the status code.

The added part for an invalid exception path should be removed since that branch doesn't die currently.