Add renderers to exceptions
laravel/framework pull request #25072
Opened 2018-08-03 08:49 UTC by omarkdev

In a recent application, I had to handle several exceptions and for this I separated into classes, but at a certain moment of the application the file "Exception/Handler" started to get very large with several "instanceof", so I decided to do it automatically with a "array", worked correctly and I thought it would be an interesting feature for the framework.

In the **Handler** I created an array called **renderers** with expects for an item in which the key is the class to be rendered and the value is the class that will render. When the class is instantiated, the Request and Exception is passed as parameter.

In addition, an interface called **ExceptionRenderer** and an abstract **Renderer** class were also created, in the **Renderer** abstract class in your constructor she receives the Request and Exception and adds them as properties in the class.

2018-08-03 09:00 UTC, GrahamCampbell requested changes

2018-08-03 09:00 UTC, GrahamCampbell commented on src/Illuminate/Foundation/Exceptions/Renderer.php
> +     * @param $request
Invalid syntax, missing type.

2018-08-03 18:52 UTC, taylorotwell commented
You can already define a `render` method on Exceptions in order to avoid instanceof checks in the handler.

2018-08-03 18:52 UTC, closed without merging

2018-08-03 20:17 UTC, omarkdev commented
@taylorotwell But if we need to handle the internal exception? In this case, every time we need to handle, we need to add another "if".

2018-08-03 20:30 UTC, devcircus commented
You can just create an exception class in App\Exceptions and be sure it has a ```render``` method.
[Documentation](https://laravel.com/docs/5.6/errors#renderable-exceptions)

2018-08-04 08:54 UTC, decadence commented
@devcircus 
@omarkdev says about internal PHP exceptions (not user defined custom exceptions).
You can't create `render` method for it.