[5.7] Allow daemon to stop when there is no more jobs in the queue
laravel/framework pull request #25116
Opened 2018-08-06 20:57 UTC by deleugpn

Amazon SQS offers alarms that trigger when a message appears in the Queue. We can use that alarm to run a Task from AWS Elastic Container Service. If the Task has an exit code, Docker will gracefully shutdown the container.

The process I'm seeking is one that I don't need to have a container running 24/7 to work the jobs from the Queue. Instead, the container will start only when there is jobs available in the Queue and it will shutdown when there's nothing more to execute. AWS Fargate makes a pretty decent service to run containers with a limited lifespan.

I felt like the implementation was fairly simple and clean. The test code, however, is not one of my best. I had to figure out a way to avoid the explicit call to `exit` so PHPUnit doesn't end execution.

2018-08-07 08:08 UTC, GrahamCampbell requested changes

2018-08-07 08:08 UTC, GrahamCampbell commented on tests/Queue/QueueWorkerTest.php
> +
Only one newline at end of file please, not two.

2018-08-07 10:06 UTC, lucasmichot commented on src/Illuminate/Queue/Worker.php
> +    protected function stopIfNecessary(WorkerOptions $options, $lastRestart, $job = null)
Missing $job param docblock

2018-08-07 10:06 UTC, lucasmichot commented on src/Illuminate/Queue/WorkerOptions.php
> +    public function __construct($delay = 0, $memory = 128, $timeout = 60, $sleep = 3, $maxTries = 0, $force = false, $stopOnEmptyQueue = false)
same, missing docblock

2018-09-05 13:39 UTC, taylorotwell commented
How is the "stop when empty" option going to be populated. You never populate it from a console command, etc. in your PR.

2018-09-05 13:47 UTC, deleugpn commented
@taylorotwell  I assumed that I could write a new custom command to do that myself, but I can also add that to the existing `queue:work` if you want.

2018-09-05 20:51 UTC, deleugpn commented
Demo: ![Demo](https://puu.sh/BqgKL/1ddff3d556.gif)

2018-09-06 13:48 UTC, merged