[5.8] Upgrade Carbon to version 2 and allow CarbonImmutable
laravel/framework pull request #25310
Opened 2018-08-23 16:21 UTC by kylekatarnls

Hi,

This PR is not ready to be merged yet, this is a proof of concept to be discussed. This is about upgrading to Carbon 2 and as Carbon 2 comes with a factory, it could allow Laravel users to choose `CarbonImmutable` as default class for dates (immutability seems very asked). Or it would allow to change in a easier way the class/engine to use for date with anything (jessengers/date, chronos, or simply a custom user sub-class).

It would be done with:
```php
app(\Carbon\Factory::class)->setClassName(\Carbon\CarbonImmutable::class);
```

After this code, any `now()`, `today()` or inner Carbon creations would create CarbonImmutable instances.

I targeted 5.8, tell me if you think it should be 5.7 or else.

If you think it's the right way to do it. I could go further with tests, doc and maybe a dedicated place in config to set date class and settings.

2018-08-23 16:50 UTC, browner12 commented
I think 5.8 is definitely the right choice. 5.7 is coming out fairly soon, and Carbon v2 is still only in beta.

2018-08-23 17:33 UTC, deleugpn commented
Having Immutable Dates in 5.7 would be the cherry in the pie.

2018-08-23 18:26 UTC, GrahamCampbell requested changes

2018-08-23 18:26 UTC, GrahamCampbell commented on composer.json
> +        "nesbot/carbon": "^2.0.0-beta.5",
Just `^2.0` would be fine.

2018-08-23 18:26 UTC, GrahamCampbell commented on composer.json
> +        "nesbot/carbon": "^2.0.0-beta.5",
Please also update the other composer.json files in this project.

2018-08-23 22:06 UTC, kylekatarnls commented
I thought StyleCI expected alphabetical order for imports as my IDE set them, but seems not. Someone can explain to me the expected order? https://github.styleci.io/analyses/8AEyl9

2018-08-23 22:12 UTC, X-Coder264 commented
Nope, Laravel style is to sort them by length first. And StyleCI clearly depicts that by showing what needs to be placed where.

2018-08-23 22:32 UTC, X-Coder264 commented
You can apply rules for the repo on the StyleCI website if you are the owner of the repo. So there is no need for the styleci.yml to be in the repo.

2018-08-23 22:40 UTC, crynobone commented
Are we going to start using `app()` everywhere in the framework?

2018-08-23 22:42 UTC, X-Coder264 commented
@crynobone Good question. I think we should use `app()` as little as possible or even better avoid it completely.

2018-08-23 22:43 UTC, crynobone commented on src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php
>          $this->getTable()->where('created_at', '<', $expiredAt)->delete();
Auth component doesn't load `app()` which is under `Illuminate\Foundation`, nor does it require `illuminate/container`.

2018-08-23 22:43 UTC, crynobone commented on src/Illuminate/Cache/Repository.php
> +            $duration = $dateFactory->now()->diffInSeconds($dateFactory->createFromTimestamp($duration->getTimestamp()), false) / 60;
Cache component doesn't load `app()` which is under `Illuminate\Foundation`, nor does it require `illuminate/container`.

2018-08-23 22:43 UTC, crynobone commented on src/Illuminate/Console/Scheduling/Event.php
>          )->getNextRunDate($currentTime, $nth, $allowCurrentDate, $this->timezone));
Console component doesn't load `app()` which is under `Illuminate\Foundation`, nor does it require `illuminate/container`.

2018-08-23 22:43 UTC, crynobone commented on src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php
> +        $dateFactory = app(Factory::class);
Database component doesn't load `app()` which is under `Illuminate\Foundation`.

2018-08-23 22:43 UTC, crynobone commented on src/Illuminate/Filesystem/FilesystemAdapter.php
> +            app(Factory::class)->now()->diffInSeconds($expiration),
Filesystem component doesn't load `app()` which is under `Illuminate\Foundation`, nor does it require `illuminate/container`.

2018-08-23 22:44 UTC, crynobone commented
This would fine on the framework level, but once you need to pull in a single component none will work with this changes.

2018-08-23 22:55 UTC, kylekatarnls commented
OK, but what do you propose so? Remember the desired feature: the user should be able to set somewhere the class he want for any date accessible in at application level.

So it may not be needed everywhere. Carbon instances used then destroyed and never returned could still be created the old way. But if the user would have chosen CarbonImmutable as date type, he certainly would expect to get CarbonImmutable for datetime columns in Eloquent models.

2018-08-24 01:02 UTC, crynobone commented
> Remember the desired feature: the user should be able to set somewhere the class he want for any date accessible at application level.

Who desire this feature? What's the advantage of requiring `nesbot/carbon` when Laravel plan to support other date libraries?

I don't see any advantage on resolving factory when a class only generate a carbon instance and use the output. The only component that might heavily take advantage of Immutable is the database component, and maybe for queues scheduling.

2018-08-24 03:08 UTC, crynobone commented on src/Illuminate/Auth/Notifications/VerifyEmail.php
> +            'verification.verify', app(Factory::class)->now()->addMinutes(60), ['id' => $notifiable->getKey()]
This is just going to create a "60 minutes datetime from now", a plain `Carbon::now()->addMinutes(60)` should work fine.

2018-08-24 03:09 UTC, crynobone commented on src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php
> +            'created_at' => app(Factory::class)->now(),
This is just used to store "now" as `created_at` for `reset_passwords`, `Carbon::now()` should be more than enough.

2018-08-24 03:10 UTC, crynobone commented on src/Illuminate/Auth/Passwords/DatabaseTokenRepository.php
> +        return app(Factory::class)->parse($createdAt)->addSeconds($this->expires)->isPast();
This just to check if the token has expired. Why do we need to make it complicated?

2018-08-24 07:08 UTC, kylekatarnls commented
Thanks all for your help. I will have a second iteration on this according to your recommendations:
- target public dates only
- use stuff from illuminate/support, so we get no inner dependencies change

2018-08-24 07:08 UTC, closed without merging

2018-08-24 07:32 UTC, kylekatarnls commented
Yes, it's exactly what I planned and why I close this one. Carbon project will not handle this because we want to abandon the facade pattern (mostly static setters), then each third-party library could get its own factory with its own settings with no impact for the app. So I would create this facade in the Illuminate\Support namespace to carry the factory dedicated to Laravel dates exposed to the user.

2018-08-24 08:45 UTC, crynobone commented
We don't need `immutable` and `mutable` options everywhere in the framework. Most of the usage above were done to utilise `Carbon::setTestNow()` so we can utilise Carbon for testing. Otherwise `time()` or `new DateTime()` would be sufficient.

Yes there is a request or needs for `immutable`, but as I said earlier maybe on the database components specifically.