[5.7] Add aperture collection method
laravel/framework pull request #25403
Opened 2018-09-01 20:33 UTC by manniL

This PR adds a new collection method that transforms an existing collection in sub-collections containing consecutive and linked array with a length of `$length` (default: `2`).

Examples:
`collect([1, 2, 3, 4])->aperture()->toArray(); // [[1, 2], [2, 3], [3, 4]]`
`collect([1, 2, 3, 4])->aperture(1)->toArray(); // [[1], [2], [3], [4]]`
`collect([1, 2, 3, 4])->aperture(0)->toArray(); //  []`
`collect([1, 2, 3, 4])->aperture(-1)->toArray(); //  []`
`collect([1, 2, 3, 4, 5, 6])->aperture(3)->toArray(); // [[1, 2, 3], [3, 4, 5], [4, 5, 6]]`

2018-09-01 21:00 UTC, antonkomarev commented
Isn't it `chunk` method?

2018-09-02 02:33 UTC, manniL commented
@sisve I got the name from [RamdaJS](https://github.com/ramda/ramda/pull/917) (where name finding was also hard :see_no_evil:). I like the metaphor/image of a "moving window", similar to its physical [pendant](https://en.wikipedia.org/wiki/Aperture). However, `consecutive` or `overlapping` would be suitable as function names too but I think it'll be hard to find a name that will exactly describe what the function does.

You are right! haven't thought of `n-grams` by now.

2018-09-02 05:03 UTC, mfn commented
> "moving window"

"sliding window" ? 

However I do like the n-gram analogy: `ngram(int $n)`? 

I think the ngram name might be a good choice because only this will lead to search results remotely related to the functionality. The other names are less idea in that case.

> collect([1, 2, 3, 4])->aperture(-1)->toArray(); // []

Negative value don't make sense? Shouldn't they throw an error?

I think this is one the functions which would benefit from examples right in the phpdoc. No simple amount of textual description will explain what the output will look like IMHO aka "pictures says a 1k words" (I know there are the tests but if you trace code to the method you'll end up there first).

Btw, I would like to know your application of this. Can you give a real-life example where you will use this?

2018-09-02 05:36 UTC, GrahamCampbell requested changes

2018-09-02 05:36 UTC, GrahamCampbell commented on src/Illuminate/Support/Collection.php
> +        $collection = new self;
static?

2018-09-02 08:31 UTC, manniL commented on src/Illuminate/Support/Collection.php
> +        $collection = new self;
Whoops!

2018-09-02 09:26 UTC, manniL commented
@antonkomarev Yeah, sliding window is what I meant :D It was somewhat late :see_no_evil: 
@sisve @antonkomarev  I've altered the function to `ngram($n)`

This function can help greatly when you want to find consecutive pairs/triples/... with f.ex. same properties. Like: Orders that have the same items, actions of the same type, ...

2018-09-02 13:50 UTC, taylorotwell commented
You can macro this into Collection if you need it or release it as a package.

2018-09-02 13:50 UTC, closed without merging