allow to set default time zone for scheduler
laravel/framework pull request #25626
Opened 2018-09-15 06:51 UTC by shrft

this PR is related to this one: https://github.com/laravel/ideas/issues/221

you can set default time zone for scheduler in config/app.php as below.

```
'scheduler_timezone' => 'America/New_York',
```

2018-09-15 11:52 UTC, mfn commented
This would be much appreciated!

Application wise I'm using UTC full throttle (also important for database) but we're not in the UTC+0 timezone.

We've over 20 scheduler jobs but scheduling commands not in your local time is very confusing so we had littered them with our custom timezone to the point we wrote a helper method in `Console\Kernel` to reduce the duplication, etc.

PS: if it gets accepted, don't forget to add it to https://github.com/laravel/laravel too!

2018-09-17 07:37 UTC, shrft commented
@mfn 
thank you for your comment. Yes I will add it to https://github.com/laravel/laravel after this!

2018-09-17 09:30 UTC, lucasmichot commented on src/Illuminate/Console/Scheduling/Event.php
>          return CronExpression::factory($this->expression)->isDue($date->toDateTimeString());
Why not just:
```php
return CronExpression::factory($this->expression)->isDue(
    Carbon::now(),
    $this->timezone ?: config('app.scheduler_timezone', 'UTC')
);
```

2018-09-17 16:32 UTC, laurencei commented
You are not setting `$this->timezone` itself. So functions like `nextRunDate()` will evaluate incorrectly in this current PR.

2018-09-17 16:40 UTC, laurencei commented
p.s. isnt this a massive breaking change?

i.e. If I had my `app.timezone` set to `Australia/Sydney` - then after this PR all my schedules will suddenly switch to `UTC` - because I wont have a default `app.scheduler_timezone` set?

I dont have time to test now - I'll do a test later (unless someone else wants to check in the meantime).

2018-09-17 16:47 UTC, 36864 commented
To avoid breaking changes, the default should be changed to `app.timezone` instead of `UTC`.

2018-09-17 20:44 UTC, taylorotwell commented
While I like the idea behind this feature, we can't use the `config` global foundation helper in the Console component.

2018-09-17 21:02 UTC, lucasmichot commented
@shrft - this should probably target `master`

2018-09-18 12:37 UTC, shrft commented
thank you for the comment. I will fix and push it later.

2018-09-19 19:15 UTC, GrahamCampbell requested changes

2018-09-19 19:15 UTC, GrahamCampbell commented on src/Illuminate/Console/Scheduling/Event.php
> +        $timezone = $this->timezone ?: config('app.scheduler_timezone', 'UTC');
We cannot introduce a cyclic dependency on foundation.

2018-09-20 20:08 UTC, closed without merging