[5.8] Add columns and compact options to route:list command
laravel/framework pull request #25683
Opened 2018-09-18 15:18 UTC by AlexVanderbist

This PR adds some extra options to the route:list command to specify what columns should be included in the output.

### `--columns`

Array input to specify columns to include in the output.

![image](https://user-images.githubusercontent.com/6287961/45696879-cae61480-bb64-11e8-9015-efd608df2a3a.png)

Nice use case: `alias routels='php artisan route:list --columns=method --columns=uri'` for the above output.

### `--compact` or `-c`

Alias for `--columns=method --columns=uri --columns=action`

![image](https://user-images.githubusercontent.com/6287961/45696955-f668ff00-bb64-11e8-89c4-4edc6420558e.png)

Use case: no more truncated lines in terminal :)

### Why is this breaking?

For some reason the domain information for a route was being put in the routes array as `host` (even though the column header is "Domain"). This caused some issues for my PR and also causes `--sort=host` to sort the domain column. 
See line 109 here: https://github.com/laravel/framework/blob/9f313ce9bb5ad49a06ae78d33fbdd1c92a0e21f6/src/Illuminate/Foundation/Console/RouteListCommand.php#L106-L116

As I fix I renamed the array key from `host` to `domain` but this breaks the `--sort=host`.

2018-09-19 19:15 UTC, GrahamCampbell requested changes

2018-09-19 19:15 UTC, GrahamCampbell commented on src/Illuminate/Foundation/Console/RouteListCommand.php
> +            'domain'   => $route->domain(),
Please fix the alignment here. :)

2018-09-20 07:52 UTC, AlexVanderbist commented on src/Illuminate/Foundation/Console/RouteListCommand.php
> +            'domain'   => $route->domain(),
Fixed, can't believe I missed that 😅

2018-09-21 11:46 UTC, mvdnbrk commented
Nice one! 
Maybe it would also be great to have an option to exclude routes from packages? 
Nova, Passport, Debugbar etc. 
Nova alone adds over 50 uri's to the list.

2018-09-23 19:14 UTC, merged