Queued Closures
laravel/framework pull request #25777
Opened 2018-09-25 20:03 UTC by taylorotwell

This reintroduces a feature that was previously present in early versions of Laravel queues. However, there have been improvements to serializable closure libraries in the meantime which allows for better security and better handling of Eloquent models and collections. Namely, signing closures with a hash to prevent modification and arbitrary code execution, as well as transforming and resolving models and collections to ModelIdentifier instances.

2018-09-25 20:08 UTC, m1guelpf commented
@taylorotwell Any chances of serializing closure routes now that you added a library for serializing closures?

2018-09-25 23:19 UTC, GrahamCampbell requested changes

2018-09-25 23:19 UTC, GrahamCampbell commented on composer.json
> +        "opis/closure": "^3.1",
This needs adding to the queue composer.json file too. :)

2018-09-25 23:20 UTC, GrahamCampbell commented
> Namely, signing closures with a hash to prevent modification and arbitrary code execution

I'm pretty sure the previous implementation also supported this? :P

2018-09-25 23:23 UTC, GrahamCampbell requested changes

2018-09-26 11:37 UTC, nunomaduro approved these changes

2018-09-26 13:51 UTC, merged