[5.7] an array of messages for custom validation rules
laravel/framework pull request #26327
Opened 2018-10-31 13:34 UTC by rubenvanassche

At a current project we're working on we have a lot(+200) rules for validating a request. The solution is splitting these rules into separate custom rule classes. Like so

```php
// Before
'units.*.articles.*.date_start' => 'required|date' 
'units.*.articles.*.date_end' => 'required|date' 

// After
'units.*.articles' => new UnitArticlesRule
```

Then in our UnitArticlesRule class we do the following:

```php
class HabitantContractArticlesRule implements Rule
{
    /** @var array */
    protected $messages = [];

    public function passes($attribute, $value)
    {
        foreach ($value as $article){
            $validator = Validator::make($article, $this->rules($article));

            if($validator->fails()){
                $this->messages = array_merge($this->messages, $validator->errors()->all());
            }
        }

        return count($this->messages) === [];
    }

    public function message()
    {
        return $this->messages;
    }

    public function rules(array $article){
        $rules = [
            'date_start' => 'nullable|date',
            'date_end' => 'nullable|date',
        ];

        if($article['date_start'] !== null){
            $rules["date_end"][] = 'after:' . Carbon::make($article['date_start']);
         }

        return $rules;
    }
}

```
As you can see, multiple articles can have validation errors. In the current implementations of custom validation rules we can only return a string. This PR adds the ability to return an array of messages so the example above will work.

The PR won't break any functionality and two tests are added.

2018-10-31 13:42 UTC, driesvints requested changes
Can you fix the StyleCI failures?

2018-10-31 13:49 UTC, rubenvanassche commented
Should be fixed now!

2018-10-31 13:51 UTC, driesvints approved these changes

2018-10-31 14:56 UTC, GrahamCampbell requested changes

2018-10-31 14:56 UTC, GrahamCampbell commented on src/Illuminate/Contracts/Validation/Rule.php
> +     * @return string|array
Could you also update the phpdoc of the implementations?

2018-10-31 15:00 UTC, brendt commented
How about being able to return `\Illuminate\Support\MessageBag` ? If you're using validator in your custom rule, as the example shows, you could just return `$validator->errors()` instead of having to parse it into an array.

2018-10-31 15:03 UTC, brendt commented
Also: I think you should keep in mind that the field where the error is shown. Right now multiple errors are shown on the parent field:

```php
foreach ($messages as $message) {
    $this->messages->add($attribute, $this->makeReplacements(
        $message, $attribute, get_class($rule), []
    ));
}
```

While I expected it to be more like:

```php
foreach ($messages as $childAttribute => $message) {
    $nestedAttribute = "{$attribute}.{$childAttribute}";

    $this->messages->add($nestedAttribute, $this->makeReplacements(
        $message, $nestedAttribute, get_class($rule), []
    ));
}
```

2018-10-31 20:35 UTC, taylorotwell commented
@brendt Interesting. Why would it make assumptions about a child attribute? I'm not sure I would expect that behavior.

2018-11-02 15:41 UTC, merged

2018-11-05 08:08 UTC, brendt commented
@taylorotwell let's assume the following example, it's nothing I'd do IRL, but it illustrates my point.

```php
// The rules in the request class

$rules = [
    'articles' => new ArticleRule(),
];
```

```php
// ArticleRule will validate two properties: type and amount

public function passes($attribute, $value)
{
    if (!in_array($value['type'], ArticleType::toArray())) {
        $this->messages['type'] = 'The article type must be defined in the ArticleType enum.';
    }

    if ($value['amount'] < 0) {
        $this->messages['amount'] = 'You can only specify a positive amount.';
    }

    return empty($this->messages);
}
```

Say both rules fail, we'd get two errors in the final result, mapping to the `type` and `amount` field respectively. I don't think this is the correct behaviour, as they should map to `articles.*.type` and `articles.*.amount`.