[5.8] Remove `fire` method
laravel/framework pull request #26392
Opened 2018-11-05 15:30 UTC by browner12

The `fire()` method is an alias to the `dispatch()` method.  The renaming of this method started way back in the 5.3 to 5.4 upgrade, and is included in the upgrade guide:

https://laravel.com/docs/5.4/upgrade

This follow PR #26379.

Because this is a breaking change, this PR targets the next release.

If accepted I will make a PR to the 5.8 Upgrade Guide.

2018-11-05 15:36 UTC, driesvints requested changes
Can you fix the tests?

2018-11-05 15:37 UTC, browner12 commented
yup, just saw it. brb

2018-11-05 15:53 UTC, driesvints approved these changes

2018-11-05 18:55 UTC, merged

2019-03-21 17:25 UTC, kheengz commented
`fire` was changed to `dispatch`