[5.7] Improve whereInRaw()
laravel/framework pull request #26471
Opened 2018-11-10 17:13 UTC by staudenmeir

The `whereInRaw()` method hasn't been released yet, we can still change it:

- Renames it to `whereInRawInt()` to make its purpose and limitations obvious.
- Removes the `array` type hint to support `Arrayable` values. This is consistent with `whereIn()`.
- Replaces `array_map()` with a `foreach` loop which is considerably faster. Since the whole point of this method is performance improvement, we shouldn't waste time here.

2018-11-10 20:29 UTC, vlakoff commented
Refs #26434 (and #26453).

* Travis CI failures seem to be unrelated.
* I'd rather name it `whereInRawInts`, let's let Taylor settle for this.

2018-11-10 22:44 UTC, GrahamCampbell requested changes

2018-11-10 22:44 UTC, GrahamCampbell commented on src/Illuminate/Database/Query/Builder.php
> +     * @param  mixed  $values
`array|Arrayable`

2018-11-11 14:07 UTC, merged

2018-11-15 04:08 UTC, vlakoff commented
Refs the subsequent a3738cf4e133a4475c56b51f521a12db78e2ecbb