[Query builder] add Builder::insertSub()
laravel/framework pull request #26732
Opened 2018-12-04 06:46 UTC by miklcct

This pull requests add the ability of inserting directly from a sub-query at SQL level, without loading data into memory.

Please refer to #2026 for its use.

2018-12-05 14:08 UTC, taylorotwell commented
Is the syntax the same across all supported database drivers?

2018-12-06 01:14 UTC, miklcct commented
They are the same in MySQL, SQL Server, PostgreSQL and SQLite.

Reference:
MySQL: https://dev.mysql.com/doc/refman/8.0/en/insert-select.html
SQL Server: https://docs.microsoft.com/en-us/sql/t-sql/statements/insert-transact-sql?view=sql-server-2017
PostgreSQL: https://www.postgresql.org/docs/9.1/sql-insert.html
SQLite: https://www.sqlite.org/lang_insert.html

2018-12-06 12:44 UTC, driesvints requested changes

2018-12-06 12:44 UTC, driesvints commented on src/Illuminate/Database/Query/Grammars/Grammar.php
> +     * @param  string   $sql
Use FQN here and proper spacing between parameters names

2018-12-07 14:05 UTC, taylorotwell commented
Renamed to `insertUsing`.

2018-12-07 14:06 UTC, merged

2019-07-14 23:33 UTC, staudenmeir commented on src/Illuminate/Database/Query/Builder.php
> +            $this->cleanBindings($bindings)
Is there a case where we need `cleanBindings()`?