Session store
laravel/framework pull request #26859
Opened 2018-12-15 02:45 UTC by wallaceandrade

There are cases where you need to increase or decrease the size of the session id. Support has been added so this can be customized in config / session.php by setting the id_size key.

2018-12-15 14:36 UTC, taylorotwell commented
Why do you need to change it?

2018-12-15 15:15 UTC, wallaceandrade commented
Estamos migrando um site com cerca de 90 mil usuários. O ID de sessão neste site tem 32 caracteres. Se simplesmente migrarmos sem definirmos o ID de sessão do laravel para 32 caracteres em vez de 40, nenhum id de sessão do site antigo será válido e todos os usuários serão deslogados, o que gerará uma grande demanda. Imagino que esse tamanho do ID possa ser configurado via ENV.

2018-12-15 15:22 UTC, GrahamCampbell requested changes

2018-12-15 17:06 UTC, wallaceandrade commented on src/Illuminate/Session/Store.php
> +        return (isset($_ENV['SESSION_ID_SIZE']) && is_numeric($_ENV['SESSION_ID_SIZE'])) ? $_ENV['SESSION_ID_SIZE'] : 40;
Should I use the env () helper instead? Or the helper config ()? what would be the way?

2018-12-16 03:05 UTC, sisve commented on src/Illuminate/Session/Store.php
> +        return (isset($_ENV['SESSION_ID_SIZE']) && is_numeric($_ENV['SESSION_ID_SIZE'])) ? $_ENV['SESSION_ID_SIZE'] : 40;
Use the config() helper. This is related to cached configuration files and how the use of config:cache will not use the .env file.

2018-12-16 12:04 UTC, X-Coder264 commented on src/Illuminate/Session/Store.php
> +        return (isset($_ENV['SESSION_ID_SIZE']) && is_numeric($_ENV['SESSION_ID_SIZE'])) ? $_ENV['SESSION_ID_SIZE'] : 40;
We can't use the `config` helper here as `illuminate/session` doesn't require the entire framework (e.g. the `Foundation` namespace) to be there in order to work.

What can be done is that the `Store` receives another parameter through its constructor (with the default value of 40) and then in the `SessionManager` where the `Store` is actually constructed the value from the config can be passed `(buildSession` and `buildEncryptedSession` methods).

2018-12-16 15:29 UTC, closed without merging