[5.7] Fix assertSessionDoesntHaveErrors() when there is no errors
laravel/framework pull request #27145
Opened 2019-01-12 07:41 UTC by shadoWalker89

When the response has no errors at all and we do

```php
$response->assertSessionDoesntHaveErrors('can_be_invited_as_reviewer');
```

A php error will occur
`
Error : Call to a member function getBag() on null
 F:\projects\quick-conference\src\quick-conference\vendor\laravel\framework\src\Illuminate\Foundation\Testing\TestResponse.php:904
`

The reason is that the assertion method is not taking into consideration someone checking that a specific error is missing when there is no errors at all.

Having this is a test
```php
$response->assertSessionDoesntHaveErrors('can_be_invited_as_reviewer');
```
intead of this
```php
$response->assertSessionDoesntHaveErrors();
```

makes it clearer that the test is checking that the `can_be_invited_as_reviewer` is missing.

2019-01-12 15:44 UTC, taylorotwell commented
Might be better to actually make an assertion? Even assertTrue(true) just so PHPUnit doesn't confusingly complain about no assertions being made in a test that only calls this method.

2019-01-12 16:56 UTC, shadoWalker89 commented
You are totally right. Change applied.

2019-01-14 12:34 UTC, driesvints requested changes

2019-01-14 12:34 UTC, driesvints commented on src/Illuminate/Foundation/Testing/TestResponse.php
> +            return PHPUnit::assertTrue(true);
`assertTrue` doesn't returns anything. If you want to conform to the signature you'll have to adjust this to

```php
	        if (is_null($this->session()->get('errors'))) {
	            PHPUnit::assertTrue(true);

	            return $this;
            }
```

2019-01-14 13:59 UTC, merged