Fix issue fake dispatcher 3th
laravel/framework pull request #27481
Opened 2019-02-11 00:34 UTC by imanghafoori1

Look at the https://github.com/laravel/framework/pull/27480 for description.

2019-02-11 16:31 UTC, GrahamCampbell requested changes

2019-02-11 16:31 UTC, GrahamCampbell commented on src/Illuminate/Auth/SessionGuard.php
> +    public function setDispatcher(\Closure $events)
Maybe use `callable` here?

2019-02-11 19:37 UTC, imanghafoori1 commented
I think some variable names should also change.
For example the argument for `setDispatcher` has no longer a relevant name.

2019-02-11 19:55 UTC, driesvints commented
Can we please thoroughly consider if this is the right way? These changes seem unwanted to me. You're swapping out a contract with a very loose implementation.

2019-02-11 20:10 UTC, imanghafoori1 commented
@driesvints Of course , I have tried to fix the issue in 3 different ways, the 2 others are closed.
The idea here is to defer resolving of dispatcher to the last moment.

Anyway fill free to close it up if you do not like it.

2019-02-11 23:27 UTC, imanghafoori1 commented
@driesvints How on earth framework users need to call that setDispatcher method. (It's Extremely rare)
It seems to be only called by the internals of the laravel.

2019-02-12 13:43 UTC, taylorotwell commented
See comment on your other PR.

2019-02-12 13:43 UTC, closed without merging

2019-02-13 22:01 UTC, imanghafoori1 commented
@taylorotwell 
- Please reconsider this PR, since we have 3 guards in the core and only the `sessionGuard` dispatches events.
The 2 other guards do not even have a `setDispatcher` method on them.

- This PR covers any guard that can accept a dispatcher through a `setDispatcher` method and is not coupled or know any thing about a specific guard.
The same thing is true for the other PR, https://github.com/laravel/framework/pull/27480