[5.8] Job-based retry delay
laravel/framework pull request #27831
Opened 2019-03-08 14:59 UTC by bahdcoder

#### What does this feature do?
If a `$retriesIn` property is defined on a job, then if that job fails the retry will be delayed for `$retriesIn` amount of time.

#### How will this feature be useful to users?
Let's take an example. An application that  creates `Digital Ocean` droplets using the API. 

The application then tries to `SSH` into the droplet using a job `SshIntoDroplet` once it's active. Even though the droplet is marked as `active` sometimes `SSH` is just not ready, and the job fails. 

With the current functionality, this job is retried immediately. This probably isn't the best way to handle this specific job. 

To fix this, this pull request adds a `$retriesIn` property on a job, and the job is only re-attempted after the defined amount of time.

#### How to use?

Here's an example job that implements this feature:

```php
<?php

namespace App\Jobs;

use App\Droplet;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;

class SshIntoDroplet implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * The droplet to ssh into.
     *
     * @var Droplet
     */
    public $droplet;

    /**
     * The delay before attempting job again
     * 
     * @var integer
     */
    public $retriesIn = 5;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(Droplet $droplet)
    {
        $this->droplet = $droplet;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        // job fails when droplet is active but still booting.
        // If it fails, the Queue worker waits for 5 seconds before retrying.
        $this->droplet->ssh();
    }
}

```

#### Related links
This pull request implements the feature requested  [here](https://github.com/laravel/ideas/issues/537)

2019-03-08 15:25 UTC, driesvints requested changes
Please fix the tests as well.

2019-03-08 15:25 UTC, driesvints commented on src/Illuminate/Queue/Worker.php
> +            );
Please put this on one line.

2019-03-08 15:25 UTC, driesvints commented on src/Illuminate/Queue/Worker.php
> +     * @return  void
```suggestion
     * @return void
```

2019-03-08 17:40 UTC, bahdcoder commented
Hello @driesvints . Could you have a look at the failing tests? They seem to fail on the `5.8` branch even without my implementation.

2019-03-10 05:11 UTC, bahdcoder commented
Hello @GrahamCampbell for some strange reason, running the tests on a freshly new cloned copy of the 5.8 branch locally fails. Same thing I'm experiencing on this branch, and I have no idea why. Could you help out? Thanks.

2019-03-11 09:02 UTC, closed without merging

2019-03-24 18:53 UTC, benignant commented
Quite a few people are interested in this. What happened?

2019-03-26 15:40 UTC, rokde commented
This would be very helpful.

2019-04-18 20:49 UTC, taylorotwell commented
I'm reviving this. Should be done today.

2019-04-19 22:54 UTC, bahdcoder commented
Hey @taylorotwell I initially opened this pull request. Should I reopen? Do you have any improvements you would love me to implement, or are you working on it?

2019-04-20 00:00 UTC, devcircus commented
Another pr has  already been merged.

2019-04-20 00:01 UTC, devcircus commented
#28265