[5.8] Add the ability to register custom DBAL types in the schema builder.
laravel/framework pull request #28214
Opened 2019-04-14 09:02 UTC by JacksonIV

### Overview
This pull request aims to resolve issue #8840. In addition to that, it allows you to easily add custom, platform specific DBAL types to the framework in the future.

### Quick Summary
When changing an existing column to tinyint, it will produce the following error:

> DBALException in DBALException.php line 228:
Unknown column type "tinyinteger" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType()

### Reproduction
In order to reproduce this error, you'll need to run two migrations. One should create a column and the other should should change the column:

```php
// The first migration.
Schema::create('test_migration', function($table) {
    $table->char('test_column');
});
```
```php
// The second migration.
Schema::table('test_migration', function($table) {
    $table->tinyInteger('test_column')->change();
});
```

### Proposed Solution
In order to solve this problem, i created a "registerCustomDBALType" method in the "Builder" class. This way the platform specific builder can call this method to register their own custom type. In addition to that, the user can register their own type in their project by calling the "registerCustomDBALType" on the "Schema" facade.

2019-04-14 16:35 UTC, staudenmeir commented
We should also register the type on other databases, at least on SQL Server (which has a native `tinyint` type). Maybe even on PostgreSQL and SQLite.

Why are you overriding `convertToPHPValue()` and `convertToDatabaseValue()` without changing the implementation?

Please add a test that checks the generated SQL.

2019-04-15 20:38 UTC, JacksonIV commented
@staudenmeir I removed the unnecessary overrides, still working on the rest though.

2019-04-16 12:24 UTC, driesvints requested changes

2019-04-16 12:24 UTC, driesvints commented on src/Illuminate/Database/Schema/Builder.php
> +     * @param  string $type
Add a space here
```suggestion
     * @param  string  $type
```

2019-04-16 12:24 UTC, driesvints commented on src/Illuminate/Database/Schema/MySqlBuilder.php
> +     *
Remove this line
```suggestion
```

2019-04-16 12:24 UTC, driesvints commented on src/Illuminate/Database/Schema/MySqlBuilder.php
> +     * @param  Connection  $connection
Use FQN
```suggestion
     * @param  \Illuminate\Database\Connection  $connection
```

2019-04-16 12:24 UTC, driesvints commented on src/Illuminate/Database/Schema/Types/TinyInteger.php
> +     * @param  AbstractPlatform  $platform
Use FQN
```suggestion
     * @param  \Doctrine\DBAL\Platforms\AbstractPlatform  $platform
```

2019-04-17 11:26 UTC, JacksonIV commented
@driesvints I made the requested changes.

2019-04-17 14:12 UTC, merged

2019-04-25 19:55 UTC, SturmB commented
Hey, is there a chance someone could explain how to use this to get the dreaded "TINYINT" issue to disappear? I'm still learning and don't know how to use `registerCustomDBALType` properly (like where to call it, for example).

2019-04-25 22:01 UTC, driesvints commented
@SturmB this was partially reverted again in https://github.com/laravel/framework/issues/28282 because of the following issue: https://github.com/laravel/framework/issues/28282

2019-04-26 07:01 UTC, JacksonIV commented
@SturmB @driesvints I just want to let you know that i’m still working on a solution to fix the problems with TINYINT, as well as other column types.