Bugfix for self-referencing polymorphic relationships
laravel/framework pull request #28291
Opened 2019-04-22 03:55 UTC by danieleisenhardt

Bug: When a model has a polymorphic relationship with itself the withCount() function always returns 0.

Analysis: The HasOneOrMany::getRelationExistenceQuery() method has separate logic for self referencing relationships, but the MorphOneOrMany::getRelationExistenceQuery() function doesn't. This causes part of the query to point to the Model itself instead of the relation leading to the resulting count being always 0.

Solution: Modified MorphOneOrMany::getRelationExistenceQuery() to accommodate self-referencing relationships.

2019-04-22 11:51 UTC, driesvints requested changes
Please provide a practical use case which details why this is needed and add a test for the fixed behavior.

2019-04-22 12:40 UTC, danieleisenhardt commented
@driesvints I can't find the test for the behavior on the `HasOneOrMany` class, so I don't have anything to base a test off. I'm a bit apprehensive of just writing a test that doesn't match the style of all the other tests. Anyway, here's my practical use case.

Let's say I have a Comment model:
```
<?php

namespace App\Entities;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'body',
    ];

    public function subject()
    {
        return $this->morphTo();
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'subject');
    }
}
```
And there's also comments morphing to posts. Somewhere in the a controller I have the following line:
```
$comments = $post->comments()->withCount('comments')->get();
```
As expected these comments have a `comments_count` property on them. However the value is always 0 because the `morphType` refers to the wrong part of the query.

Please let me know how to write a test for this.

2019-04-22 12:58 UTC, taylorotwell commented
I am closing this pull request because it lacks sufficient explanation, **tests**, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

2019-04-22 12:58 UTC, closed without merging

2019-04-22 13:51 UTC, staudenmeir commented
We can also fix this differently:

```php
public function getRelationExistenceQuery(Builder $query, Builder $parentQuery, $columns = ['*'])
{
    return parent::getRelationExistenceQuery($query, $parentQuery, $columns)->where(
        $query->qualifyColumn($this->getMorphType()), $this->morphClass
    );
}
```

2019-04-22 14:28 UTC, danieleisenhardt commented
That's a cleaner solution, thanks @staudenmeir! I've added it to my fork. 

Unfortunately I don't fully understand how the tests work and there's no test for HasOneOrMany I could use as a template. (Or I can't find it.) I'll add my fork to composer and use it until someone comes along who has a better understanding of the tests.

2019-04-23 01:41 UTC, staudenmeir commented
I'll submit a new PR.