[5.8] fixed required_with with wildcard
laravel/framework pull request #28821
Opened 2019-06-12 16:46 UTC by mxss

reopened: #28813
issue: #26957

required_with didn't work with wildcard, see source issue for more details

2019-06-12 17:59 UTC, devcircus commented
Just a suggestion, but it helps the maintainers if you you include a full description of the PR instead of just linking issues. Show the problem, what happens currently, what will happen if the pr is accepted, what you changed to make the new behavior possible, and why the new way is better.

2019-06-12 20:03 UTC, bonzai commented on src/Illuminate/Validation/Concerns/ValidatesAttributes.php
> +        if (strpos($parameters[0], '*') || ! $this->allFailingRequired($parameters)) {
```suggestion
        if (strpos($parameters[0], '*') !== false || ! $this->allFailingRequired($parameters)) {
```

2019-06-18 05:25 UTC, themsaid requested changes
This test will not pass with your changes:

```
$v = new Validator(
    $trans,
    [
        'names' => [['second' => 'Otwell']],
        'foo' => '',
    ],
    ['foo' => 'required_with:names.*.first']
);
$this->assertTrue($v->passes());
```

2019-06-18 08:13 UTC, mxss commented
@themsaid I've updated PR (added your test + addional check), please review

2019-06-18 13:59 UTC, themsaid commented
Still won't work if value is `null` or the key is not even provided.

I don't really think this can be fixed with a simple solution, `getValue()` won't accept a wildcard attribute name so it'll always return `null` causing whatever you provide in `required_with` rule to pass without validation.

I'm closing this PR since it's not right and breaking other validation cases. Please feel free to open a new one if you managed to get `getValue` to work with wildcard attributes.

2019-06-18 13:59 UTC, closed without merging