Create migrations directory if doesn't exist when making migration
laravel/framework pull request #28902
Opened 2019-06-20 14:24 UTC by aso824

Currently, when default directory `database/migrations` does not exist and command `php artisan make:migration ...` is executed, a long and not-so-obvious error is displayed (_No such file or directory_ with full content of new migration file).

This fix will try to create destination directory and will throw an exception if `mkdir` failed.

2019-06-20 14:43 UTC, awais-vteams commented
When we create a new Laravel app from composer https://laravel.com/docs/5.8#installation we already have migrations folder with 2 migrations.

https://github.com/laravel/laravel/tree/master/database/migrations

2019-06-20 14:56 UTC, aso824 commented
> When we create a new Laravel app from composer https://laravel.com/docs/5.8#installation we already have migrations folder with 2 migrations.
> 
> https://github.com/laravel/laravel/tree/master/database/migrations

But if you pass `--path` parameter to non-existing directory, same error will occur.

2019-06-21 08:01 UTC, narwy commented
Just looking at your code, the order is checking to see if the migration exists first then the folder. Wouldn't you want to check if the folder exists then check if the migration exists in that folder?

I do feel this is benefit for those who have deleted folders etc it will auto create them without errors.

2019-06-21 09:11 UTC, d3jn requested changes

2019-06-21 09:11 UTC, d3jn commented on src/Illuminate/Database/Migrations/MigrationCreator.php
> +    protected function ensureMigrationPathExist(string $path): void
A small nudge, but it should be `ensureMigrationPathExists`

2019-06-21 13:27 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2019-06-21 13:27 UTC, closed without merging