Validate the characters passed to $name on MigrationMakeCommand
laravel/framework pull request #28942
Opened 2019-06-24 19:46 UTC by liam-wiltshire

Reference: #28938 

The name passed to the `make:migration` command forms the base of the classname of the generated migration file. Currently this `name` param isn't validated, meaning classes can be created with invalid class names.

This PR adds a simple check to confirm there are no unsupported characters (using the RegEx defined in the PHP docs at https://www.php.net/manual/en/language.oop5.basic.php), and throws an InvalidArgumentException should such characters be found.

2019-06-24 20:25 UTC, GrahamCampbell requested changes

2019-06-24 20:25 UTC, GrahamCampbell commented on src/Illuminate/Database/Console/Migrations/MigrateMakeCommand.php
> +        // migration.  As such, we need to confirm that there are no characters
Please don't double space after a period.

2019-06-24 20:25 UTC, GrahamCampbell commented on src/Illuminate/Database/Console/Migrations/MigrateMakeCommand.php
> +        // migration.  As such, we need to confirm that there are no characters
Please don't double space after a period.

2019-06-24 20:25 UTC, GrahamCampbell commented on src/Illuminate/Database/Console/Migrations/MigrateMakeCommand.php
> +            throw new \InvalidArgumentException("Invalid characters present in proposed classname {$name}");
Please import the exception class rather than prefixing it with a slash.

2019-06-24 20:25 UTC, GrahamCampbell commented on tests/Database/DatabaseMigrationMakeCommandTest.php
> +        $this->expectException(\InvalidArgumentException::class);
Same as above.

2019-06-24 20:29 UTC, mfn commented
Similar PRs have been rejected in the past: https://github.com/laravel/framework/pull/26892
> Rather than maintain a regular expression I rather just let people input valid names.

2019-06-24 20:48 UTC, liam-wiltshire commented
@GrahamCampbell I've tweaked those bits for you

@mfn If it gets closed then so be it, however I'd argue that in the interest of a good developer experience, maintenance of a RegEx that PHP provides and is unlikely to change often is a small price to pay. I came across this when I 'fat fingered' the comma key writing a migration name, and didn't notice until I actually went to run the migration. A small annoyance, yes sure, but an annoyance all the same. Ultimately if it get's closed then I won't lose sleep over it, I've followed the mantra of "don't moan about it, submit a PR", so I'm happy either way :-)

2019-06-24 20:51 UTC, taylorotwell commented
If we go down this road, why just migrations? Why not validate every single class based command generator?

2019-06-24 20:56 UTC, liam-wiltshire commented
> If we go down this road, why just migrations? Why not validate every single class based command generator?

Fair point - I'd thought about it in the context of migrations because that's where it annoyed me today, however I'd argue it's perhaps even more useful in other places - in most situations, you create a migration then run it straight away - if it's something like a Mailable or whatever you'll want to call it in another class (when your IDE I guess will just not even offer it as an option), and you could potentially be a few steps down the line before you realise the mistake.

I _think_ you were actually making the opposite point, that adding it everywhere is alot of changes, but I can't imagine I'm the first developer who's done this, and I doubt I'll be the last, so I'd see it as a benefit!

2019-06-25 13:40 UTC, taylorotwell commented
If this were going to be done, I would personally just do it on all generated class and create a Str::validClassName method to check if a given string is valid.

2019-06-25 13:40 UTC, closed without merging