[6.0] Adding relational support to Eloquent Factory
laravel/framework pull request #29592
Opened 2019-08-15 19:44 UTC by rasmuscnielsen

This PR introduces a Eloquent-like relational support to the Factory:

```php
$team = factory(Team::class)->with(1, 'users')->create();
```

While similar features has been discussed in a previous PR (https://github.com/laravel/framework/pull/26811), this proposed implementation offers much more advanced features; most notably nested relations. 
It may also be considered an attempt of a general overhaul of the existing factory.

The source code for this PR has been developed, used and improved in this package for around half a year: [makeabledk/laravel-factory-enhanced](https://github.com/makeabledk/laravel-factory-enhanced).

## Motivation
A major part of testing is ‘setting up your world’, which often times includes creating multiple related models.

For instance, writing the equivalent of above example in today’s factory, would look something like the following:

```php
$team = factory(Team::class)->create();
$user = factory(User::class)->create();
$member = factory(TeamMember::class)->create([
    'team_id' => $team,
    'user_id' => $user,
]);
``` 

All of this may of course be tugged away in a pre-defined definition state - but for some cases each test is just too individual.
Being able to utilize existing relations on your models makes it a breeze to prepare tests with very few lines of code.

## New functionality introduced

### Relational support 
Example: Creating nested models with states

```php
factory(Team::class)    
    ->with(2, 'online', ‘servers')
    ->with(1, 'migrated', 'mysql', ‘servers.databases', ['name' => 'forge'])
    ->create();
```

Example: Creating customized relations with a closure. 

```php
factory(Team::class)    
    ->with(2, 'online', servers', function (FactoryBuilder $builder) {
        $builder
	    ->fill(function ($faker) {
	    	'name' => $faker->name
	    })
	    ->with(1, 'mysql', 'databases')
	    ->andWith(1, 'postgres', 'databases');
    })
    ->create();
```

In the above closure we may do anything we can normally do on the `FactoryBuilder` instance - even load on more nested relations. 
Also note that there is no particular order to the attributes given to the `with()` method. Feel free to do whichever reads better 👍

More examples can be found in the package readme: [makeabledk/laravel-factory-enhanced](https://github.com/makeabledk/laravel-factory-enhanced)

### Introducing presets
While we currently have definitions and states, none of these allow us to reuse more higher level configurations such as “a user with 1 small team that has 2 employees”.

For this purpose a new preset definition is introduced, and works like this:

```php
factory()->preset(User::class, 'businessOwner', function (FactoryBuilder $user, Generator $faker) {
    $user
        ->with(1, 'teams')
        ->with(2, 'teams.employees');
});
```

Now we may use the factory to create a `User` using that preset:

```php
factory(User::class)->preset(‘businessOwner’)->create();
```

Or on the fly in a relation:

```php
factory(Invoice::class)->with(‘businessOwner’, ‘user’)->create();
```

This is super powerful, as it allows the developer to make use of the full FactoryBuilder, instead of relying on it to only return attributes.

The main downside is that it introduces yet another type of ‘definition’ to the factory, making it a full 3 (define, state, preset).
I will be discussing this issue further in a later section ‘Future prospects’. 

### New methods on FactoryBuilder
Finally a handful of new helpers has been introduced:

- definition
- fill - fill attributes
- fillPivot - only applicable when loading a BelongsToMany relation.
- odds - add some randomness to the factory. Useful when seeding.
- preset
- presets
- tap
- when
- with
- andWith - allows for loading same the HasMany relation multiple times with different configuration.

## Compatibility 
The implementation for creating relations works for all relation types except

- HasManyThrough 
- MorphedByMany

While the implementation includes some heavy refactoring of the existing codebase, all public instance methods remains the same.
The refactoring seemed due and necessary to implement the new features in a sustainable manner.

The breaking changes are limited to

- `Factory::__construct` 
- `FactoryBuilder::__construct` 
- Protected methods

## Future prospects
Alternate heading: My personal wishlist.

Given how much has happened since Eloquent Factory was first introduced in v5.1, it is no wonder that certain parts of the codebase is starting feel a bit outdated at this point.

Here are a couple of my observations, after having familiarized myself quite thoroughly with the codebase through the better part of the past year.

### Cleaning out legacy helpers

The majority of the legacy seems to be in the ´Factory` class:

- ArrayAccess. It only works for definitions, and takes up 45 lines of code.
- All methods containing the words `create`, `make`, and `raw` are redundant. Simply `factory(User::class)->create()` instead. Also they exist twice as `createOf`.

At this point we would have removed 10 methods, and reduced from 321 to 198 lines of code in `Factory`.

The only responsibilities left of the `Factory` class is now: 

- Load definitions
- Instantiate new `FactoryBuilder`’s 

With this reduction of responsibility, it'd be up for discussion if the `StateManager` in this PR should just be re-implemented back into the factory.

If this is something the community would be supportive of, we could start by deprecating helpers in `v6.0`, and remove them in `v7.0`. 

### Streamlining definition types
At this point we have 3 different types of definitions  (included 1 introduced in this PR): 

- Definitions
- States
- Presets

States and definitions are basically completely interchangeable except, on the contrary to definitions, multiple states can be applied when factoring a model.

Internally both states and definitions could be implemented as presets, as they would simply need to be wrapped with a closure that fills the attributes on the `FactoryBuilder`.
The main problem with this is that they would share the same namespace, so a ‘default’ state would overwrite the ‘default’ definition.
The ‘afterCallbacks’ implementation already uses the same concept, so the main thing is that it may break some people’s codebases if they rely on this as a feature.
 
The above refactoring would still expose the same public API to keep breaking changes at the bare minimum.

Further down the line we could completely outphase the concept of ‘definition’, and simply have a ‘default’ state.

## TODO

Move and re-implement tests from https://github.com/makeabledk/laravel-factory-enhanced/tree/master/tests/Feature to this PR.

I will do this ASAP once I know that there is general support to bring this into the Laravel Core, as I've already spent too much time on getting this PR ready 😅 

There is 35 tests and 75 assertions for the source code, so everything is pretty well tested (in comparison to the existing 12 tests and 24 assertions). 

Hope you all like it - appreciate any feedback!

2019-08-16 12:16 UTC, driesvints requested changes
Took a real quick look. Mostly styling remarks. Make sure you always use FQN in DocBlocks and always annotate types.

2019-08-16 12:16 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Factory.php
> +     * @var StateManager
Use FQN in DocBlocks.

2019-08-16 12:16 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Factory.php
> +     * @param StateManager $stateManager
Use FQN in DocBlocks and two spaces before and after types in `@param` annotations.

Ps.: I'm gonna skip all the other places in this PR where this is the case so it's best that you go through it yourself.

2019-08-16 12:16 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Factory/RelationRequest.php
> +     * @param StateManager $stateManager
Add types to these `@param` annotations.

2019-08-16 12:16 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Factory/RelationRequest.php
> +     * @var callable | null
Don't use spaces after or before the `|` character for types.

2019-08-16 12:16 UTC, driesvints commented on src/Illuminate/Database/Eloquent/FactoryBuilder.php
> +     * @throws \InvalidArgumentException
This method doesn't throws this exception. We don't document cascading throws.

2019-08-16 12:16 UTC, driesvints commented on tests/Integration/Database/EloquentFactoryBuilderTest.php
> +use Illuminate\Database\Eloquent\Factory\StateManager;
Arrange imports by length.

2019-08-16 14:24 UTC, rasmuscnielsen commented
Thanks @driesvints - fixed 

Think I've got all of them. Let me know if I missed some!

2019-08-16 14:30 UTC, driesvints requested changes
Some small details. Think that's it.

2019-08-16 14:30 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Factory.php
> +     * @param  \Illuminate\Database\Eloquent\Factory\StateManager  $stateManager
Re-add void to every constructor.

2019-08-16 14:30 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Factory.php
> +     * @var \Illuminate\Database\Eloquent\Factory\StateManager
Add a small one line explanation of this property like on other properties/classes.

2019-08-16 14:30 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Factory/BuildsRelationships.php
> +     * @param  string  $relationName
Add a small one-line explanation of this method.

2019-08-16 14:30 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Factory/RelationRequest.php
> +     * @return int
Add a small one-line explanation of this method.

2019-08-16 14:30 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Factory/RelationRequest.php
> +     * @return \Illuminate\Database\Eloquent\Model
Add a small one-line explanation of this method.

2019-08-16 15:36 UTC, rasmuscnielsen commented
@driesvints Done 👍

2019-08-20 10:20 UTC, rasmuscnielsen commented
Any thoughts / feedback on this PR and prospects of shipping with v6? 

@driesvints

2019-08-20 12:19 UTC, driesvints commented
@rasmuscnielsen needs a review from Taylor now.

2019-08-27 05:56 UTC, rasmuscnielsen commented
@driesvints @taylorotwell Given that 6.0 will be presented at Laracon EU in a few days and is set to be released next week, does that officially mean this PR won't make it to this release? 

What are the next steps in that case? Kinda hoping it won't just be closed with a ‘try again next year’ 🙁
Also considering there seems to be good support for this in the community too.

2019-09-02 09:21 UTC, driesvints commented
I don't think Taylor will have time to review this before the 6.0, sorry.

2019-09-04 16:26 UTC, gofish543 commented
Can we merge this please? This was the main feature I was really hoping to use with the Laravel 6.0.

TBH, I'm a few days away from downgrading from 6.0 and using @rasmuscnielsen 's branch specifically for this feature.

2019-09-04 16:28 UTC, gofish543 commented
Can we merge this... :(

2019-09-04 16:29 UTC, gofish543 commented
What's the status of this PR? I've been following it because it contains features that I will use daily on every one of my Laravel applications

2019-09-05 03:04 UTC, ManojKiranA commented
> I've been following it because it contains features that I will use daily on every one of my Laravel applications

try this

https://github.com/makeabledk/laravel-factory-enhanced

2019-09-05 07:37 UTC, rasmuscnielsen commented
@gofish543 Currently there is not support for attaching existing models although this was actually supported in a early version. I decided to drop it though because it introduced extra complexity and unexpected behavior when combined with nested relations. The few times I've needed it since myself, I've just attached it manually after the fact. 
I'm not inherently against re-introducing it if a cleaner and more simple solution could be found.  Here is the stale branch: https://github.com/makeabledk/laravel-factory-enhanced/tree/feat/relatable-instances
Feel free to open up a issue if you'd like to discuss further. 👍

@ManojKiranA Thanks for posting the link👍 

For the people wishing to use the package, I've not yet tagged the features added while working on this PR (primarily presets).
I still have some ideas that may introduce breaking changes, and I wanted to wait and see what the outcome of this PR will be. I recommend using the latest tagged version, but if you want the latest features, you could pull in `dev-master` which is stable as well. I do not anticipate any breaking changes to the public API, but of course, use it at your own risk 😊

_____

As for the future plans of this PR I'm still very much hoping that Taylor will eventually get around to give his thoughts and feedback. If he's generally positive around the ideas and implementation discussed here we could continue on and talk about prospects for how it might be introduced in a minor version. 
One way that jumps to mind would be by the user opting in for the new version in ie 
`AppServiceProvider@boot` method.

`Factory:v2()` - or `app()->bind('factory', \Illuminate\Path\To\New\Factory::class)`

2019-09-18 15:35 UTC, rasmuscnielsen commented
@driesvints 

Still no word from @taylorotwell on this? 😟

2019-10-15 18:38 UTC, darielopper requested changes

2019-10-15 18:38 UTC, dramosv90 commented on src/Illuminate/Database/Eloquent/Factory/RelationRequest.php
> +        [$this->class, $this->batch, $this->stateManager] = [$class, $batch, $stateManager];
😉

2019-10-15 18:38 UTC, dramosv90 commented on src/Illuminate/Database/Eloquent/Factory/RelationRequest.php
> +        return implode('.', $nested);
You can omit the two first line and accept this one (In `getRelationName` function you use the same logic)

```suggestion
        return implode('.', $this->getRelationName($path));
```

2020-01-02 20:13 UTC, rasmuscnielsen commented
Hey @driesvints @taylorotwell 

Just thought to check in if there are any plans for this to make it for the upcoming Laravel 7? Or just any feedback beyond code-style? 

It's been a bit discouraging having put ~100h work into the code and thoughts behind this PR, yet after 5 months it's still awaiting any official feedback. 
I understand if it's not inline with the future visions of the framework - after all that's why it was made into a package in the first place - but honestly just some feedback and clarity would be greatly appreciated at this point. 

Hope to hear from you guys

2020-01-02 21:04 UTC, driesvints commented
@rasmuscnielsen Hey, I took a quick look at the initial comment. I have to say that this PR is quite large which makes reviewing difficult. Doing separate prs for the things proposed in this PR could help digest it a little bit.

I like the relational support. I often find myself doing this so nice api for this could be cool. If we're going to do this I'd definitely want to reference model classes and not any strings. So `->with(User::class)` if that was possible. I'd also make the relation class the first argument so you can easily create one instance of a relation fast. Then make the rest of the arguments "smart" like the factory helper so you could either add a closure/array for fields or an integer/string for amount/state.

I don't think presets serve any value since we already have seeds which serve the same purpose. You can just create a specific seed class which will seed the scenario you needed. We'd only be adding the same functionality twice imo.

Thanks for all the work so far 👍 Ultimately it's up to Taylor to decide upon this.

2020-02-03 18:40 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2020-02-03 18:40 UTC, closed without merging