Implement Aws temporary url via CloudFront
laravel/framework pull request #29697
Opened 2019-08-23 09:48 UTC by plumpboy

this pull request will solve the issue 
https://github.com/laravel/framework/issues/26797
It help someone who use CloudFront to serve S3 files and want to get CloudFront Signed Url.
**Add CloudFront configuration to env file**
```
AWS_CLOUDFRONT_PROTOCOL=https
AWS_CLOUDFRONT_DOMAIN=your_cloudfont_domain_name
AWS_CLOUDFRONT_KEY_PAIR_ID=your_key_pair_id
AWS_CLOUDFRONT_PRIVATE_KEY_PATH=path_to_private_key_file
AWS_S3_VIA_CLOUDFRONT=false
```
set "AWS_S3_VIA_CLOUDFRONT" into "true" to get CloudFront Signed Url instead of S3 Pre-Signed Url

2019-08-23 10:50 UTC, deleugpn commented on src/Illuminate/Filesystem/FilesystemAdapter.php
> +        $resourceUrl = env('AWS_CLOUDFRONT_PROTOCOL').'://'.env('AWS_CLOUDFRONT_DOMAIN').$path;
You can't use `env` outside of config files as it will return null for cached configuration.

2019-08-23 10:52 UTC, GrahamCampbell requested changes

2019-08-23 10:52 UTC, GrahamCampbell commented on src/Illuminate/Filesystem/FilesystemAdapter.php
> +        if (env('AWS_S3_VIA_CLOUDFRONT')) {
We can't call the env function here.

2019-08-23 10:53 UTC, closed without merging

2019-08-23 10:53 UTC, driesvints commented
Heya as @deleugpn said, please use the config repository to retrieve options. Feel free to resubmit with those changes.

2019-08-23 10:53 UTC, GrahamCampbell commented
Please retarget this at the 6.0 branch, rather than master.

2019-08-23 10:53 UTC, driesvints commented
@GrahamCampbell you were too fast heh

2019-08-23 11:05 UTC, plumpboy commented
@GrahamCampbell @driesvints ok guys i will fix and resubmit.
i am thinking about custom the league filesystem to make getTemporaryUrl as a method in adapter.
Is it alright ?

2023-10-19 22:42 UTC, meyer59 commented
Hey, @plumpboy,
I have the exact same issue, how do you endup managing cloudfront url in laravel at the end? I see that none of your PR has been merged, is there anything for cloudfront in the framework? 
Thanks