[FIX] Override (static) password key name
laravel/framework pull request #30150
Opened 2019-10-01 13:00 UTC by ahmedsayedabdelsalam

There was a case when I needed to make the User model store the password in a different column rather than "password", unfortunately, this column can't be changed, so to make it more dynamic, I've added a method that can be overridden, where we can specify the name of the column that stores the password, and an attribute in the User model that has a default value for that column with a value = "password"

old: `if (Str::contains($key, 'password'))`

new: `if (Str::contains($key, $query->getModel()->getPasswordKeyName()))`

the new attribute: `protected $passwordKey = 'password';`

2019-10-01 14:44 UTC, jmarcher requested changes
Also add some tests for the new code.

Edit: Fix the tests as well

2019-10-01 14:44 UTC, jmarcher commented on src/Illuminate/Database/Eloquent/Model.php
> +    public function setPasswordKeyName($key)
Do we really need this method? The table name will not change on runtime

2019-10-01 20:49 UTC, X-Coder264 commented
I don't see why we should add all these methods to the base Eloquent model class (which all Eloquent models extend) when this is very specific user model stuff? The `password` column is hardcoded and it would be nice to be more flexible about it, but this implementation is not the way to go IMO.

2019-10-02 07:09 UTC, svenluijten commented
I agree with @X-Coder264, I think this code would fit better in [`Illuminate\Auth\Authenticatable`](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Auth/Authenticatable.php).

2019-10-02 07:35 UTC, ahmedsayedabdelsalam commented
> I don't see why we should add all these methods to the base Eloquent model class (which all Eloquent models extend) when this is very specific user model stuff? The `password` column is hardcoded and it would be nice to be more flexible about it, but this implementation is not the way to go IMO.

@X-Coder264 , @svenluijten 

You're Right, thank you.
Which way Would be better : 
1- fix it in another commit 
2- undo these commits and add new one
3- close the PR and open a new one

2019-10-02 09:29 UTC, svenluijten commented
You can add a commit to this PR @ahmedsayedabdelsalam.

2019-10-02 09:47 UTC, jmarcher commented on src/Illuminate/Database/Eloquent/Model.php
> +    public function setPasswordKeyName($key)
@ahmedsayedabdelsalam have any use cases for this?

2019-10-02 13:03 UTC, taylorotwell commented
We wouldn't add anything about passwords to the base Eloquent model. What if my model is a street address?

2019-10-02 13:03 UTC, closed without merging

2019-10-02 13:46 UTC, Abdalmoniem8 commented
.

2019-10-02 13:52 UTC, ahmedsayedabdelsalam commented
I wrote a comment that I will fix the implementation as @X-Coder264 request
I didn't get why you closed the PR, Is using (password) statically in code more appropriate ?!

2019-10-02 13:53 UTC, Abdalmoniem8 commented
اضرب يا استاذ احمد

2019-10-02 14:26 UTC, svenluijten commented
@ahmedsayedabdelsalam no worries, you can submit another PR with this same functionality except (as discussed) put in the `Authenticatable` class. I'm sure that'll be accepted no problem.

2019-10-03 07:25 UTC, ahmedsayedabdelsalam commented
new PR [30161](https://github.com/laravel/framework/pull/30161)