[7.x] accept field for Route binding
laravel/framework pull request #30471
Opened 2019-10-30 23:56 UTC by browner12

### Scenario

Assume we have a Model called `App\Page` with the following table structure.

- id
- title
- slug

When accessing it in a user facing Route via implicit binding (`example.com/my-page-slug`) we want to query the Model via the `slug` property, but when accessing it from an administration facing Route via implicit binding (`example.com/admin/pages/1/edit`) we want to query off the default `id` property.

We currently have the ability to change which field the Model uses to query off of by overriding the `getRouteKeyName()` method. Unfortunately, this is global and does not allow us to do it selectively.

What I would propose is we can override the query field via the Route definition for Route localized needs.

```php
Route::resource('admin.pages, 'AdminPageController');

Route::get('{page}', 'PageController@show')->by(['page' => 'slug']);
```

### Proposed Solution

This is part 1 of a 2 part solution. This PR allows us pass an override `$field` to the `resolveRouteBinding()` method.  The default will be `null` so existing calls will not be affected, and the fallback for the parameter will be the default `getRouteKeyName()`.

Part 2 will require passing the override values in from the Route definition. My first thought would be to add these as more "actions", but I'd be open to other suggestions. Also open to naming, since  I don't have any good ones yet.

### Master

PRing to master since there are Contract changes.

2019-10-31 00:11 UTC, devcircus commented
Not necessarily against the changes but it seems like this goes against the nature of "implicit" binding, however, laravel already allows you to explicitly define route model binding via a service provider, which would probably work well in this situation.

2019-10-31 00:20 UTC, browner12 commented
I guess there's different levels of implicit. This lies somewhere in-between.

correct, that it the solution I currently use where I designate a custom route slug that has its own logic in the `RouteServiceProvider`.

```php
Route::get('{slug}', 'PageController@show');
```

```php
public function boot()
{
    parent::boot();

    Route::bind('slug', function ($value) {
        return \App\Page::where('slug', $value)->first() ?? null;
    });
}
```

It's just a little more verbose of a solution, so was hoping we could build something a little more terse.

2019-10-31 12:48 UTC, BrandonSurowiec commented
There was a previous proposal for syntax like:

```
Route::get('{page:slug}', 'PageController@show');
```

But I like your solution just as much.

(https://github.com/laravel/framework/pull/18197)

2019-10-31 13:04 UTC, taylorotwell commented
I wouldn't mind revisiting that syntax @BrandonSurowiec. I think it is pretty clean.

2019-10-31 16:25 UTC, browner12 commented
yah, that's not bad. I'm open to other syntaxes if we can get this to work.

2019-11-05 14:12 UTC, taylorotwell commented
I like the syntax in #18197 best, I think at the time I just thought that PR seemed to touch quite a few files to make it work.

2019-11-11 13:57 UTC, taylorotwell commented
@browner12 do you want to try that other syntax in the PR I linked or do you want to move on from this PR?

2019-11-12 01:09 UTC, browner12 commented
sure, let me give it a shot this week.

2019-11-17 08:04 UTC, tisuchi approved these changes

2019-11-17 11:23 UTC, GrahamCampbell requested changes

2019-11-17 11:23 UTC, GrahamCampbell commented on src/Illuminate/Contracts/Routing/UrlRoutable.php
> +     * @param  string  $field
string|null

2019-11-18 12:29 UTC, Arkanius commented on src/Illuminate/Database/Eloquent/Model.php
> +     * @param  string  $field
string|null

2019-11-18 12:30 UTC, Arkanius commented on src/Illuminate/Http/Resources/DelegatesToResource.php
> +     * @param  string  $field
string|null

2019-11-22 17:45 UTC, merged

2019-11-22 17:45 UTC, taylorotwell commented
I've written the other half of this. Will link them together now.

2019-11-22 18:39 UTC, browner12 commented
sorry for the delay, things got busy at work. thanks for taking charge on the other part of this.

2020-02-08 22:52 UTC, Daniel-Mendes commented
And if I want to use an Accessor like getDateAttribute, that isn't  a column of my database, will it work ?

2020-07-22 11:19 UTC, deleugpn commented
I knew I wasn't crazy and I had seen this PR in the past, but it was hard to find it, so I'm just adding a few keywords here to try and make it easier to search GitHub

**keywords**: Route Binding, Substitute Bindings, Route Middleware, Custom Route Binding.

2020-10-05 13:51 UTC, sailingdeveloper commented
Haven't used Laravel in a while and picking it back up now, it's really nice to see that the idea I proposed in https://github.com/laravel/framework/pull/18197 was actually implemented, thanks @browner12 and @taylorotwell!