[6.x] Add existsOr and doesntExistOr to the querybuilder
laravel/framework pull request #30495
Opened 2019-11-01 13:40 UTC by SjorsO

Resubmit of https://github.com/laravel/framework/pull/30479

In my controllers, I often use something like this to validate requests:
```php
$hasOpenDossier = $user->dossiers()
    ->whereNull('closed_at')
    ->exists();

if ($hasOpenDossier) {
    abort(422, 'User already has an open dossier');
}
```

With this PR, I can do this instead:
```php
$user->dossiers()
    ->whereNull('closed_at')
    ->doesntExistOr(function () {
        abort(422, 'User already has an open dossier');
    });
````

This way I don't have to create a temporary variable, and the code is more logically grouped together (which is especially nice in more complex projects where you can have three of these checks in a row). 

I would almost always use this feature for aborting. It could also be used for other things, but to be honest I can't really think of any. (maybe adding a `doesntExistOrAbort` macro to my projects would be a better solution).

---

An alternative to adding two new methods is adding an optional `$callback` argument to the `exists()` and `doesntExist()` methods. I think adding two new methods is a cleaner way of doing it, mainly because it keeps the parameters and return type of `exists()` and `doesntExist()` simple.

2019-11-01 14:29 UTC, driesvints commented
@SjorsO can you rebase with the 6.x branch? StyleCI updated their default checks today. Rebasing should make the checks pass again.

2019-11-01 20:03 UTC, chuckrincon commented
@SjorsO It's possible to use the null coalescing operator (??), produces the same return

```php
// Before
return $this->exists() ? true : $callback();

// After
return $this->exists() ?? $callback();
```

2019-11-02 07:43 UTC, SjorsO commented
> @SjorsO It's possible to use the null coalescing operator (??), produces the same return
> 
> ```
> // Before
> return $this->exists() ? true : $callback();
> 
> // After
> return $this->exists() ?? $callback();
> ```

`??` will only call the callback if `exists` is null or not set, which is never the case.

I think you're thinking about `?:`, which would be slightly shorter than the current code. But i prefer not being fancy and just using a simple shorthand if statement.

2019-11-05 09:47 UTC, netpok commented
I'm not sure about this,
one can already use the:

```php
abort_if(
    $user->dossiers()->whereNull('closed_at')->exists(),
    422, 'User already has an open dossier'
);
```
method which is way more expressive.

The `findOr` method is used to provide a default when the record not exists, but I don't see a use-case when one want to do that with an `exists()` to use the return value and the `…->exists() ?: randomStatement` is not enough.

2019-11-05 10:06 UTC, SjorsO commented
Queries often don't fit neatly on a single line, in that case you can't use `abort_if` like that

2019-11-05 10:14 UTC, netpok commented
I would argue than it probably should be moved to a method or better to the FormRequest object, but that's not in the scope of this pull request.

2019-11-05 10:24 UTC, netpok requested changes

2019-11-05 10:24 UTC, netpok commented on src/Illuminate/Database/Query/Builder.php
> +     * @param  \Closure $callback
I think it would be better to typehint Closure|bool

2019-11-05 10:24 UTC, netpok commented on src/Illuminate/Database/Query/Builder.php
> +    public function existsOr(Closure $callback)
Allow all types here (should only be closure and bool, but there is some time till union types will be available).

2019-11-05 10:24 UTC, netpok commented on src/Illuminate/Database/Query/Builder.php
> +        return $this->exists() ? true : $callback();
And return `$this->exists() ?: value($callback)`

I prefer `?:` over `? true :` but maybe that's just me.

2019-11-05 14:11 UTC, merged

2019-11-30 04:15 UTC, s51983 commented
When  Model use SoftDeletes, existsOr / doesntExistOr didn't check deleted_at columns 

```
 User::where('id', $id)->exists();

SQL: select exists(select * from `users` where `id` = ? and `users`.`deleted_at` is null) as `exists`
```

```
 User::where('id', $id)->existsOr(function(){
    abort(404,'User not exists!')
});

SQL: select exists(select * from `users` where `id` = ?) as `exists`
```

How to fix it?