Fixed migration's data source configuration does not take effect.
laravel/framework pull request #30503
Opened 2019-11-03 13:05 UTC by youmingdot

When we use statement like `Schema::create` in Migration, the connection property defined in Migration do not take effect. This is because Schema uses the default data connection. This pull request makes Migration as it describes it.

```php
<?php

namespace Illuminate\Database\Migrations;

abstract class Migration
{
    /**
     * The name of the database connection to use.
     *
     * @var string|null
     */
    protected $connection;

    // ...

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            // ...
        });
    }
}
```

2019-11-05 09:36 UTC, netpok requested changes

2019-11-05 09:36 UTC, netpok commented on src/Illuminate/Database/Migrations/Migrator.php
> +                if ($runInConnection = $migration->getConnection()) {
Either this variable should be dropped

2019-11-05 09:36 UTC, netpok commented on src/Illuminate/Database/Migrations/Migrator.php
> +                if (isset($defaultConnectionName)) {
or it should be used here instead of the isset

2019-11-05 09:36 UTC, netpok commented on src/Illuminate/Database/Migrations/Migrator.php
> +    protected function resolveConnectionName($connection)
Do we need to split this out, it is not used anywhere else?

2019-11-05 09:46 UTC, mfn commented
But doesn't `Schema::connection('…')->create(…)` do this already or am I missing something?

2019-11-05 09:57 UTC, netpok commented
> But doesn't `Schema::connection('…')->create(…)` do this already or am I missing something?

Yes but it's already [part of the framework](https://github.com/laravel/framework/blob/1c44dff3eb1a338f807ed59b9cfedace72322458/src/Illuminate/Database/Migrations/Migration.php#L12) and the other way you need to define it at least twice.

2019-11-05 11:50 UTC, mfn commented
So should we remove `Schema::connect()` after this PR?

I mean, why two things to do the same _here_ 😄

2019-11-05 12:00 UTC, netpok commented
While I'm definitely on the side of the one-table-per-migration group removing it would prevent one to create or check multiple tables in multiple connections or just check. (Personally I wouldn't shed many tears)

2019-11-05 14:06 UTC, closed without merging

2019-11-05 14:31 UTC, mfn commented
> removing it would prevent one to create or check multiple tables in multiple connections

Smart thinking, didn't occur to me; thanks for sharing this use case 👍

2019-11-06 01:10 UTC, youmingdot commented
> Use Schema::connection().

So, Migration::$connection can be removed? While it's confused.