[7.x] Restore default connection after Artisan migrate/seed call
laravel/framework pull request #30720
Opened 2019-11-30 06:18 UTC by crynobone

This will be useful when having an application that handle migrations
for more than one database connection.

The side affect of current implementation is that until the request
(web/console) is terminated the database will used the latest migration
connection as default.

Solved #28253

Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>

2019-11-30 10:56 UTC, driesvints requested changes
Thanks @crynobone. Just some styling remarks.

2019-11-30 10:56 UTC, driesvints commented on src/Illuminate/Database/Migrations/Migrator.php
> +     *
```suggestion
```

2019-11-30 10:56 UTC, driesvints commented on tests/Database/DatabaseMigratorIntegrationTest.php
> +            'driver'    => 'sqlite',
```suggestion
            'driver' => 'sqlite',
```

2019-11-30 10:56 UTC, driesvints commented on tests/Database/DatabaseMigratorIntegrationTest.php
> +        if (! $repository2->repositoryExists()) {
```suggestion

        if (! $repository2->repositoryExists()) {
```

2019-11-30 10:56 UTC, driesvints commented on src/Illuminate/Database/Migrations/Migrator.php
> +            $this->previousConnection = $this->resolver->getDefaultConnection();
```suggestion
            $this->previousConnection = $this->resolver->getDefaultConnection();

```

2019-11-30 10:56 UTC, driesvints commented on src/Illuminate/Database/Console/Migrations/StatusCommand.php
> +        $previousConnection = $this->migrator->getConnection();
```suggestion
        $previousConnection = $this->migrator->getConnection();

```

2019-11-30 11:25 UTC, crynobone commented on src/Illuminate/Database/Console/Migrations/StatusCommand.php
> +        $previousConnection = $this->migrator->getConnection();
Done

2019-11-30 11:26 UTC, crynobone commented on src/Illuminate/Database/Migrations/Migrator.php
> +            $this->previousConnection = $this->resolver->getDefaultConnection();
Done

2019-11-30 11:26 UTC, crynobone commented on src/Illuminate/Database/Migrations/Migrator.php
> +     *
Done

2019-11-30 11:26 UTC, crynobone commented on tests/Database/DatabaseMigratorIntegrationTest.php
> +            'driver'    => 'sqlite',
Done

2019-11-30 12:24 UTC, GrahamCampbell approved these changes

2019-11-30 12:41 UTC, driesvints approved these changes

2019-12-03 16:01 UTC, taylorotwell commented
I understand the use case but something about this particular design maybe feels a bit weird. For example say I was to just instantiate a migrator directly... call `setConnection`... then call `runPending`... now my connection is set to `null` again?

2019-12-03 16:09 UTC, taylorotwell commented
Is there something preventing us from managing this totally at the comment level? It feels weird for the Migrator to be aware of this and to be managing this state in this way.

2019-12-05 11:00 UTC, crynobone commented
Another alternative is to convert `singleton` to `bind` so it resolve a new instance every time we need migrator and migration repository IoC.

But not sure how we can solve the Seeder command where it change ConnectionResolver defaults.

2019-12-05 15:25 UTC, taylorotwell commented
The changes to seed and status commands seem fine to me. I'm mainly curious if we could just take a similar approach on the migrations. It feels weird for the migrator to be maintaining that state.

2019-12-05 18:27 UTC, GrahamCampbell commented
> It feels weird for the migrator to be maintaining that state.

I agree. It feels like this is actually a code smell to tell us that we shouldn't need to mutate the state in this way.

2019-12-05 18:28 UTC, GrahamCampbell commented
Instead of setting the connection, we should pass the actual connection object around, somehow...

2019-12-06 16:13 UTC, merged

2019-12-06 16:14 UTC, taylorotwell commented
I made pretty big changes to the Migrator on this and got rid of all previous connection state. Added a new `usingConnection(name, fn)` method that we can use to run a block of code with a different connection. Then tweaked migrate and rollback commands to use this.

2019-12-06 17:52 UTC, GrahamCampbell commented
👍