[7.x] Fix tests based on new Migrator::usingConnection().
laravel/framework pull request #30781
Opened 2019-12-07 02:34 UTC by crynobone

Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>

2019-12-07 14:13 UTC, GrahamCampbell requested changes

2019-12-07 14:13 UTC, GrahamCampbell commented on tests/Database/DatabaseMigrationResetCommandTest.php
> +        $migrator->shouldReceive('usingConnection')->once()->with(null, m::type('Closure'))->andReturnUsing(function ($connection, $callback) {
Probs should be `Closure::class` rather than `'Closure'` (and imported).

2019-12-09 09:57 UTC, GrahamCampbell approved these changes

2019-12-09 12:10 UTC, merged

2019-12-09 12:10 UTC, driesvints commented
Thanks Mior!