[7.x] Add the exceptionContext method to the exception handler
laravel/framework pull request #30784
Opened 2019-12-07 14:48 UTC by AbdelElrafa

This PR will add the exceptionContext method to the exception handler to allow exception specific data to be added to the logging context.

Currently if you need to get context off of an exception to pass it to the logger you would need to override the whole report method and do it there.

Adding this method allows us to add context off of an exception by simply implementing the method in the applications Handler class. This is not a breaking change.

Example: 

```PHP

throw (new CustomException())->setCustomProperty('foo');

// App/Exceptions/Handler.php
protected function exceptionContext(Exception $e)
{
    if ($e instanceof CustomException) {
        return ['custom_context' => $e->getCustomProperty()];
    }
}
````

Now the logger can get the custom exception context and handle it just like it handles the other context.

2019-12-07 14:57 UTC, GrahamCampbell requested changes

2019-12-07 14:57 UTC, GrahamCampbell commented on src/Illuminate/Foundation/Exceptions/Handler.php
> +    protected function exceptionContext(Exception $e)
This should be `Throwable`.

2019-12-09 12:18 UTC, driesvints commented
@AbdelElrafa can you rebase with master? Tests on master have been fixed.

2019-12-09 13:13 UTC, GrahamCampbell commented
I think we also need tests for this feature too, so that it doesn't get broken in the future.

2019-12-09 14:30 UTC, AbdelElrafa commented
@driesvints I rebased.

@GrahamCampbell I had looked into it but dismissed the tests because I didn't find any tests for the context method. The only test that's there is to test that the exception is passed in the context. Let me know if I still should find a way to test it.

2019-12-09 15:00 UTC, taylorotwell commented
I'll just handle this when I merge 6.x forward this week.

2019-12-09 15:00 UTC, closed without merging

2019-12-09 15:02 UTC, taylorotwell commented
Hey @AbdelElrafa, after looking at this again. I think my intention was that you could already override the `context` method and return `array_merge(parent::context(), ['my-context' => 'foo'])`. Does that not work for you?

2019-12-09 15:02 UTC, taylorotwell commented
Ah, never mind. You are wanting exception specific context.