[6.x] Allow formatting an implicit attribute using a closure
laravel/framework pull request #31246
Opened 2020-01-27 13:41 UTC by themsaid

This PR adds a `setImplicitAttributesFormatter` method to the validator that allows the instance to output a message that says:

```
age at line 1 must be an integer
```

instead of 

```
0.age must be an integer
```

```php
validator(
    [['age' => 'thirty']],
    ['*.age' => 'integer']
)->setImplicitAttributesFormatter(function ($attribute) {
    [$line, $attribute] = explode('.', $attribute);

    return sprintf('%s at line %d', $attribute, $line + 1);
})->validate();
```

2020-01-27 13:42 UTC, GrahamCampbell requested changes

2020-01-27 13:42 UTC, GrahamCampbell commented on src/Illuminate/Validation/Validator.php
> +    public function setImplicitAttributesFormatter(callable $formatter)
Maybe allow this to be null, so it can be unset too?

2020-01-27 13:42 UTC, GrahamCampbell requested changes

2020-01-27 13:42 UTC, GrahamCampbell commented on src/Illuminate/Validation/Validator.php
> +     * @var callable
This is `callable|null`, since it may never be set.

2020-01-27 13:48 UTC, GrahamCampbell requested changes

2020-01-27 13:48 UTC, GrahamCampbell commented on src/Illuminate/Validation/Validator.php
> +    public function setImplicitAttributesFormatter($formatter)
You can keep the typehint `(callable $formatter = null)`

2020-01-27 15:12 UTC, merged

2020-01-28 23:44 UTC, MarceauKa commented
Hi @themsaid , I'm just reading the 6.13 changelog. Can you help me to understand this new behavior with a real case usage?

2020-01-29 14:50 UTC, PovilasKorop commented
Hi @themsaid! Great feature it seems, I want to shoot a video about it, but I don't understand - is it possible to use it with `FormRequest` classes? Or what would be the syntax with `$this->validate()` in Controller?

2020-01-29 14:57 UTC, themsaid commented
@PovilasKorop You'll want to use:

```
function withValidator($validator){
    $validator->setImplicitAttributesFormatter(function ($attribute) {
        [$line, $attribute] = explode('.', $attribute);

        return sprintf('%s at line %d', $attribute, $line + 1);
   });
}
```

@MarceauKa the example above is a real use case :)

2020-01-29 15:54 UTC, PovilasKorop commented
@themsaid thanks, it's working, tried it with a bit changed example, will shoot a video tomorrow.
For anyone else, here's the code:

```
<?php

namespace App\Http\Requests;

use App\Order;
use Gate;
use Illuminate\Foundation\Http\FormRequest;
use Symfony\Component\HttpFoundation\Response;

class StoreOrderRequest extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'customer_name' => 'required',
            'products.*.product_id' => 'required',
        ];
    }

    function withValidator($validator){
        $validator->setImplicitAttributesFormatter(function ($attribute) {
            [$field, $line] = explode('.', $attribute);
            if ($field == 'products') {
                return 'product number ' . ($line+1);
            }
        });
    }
}
```

2021-08-09 15:46 UTC, ankurk91 commented
I made it working like in Laravel 8.x

```php
    public function withValidator(Validator $validator)
    {
        $validator->setImplicitAttributesFormatter(function ($attribute) {
            return Str::of($attribute)->afterLast('.');
        });
    }
```

This is a hidden gem.