Fixed SqlServerGrammer for tables with schema definition
laravel/framework pull request #31243
Opened 2020-01-27 12:12 UTC by jeff-99

When the migration table is placed in a different schema than dbo (default schema) the `php artisan migrate` commands can't find the created table. 

**Steps to reproduce:** 
in config/database.php change: 

```php
    'migrations' => 'migrations',
```

into 

```php
    'migrations' => 'schemaName.migrations',
```

The bug is fixed by joining the `sys.schemas` table so tables with schema's in the SqlServerGrammar `compileTableExists` method.

2020-01-27 12:15 UTC, jeff-99 commented
Related issues: 

#7556
#8523

2020-01-27 13:20 UTC, GrahamCampbell commented
Could you add some tests to cover this?

2020-01-27 13:57 UTC, driesvints requested changes

2020-01-27 13:57 UTC, driesvints commented on src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php
> +                from sys.columns as col
Please put this back if it's unrelated to the PR.

2020-01-28 14:47 UTC, taylorotwell commented
I am closing this pull request because it lacks sufficient explanation, tests, or both. It is difficult for us to merge pull requests without these things because the change may introduce breaking changes to the framework.

Feel free to re-submit your change with a **thorough** explanation of the feature and tests - integration tests are preferred over unit tests. Please include it's benefit to end users; the reasons it does not break any existing features; how it makes building web applications easier, etc.

Thanks!

2020-01-28 14:47 UTC, closed without merging