new command for listing all commands and respective "classes" in tabular form
laravel/framework pull request #31410
Opened 2020-02-09 14:31 UTC by awebartisan

Currently, there is no "easy" way to see the class responsible for handling the command. 
Many times I find myself ( maybe some other devs too ) inside `vendor` directory to find the class behind a command. This pull request can help us find the required command's class quickly. 

`php artisan commands:list` is inspired from `route:list` command. 
An option can be added to `php artisan list` command like `php artisan list --class` but I think it will make the existing output cluttered. 

A sample output of this command can be seen below:
![image](https://user-images.githubusercontent.com/29105478/74104033-ad0eba80-4b72-11ea-941f-03f68ea623e6.png)

Let me know your thoughts :) 

Thank you!

2020-02-09 19:31 UTC, RFreij commented
An option like - - signature= would be nice here.

If you would, for example, search - - signature=even you'll get
event:clear, event:cache and event:list

2020-02-09 22:54 UTC, GrahamCampbell requested changes

2020-02-09 22:54 UTC, GrahamCampbell commented on src/Illuminate/Foundation/Console/CommandsListCommand.php
> +    protected $headers = ['Signature', 'Class'];
This is not the signature, but the name. Should be `['Name, 'Class']`.

2020-02-10 04:27 UTC, taylorotwell commented
Feel free to release this as a package.

2020-02-10 04:27 UTC, closed without merging