[6.x] Fixes appendRow on console table.
laravel/framework pull request #31469
Opened 2020-02-14 09:02 UTC by crynobone

There's some limitation with the new implementation.

- You can't call command with table from another command (the request to command will use `BufferedOutput`).
- You can't call command with table from a controller.

------- 

IMHO if developer want to use Table with `appendRow()` capability they should manually execute it inside `Command` instead of `table()` because the usage of `ConsoleOutput` on CLI usage while `BufferedOutput` when calling other commands or from a controller.

Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>

2020-02-14 09:48 UTC, GrahamCampbell requested changes

2020-02-14 09:48 UTC, GrahamCampbell commented on tests/Integration/Console/CommandWithTableTest.php
> +        $this->expectException('Symfony\Component\Console\Exception\RuntimeException');
Please use `::class` notation here.

2020-02-14 11:57 UTC, crynobone commented on tests/Integration/Console/CommandWithTableTest.php
> +        $this->expectException('Symfony\Component\Console\Exception\RuntimeException');
done

2020-02-14 13:09 UTC, driesvints commented
Does this fixes all the issues from https://github.com/laravel/framework/issues/31445 ? (see comments after closing)

2020-02-14 13:14 UTC, crynobone commented
> Does this fixes all the issues from #31445 ?

It should because the current behaviour assume `$this->output->getOutput()` always have `section()` method but in reality only implementation of `Symfony\Component\Console\Output\ConsoleOutput` does while Laravel use `Symfony\Component\Console\Output\BufferedOutput` when using `Illuminate\Foundation\Console\Kernel::call()` instead of from `artisan` cli.

2020-02-14 13:18 UTC, crynobone commented
But at the same time, checking the instanceof `$output` will give different output based how you execute the command so I would say it is better to let developer construct `Table` command directly if they want `appendRow()` feature instead of having it available via `InteractsWithIO::table()` 

```php
$output = $this->output->getOutput();

$table = new Table($output instanceof ConsoleOutput ? $output->section() : $output);
```

2020-02-14 14:24 UTC, taylorotwell commented
@crynobone... sooo... do we want to merge this or not? You said it fixed the issue but then you seemed to imply the whole thing was a bad idea? I'm confused.

2020-02-14 16:48 UTC, crynobone commented
@taylorotwell 

You can only use `$table->appendRow()` when you run it directly from say `php artisan command:name`. If you do `Artisan::call('command:name')` it wouldn't work as described in `testItCantExecuteCommandWithTableAndAppendRowDueToBufferedOutput()`.

This PR fixed:

- Running artisan command with table without mocking the output
- Running existing artisan command with table from Controller or another artisan command.
- Addes tests

2020-02-14 17:02 UTC, dbpolito commented
Well with this PR it will fix the tests with commands with usual `table()`, but if you do use `appendRow()` the test will fail because it requires it to be an Section and will throw an error:

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Helper/Table.php#L279-L281

2020-02-14 18:23 UTC, merged

2020-02-14 22:07 UTC, taylorotwell commented
Reverting this entire feature and all related pieces of it @adam-prickett @crynobone ... it's causing continual problems.

2020-02-15 07:17 UTC, crynobone commented
@taylorotwell I'm okay with that, but `CommandWithTest` and `OuputStyle::getOutput()` should be okay to stay in the core