[6.x] Add requeue function to jobs
laravel/framework pull request #31537
Opened 2020-02-19 23:14 UTC by andershagbard

This pull requests adds a `requeue` method to database and Redis jobs. The idea comes from https://github.com/laravel/ideas/issues/1381

The method does the same as the `release` method, but before putting the job back into queue, it decrements the attempts attribute.

This handles an issue like this, where the job could fail, because the attempts attribute had exceeded the tries attribute.

```php
Redis::throttle('key')->allow(10)->every(60)->then(function () {
    try {
        // API logic
    }
    catch (Exception) {
        // Release the job back into the queue
        return $this->release(10);
    }
}, function () {
    // Could not obtain lock...
    return $this->requeue(10);
});
```

I think we possible need to rename this method to something more suited. Maybe `isDeletable` ?
https://github.com/laravel/framework/blob/641a7cda8280ecd3035616d4ce6434434b116624/src/Illuminate/Contracts/Queue/Job.php#L64

_Reopen of #30342_

2020-02-19 23:41 UTC, GrahamCampbell commented
Please update the job contract too.

2020-02-20 10:22 UTC, themsaid commented
I wonder what could be a user case for this? This seems to be a bad practice in my opinion since it'll keep the job in queue forever.

I'd set a proper `$tries` on my job and use `release()` knowing that I won't get myself into a job that would keep failing forever.

2020-02-20 11:16 UTC, andershagbard commented
> I wonder what could be a good use case for this? This seems to be a bad practice in my opinion since it'll keep the job in queue forever.
> 
> I'd set a proper `$tries` on my job and use `release()` knowing that I won't get myself into a situation where I have a job that would keep coming back to the queue forever. Having a few jobs like this could completely block the queue.
> 
> You can also use `retryUntil()` which will basically retry the job until the set time passes no matter how many attempts are incremented. This will make `release()` act like your `requeue()` but with a fail safe.

Obviously, you need to use this function with caution, and not just requeue it on every exception. The use case I mentioned initially is a very good example.

I could also imagine it could be useful if you work with API calls, and your calls are getting throttled. Then I rather use the `requeue` method, and not increase the `attempts`.

2020-02-20 11:18 UTC, themsaid commented
@andershagbard You can use `retryUntil` and never worry about the attempts. I just don't see why we need to add a functionality + extra code while we can already achieve what it's supposed to make possible.

2020-02-20 11:43 UTC, andershagbard commented
> @andershagbard You can use `retryUntil` and never worry about the attempts. I just don't see why we need to add a functionality + extra code while we can already achieve what it's supposed to make possible.

Imagine you use the Redis throttle method, and your job keeps failing because of some exception, if you use the retryUntil, it will keep failing and fill the queue. It could be a resource heavy job failing, and using server resources.

The comments in the linked ideas issue explains it pretty well.

2020-02-20 11:43 UTC, andershagbard commented
> Please update the job contract too.

Updated.

2020-02-20 13:35 UTC, GrahamCampbell commented
Please could you rebase your branch against the latest 7.x, to allow the tests to run against the latest code. `git pull --rebase upstream 7.x && git push --force`

2020-02-20 13:35 UTC, GrahamCampbell commented on src/Illuminate/Queue/Jobs/SyncJob.php
> +     * @param  int   $delay
One too many spaces here after `int`. Should be exactly 2, but there are 3.

2020-02-20 13:36 UTC, GrahamCampbell commented on src/Illuminate/Queue/Jobs/RedisJob.php
> +     * @param  int   $delay
Same, etc.

2020-02-20 13:36 UTC, GrahamCampbell requested changes
I've left some feedback.

2020-02-20 13:55 UTC, themsaid commented
@andershagbard 

That's if you `requeue()`, it'll keep the job forever. However, using `retryUntil` it'll keep retrying until a certain time and then fail. I don't really see why you'd risk and use `requeue()` and have hanging jobs in your queue that you can't clear out.

2020-02-20 14:48 UTC, andershagbard commented
@themsaid I would not call this an edge case. The problem becomes much more frequent if you use a funnel.

Let's take your example as a case. If the job gets locked out three times in a row, it will run `fail()` on the first exception caught.

2020-02-20 14:53 UTC, themsaid commented
I'm just showing an example, you'll need to use a sensible value based on what you need. If you don't want to have any limits then you can clone the job and reset the attempts to `0` and release it back to queue but I wouldn't recommend that ¯\_(ツ)_/¯ .

2020-02-20 15:04 UTC, themsaid commented
@taylorotwell explained a use case to me where this might be needed. However, I think we can achieve this without all the changes in that PR. We could update the payload of the job, reset attempts, and then `release()`.

2020-02-20 15:16 UTC, andershagbard commented
@themsaid Yes, this is basically what this PR does, but I am not sure if there is a solution which works for all drivers, without adding these methods.

2020-02-20 15:17 UTC, themsaid commented
@andershagbard let me tinker with that a bit. Sorry it took me too long to get it 😀

2020-02-20 19:34 UTC, GrahamCampbell requested changes

2020-02-20 19:34 UTC, GrahamCampbell commented on src/Illuminate/Contracts/Queue/Job.php
> +     * @param  int   $delay
One too many spaces

2020-02-20 19:34 UTC, GrahamCampbell commented on src/Illuminate/Queue/InteractsWithQueue.php
> +     * @param  int   $delay
Same

2020-02-20 19:34 UTC, GrahamCampbell commented on src/Illuminate/Queue/Jobs/DatabaseJob.php
> +     * @param  int   $delay
Same

2020-02-20 19:34 UTC, GrahamCampbell commented on src/Illuminate/Queue/Jobs/Job.php
> +     * @param  int   $delay
Same

2020-02-24 13:31 UTC, closed without merging

2020-02-24 13:33 UTC, driesvints commented
@GrahamCampbell why did you close this pr?

2020-02-24 13:34 UTC, GrahamCampbell commented
I didn't. GitHub seems to have messed up. I rebased it, but it only let met push the old commits and denied access with the new stuff, so it thinks the remote branch is exactly laravel/framework 6.x.

2020-02-24 13:42 UTC, GrahamCampbell commented
Now at https://github.com/laravel/framework/pull/31581. Sorry about this!