[6.x] Fix model restoring right after soft deleting it
laravel/framework pull request #31719
Opened 2020-03-03 22:38 UTC by danielsuguimoto

Relates to #31527

When we soft delete a model it becomes dirty, so if we try to restore it after deletion, the deleted_at column is not cleared. We need to sync the model, setting dirty to false, then the restore works.

2020-03-03 23:39 UTC, GrahamCampbell requested changes

2020-03-03 23:39 UTC, GrahamCampbell commented on tests/Database/DatabaseEloquentSoftDeletesIntegrationTest.php
> +     * @throws \Exception
Please remove this.

2020-03-04 14:45 UTC, taylorotwell commented
Hey there, could you send this to the 7.x branch? Thanks.

2020-03-04 15:00 UTC, taylorotwell commented
Nevermind.

2020-03-06 13:34 UTC, merged