Add str words count function
laravel/framework pull request #31890
Opened 2020-03-10 18:34 UTC by itanea

The purpose is to add an helper to count words in a string.

$jdoe = 'My name is John Doe';
echo Str::wordsCount($jdoe);

// display 5

2020-03-10 19:00 UTC, itanea commented
I've updated documentation to : https://github.com/laravel/docs/pull/5876
Hope is this good format ;-)

2020-03-10 19:33 UTC, browner12 commented
Why do we need this method if it's just a wrapper for the PHP native `str_word_count`?

Also, you lose a little bit with this because you can longer pass the optional parameters to `str_word_count`.

2020-03-10 20:43 UTC, itanea commented
> Why do we need this method if it's just a wrapper for the PHP native `str_word_count`?
> 
> Also, you lose a little bit with this because you can longer pass the optional parameters to `str_word_count`.

I understand your position. There is others methods who wrap natives PHP function like mb_substr or ucfirst. Then, I don't think this could be a problem.

But your second point is true. So I will modify to take care of native options of str_word_count.
I will do this today or tomorrow.

Thanks for your comment.

2020-03-10 20:48 UTC, GrahamCampbell commented
Does the native function handle multibyte strings properly? Also, you will need to add tests and update the `Stringish` class too.

2020-03-10 20:49 UTC, GrahamCampbell requested changes

2020-03-10 20:49 UTC, GrahamCampbell commented on src/Illuminate/Support/Str.php
> +     * @param  int  $format
`int|null`

2020-03-10 20:49 UTC, GrahamCampbell commented on src/Illuminate/Support/Str.php
> +     * @param  string  $charlist
`string|null`

2020-03-10 20:49 UTC, GrahamCampbell commented on src/Illuminate/Support/Str.php
> +    public static function wordsCount($value)
Missing parameters.

2020-03-10 20:49 UTC, GrahamCampbell commented on src/Illuminate/Support/Str.php
> +        return str_word_count($value, $format = null, $charlist = null);
Incorrect null assignment.

2020-03-10 20:51 UTC, itanea commented on src/Illuminate/Support/Str.php
> +        return str_word_count($value, $format = null, $charlist = null);
Oups, I'm tired :-(.
I will fix :D

2020-03-10 21:03 UTC, happytodev reviewed
I already fix this. Hope it's good.

2020-03-10 21:27 UTC, GrahamCampbell requested changes
Please also update the `Stringish` class, and add tests for both implementations.

2020-03-11 08:19 UTC, itanea commented
> Please also update the `Stringish` class, and add tests for both implementations.

Sorry, but could you give some more details please ? I didn't found `Stringish` class, Maybe I didn't look hard enough.

Could you give me, please, more details ?

2020-03-11 08:28 UTC, mpyw commented
He probably means `Stringable`

2020-03-11 08:34 UTC, itanea commented
> He probably means `Stringable`

That's what I started looking at. I understand this is to add fluent string operation for this new method.
Ok, I will do it.

2020-03-11 10:29 UTC, itanea commented
> Please also update the `Stringish` class, and add tests for both implementations.

Hello @GrahamCampbell I made changes.
For the Stringable class, I assumed that only the word count made sense. I did not implement the 'format' and 'charlist' options. 

What do you think of that?

2020-03-11 10:29 UTC, itanea commented
> He probably means `Stringable`

Tanks to you ;-)

2020-03-11 10:45 UTC, GrahamCampbell commented
Could you add a rest for the empty string case and a string that just contains a bunch of whitespace?

2020-03-11 10:52 UTC, itanea commented
> Could you add a rest for the empty string case and a string that just contains a bunch of whitespace?

It's done ! ;-)

2020-03-11 10:52 UTC, itanea commented
> Could you add a rest for the empty string case and a string that just contains a bunch of whitespace?

It's done ! ;-)

2020-03-11 12:47 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2020-03-11 12:47 UTC, closed without merging

2020-03-11 14:01 UTC, itanea commented
Thanks  @GrahamCampbell for your help.
I understand Taylor point of view. Just a little question, does this mean that it will never be implemented, or does it mean that it will eventually be postponed?