[7.x ]Stop using deprecated setMethods.
laravel/framework pull request #32234
Opened 2020-04-04 16:02 UTC by lucasmichot

`\PHPUnit\Framework\MockObject\MockBuilder::setMethods` is deprecated.
`onlyMethods` and/or `addMethods` should be used instead.

2020-04-04 16:05 UTC, GrahamCampbell commented
Please patch this on 6.x.

2020-04-04 16:06 UTC, GrahamCampbell commented
Just like https://github.com/laravel/framework/pull/32212, we want 6.x to be able to upgrade to PHPUnit 10 when it comes out so our LTS release can run properly on PHP 8.0 and 8.1 when they are released.

2020-04-04 16:21 UTC, lucasmichot commented
> Just like #32212, we want 6.x to be able to upgrade to PHPUnit 10 when it comes out so our LTS release can run properly on PHP 8.0 and 8.1 when they are released.

I was not aware of that.

2020-04-04 22:31 UTC, GrahamCampbell commented
There are some new warnings:

```
1) Illuminate\Tests\Auth\AuthPasswordBrokerTest::testIfUserIsNotFoundErrorRedirectIsReturned
Cannot use addMethods() on "Illuminate\Auth\Passwords\PasswordBroker" mock because mocked methods were already configured.

2) Illuminate\Tests\Auth\AuthPasswordBrokerTest::testResetRemovesRecordOnReminderTableAndCallsCallback
Cannot use addMethods() on "Illuminate\Auth\Passwords\PasswordBroker" mock because mocked methods were already configured.

3) Illuminate\Tests\Cache\CacheMemcachedStoreTest::testGetReturnsNullWhenNotFound
Trying to set mock method "get" with onlyMethods, but it does not exist in class "stdClass". Use addMethods() for methods that don't exist in the class.

4) Illuminate\Tests\Cache\CacheMemcachedStoreTest::testMemcacheValueIsReturned
Trying to set mock method "get" with onlyMethods, but it does not exist in class "stdClass". Use addMethods() for methods that don't exist in the class.

5) Illuminate\Tests\Cache\CacheMemcachedStoreTest::testMemcacheGetMultiValuesAreReturnedWithCorrectKeys
Trying to set mock method "getMulti" with onlyMethods, but it does not exist in class "stdClass". Use addMethods() for methods that don't exist in the class.
```

2020-04-05 08:59 UTC, GrahamCampbell commented
Looks like phpunit 10 on laravel 6 is not going to happen: https://github.com/sebastianbergmann/phpunit/pull/3687#issuecomment-609359756.

2020-04-05 09:01 UTC, GrahamCampbell requested changes

2020-04-05 09:01 UTC, GrahamCampbell commented on tests/Queue/QueueSqsQueueTest.php
> +        parent::setUp();
No need for all these. Please remove those changes to keep the PR atomic.

2020-04-06 09:12 UTC, driesvints commented
I really doubt we'll be supporting PHPUnit 10 on Laravel 6 tbh.

2020-04-06 09:13 UTC, driesvints commented
@lucasmichot reopening this. Not sure why you closed this again?

2020-04-06 09:35 UTC, GrahamCampbell commented
> I really doubt we'll be supporting PHPUnit 10 on Laravel 6 tbh.

It looks that way...

2020-04-06 13:35 UTC, merged