[7.x] Updated ValidatesAttributes::validateUrl to use Symfony/Validator 5.1 regex
laravel/framework pull request #32302
Opened 2020-04-08 20:02 UTC by bsacharski

The regex used by url validation logic was previously derived from version
2.7.4 of Symfony Validator component. As it turns out, old regex had a bug
where it wouldn't accept urls where domain was a hostname ending with a digit.
As such, the urls like http://domain1/ would be considered as invalid.

To fix this issue I've updated \Illuminate\Validation\Concerns\ValidatesAttributes::validateUrl
method using regex derived from version 5.1.0 of the Symfony Validator component.
To make sure that the fix works, new test cases were also added.

2020-04-08 22:08 UTC, GrahamCampbell requested changes

2020-04-08 22:08 UTC, GrahamCampbell commented on tests/Validation/ValidationValidatorTest.php
> +     * @group WIP
?

2020-04-08 22:08 UTC, GrahamCampbell commented on src/Illuminate/Validation/Concerns/ValidatesAttributes.php
> +         * This pattern is derived from Symfony Validator component, file Constraints/UrlValidator.php (5.1.0).
Please leave this as the class name.

2020-04-08 22:09 UTC, GrahamCampbell requested changes

2020-04-08 22:09 UTC, GrahamCampbell commented on src/Illuminate/Validation/Concerns/ValidatesAttributes.php
> +         * This pattern is derived from Symfony Validator component, file Constraints/UrlValidator.php (5.1.0).
There is no 5.1.0 version, also?

2020-04-09 05:42 UTC, closed without merging

2020-04-09 05:53 UTC, bsacharski commented
@GrahamCampbell thanks for review. I guess this is why I shouldn't code before going to bed and few minutes after waking up (rebased the master onto 7.x-derived branch...) :smile: 

Created new PR (with properly used & referenced STABLE Symfony version) #32307