[7.x] MySQL: `whereNull`/`whereNotNull` fir for json.
laravel/framework pull request #32417
Opened 2020-04-17 10:51 UTC by LastDragon-ru

This PR fixes #31473, please see issue for more details, in short:

```sql
set @a='{"value":null}';

select
-- Actual behavior whereNull/whereNotNull
json_unquote(json_extract(@a, '$."value"')) is null,     -- false but should be true because value = null
json_unquote(json_extract(@a, '$."value"')) is not null, -- true  but should be false 

-- Expected
(json_extract(@a, '$."value"') is null     OR  json_type(json_extract(@a, '$."value"')) = 'NULL'),  -- true, ok
(json_extract(@a, '$."value"') is not null AND json_type(json_extract(@a, '$."value"')) != 'NULL')  -- false, ok
;
```

_PS: I tested it only for MySQL, probably would be good also test for MariaDB and Percona._

2020-04-17 11:48 UTC, if4lcon commented
`whereJsonLength` works for me

```
//where not null
->whereJsonLength('json', '>=', 1); 
```

```
//where  null
->whereJsonLength('json', '<=', 0); 
```

2020-04-17 11:58 UTC, LastDragon-ru commented
> whereJsonLength works for me

@if4lcon is it work if key does not exist?

2020-04-18 17:29 UTC, taylorotwell commented
@staudenmeir do you have any feedback on this?

2020-04-18 20:00 UTC, staudenmeir commented
Looks good to me. Great tests!

2020-04-20 08:31 UTC, driesvints submitted a review, later dismissed

2020-04-20 08:31 UTC, driesvints commented on tests/Integration/Database/DatabaseMySqlConnectionTest.php
> +            'nested key exists and not null' => [false,    'nested->value',     ['nested' => ['value' => false]]],
Please remove the indentation here.

2020-04-20 12:44 UTC, GrahamCampbell requested changes

2020-04-20 12:44 UTC, GrahamCampbell commented on src/Illuminate/Database/Query/Grammars/MySqlGrammar.php
> +    protected function whereNull(Builder $query, $where)
Missing phpdoc.

2020-04-20 12:44 UTC, GrahamCampbell commented on src/Illuminate/Database/Query/Grammars/MySqlGrammar.php
> +    protected function whereNotNull(Builder $query, $where)
Same

2020-04-20 14:03 UTC, merged

2020-04-20 14:04 UTC, taylorotwell commented
Fixed PHP doc issues.