[7.x] Add Callbacks with Output to Console Schedule
laravel/framework pull request #32633
Opened 2020-05-01 18:53 UTC by DougSisk

Our health check provider allows POSTing output logs. Currently there's no built in way to do this. Instead of trying to figure out a one-size-fits-all to POST, my proposal is to use callbacks. This way you can use any kind of HTTP library you want, attach additional data, filter the output, etc.

I took the `$onlyIfOutputExists` argument from the `emailOutputTo()` command, so you can optionally only run the callback if an output was generated.

There are 4 callable methods, similar to the ping URL methods:
- `thenWithOutput()`
- `thenIfWithOutput()`
- `onSuccessWithOutput()`
- `onFailureWithOutput()`

Example:
```
$schedule->command('inspire')
    ->onSuccessWithOutput(function ($text) {
        Http::send('POST', 'https://healthcheckservice.test/abc123', [
            'body' => $text,
        ]);
    })
    ->daily();
```

2020-05-01 19:02 UTC, GrahamCampbell requested changes

2020-05-01 19:02 UTC, GrahamCampbell commented on src/Illuminate/Console/Scheduling/Event.php
> +     * @param  Closure $callback
Missing slash and space.

2020-05-03 16:27 UTC, merged

2020-05-03 16:40 UTC, taylorotwell commented
I made a few tweaks to this. The "output" is injected into the Closure using the container->call() method like the other callbacks. This means you must name the variable $output. 

Which leads me to my next point, I think these methods shouldn't really be called directly and in 8.x I'm going to make the standard `then` callbacks reflect into the Closure and inject a `Stringable $output` of the Closure is requesting it.

2020-05-03 16:49 UTC, taylorotwell commented
OK, got it fixed up on 8.x (master branch)... works with `after`, `then`, `onSuccess`, `onFailure`:

![image](https://user-images.githubusercontent.com/463230/80920232-0b8fa300-8d34-11ea-8675-b6c6a9cc2d6c.png)