7.x dev
laravel/framework pull request #32732
Opened 2020-05-09 03:42 UTC by yongchengchen

### How to use Self Morph Model Trait

Sometime we need an eloquent model can self morph by the database table config.

#### 1. Base class

```php
<?php
use Illuminate\Database\Eloquent\Concerns\SelfMorphModel;

class Product extends \Illuminate\Database\Eloquent\Model 
{
use SelfMorphModel;
}

class SimpleProduct extends Product 
{
}

class BundleProduct extends Product 
{
}
```

#### 2. Register in Provider class
```
<?php

//on Provider class to register
class Provider extends \Illuminate\Support\ServiceProvider 
{
   public function register() 
   {
      SimpleProduct::registerMorph('simple');
      BundleProduct::registerMorph('bundle');
   }
}
```

#### 3. Prepare database table 'products'
> //products table
id morph_type name
1  simple.        simpleproductname1
2  bundle.       bundleproductname1

#### 4. Self Morph result
```
Product::find(1).    will return instance of SimpleProduct
Product::find(2).    will return instance of BundleProduct
```

2020-05-09 08:20 UTC, GrahamCampbell requested changes

2020-05-09 08:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/SelfMorphModel.php
> +     * register a morph type to a class.
Register

2020-05-09 08:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/SelfMorphModel.php
> +     * find the class morph type(from class name to alias).
Find

2020-05-09 08:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/SelfMorphModel.php
> +     */
missing param and return doc

2020-05-09 08:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/SelfMorphModel.php
> +     */
same

2020-05-09 08:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/SelfMorphModel.php
> +     * get all morph types(alias).
etc

2020-05-09 08:20 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/SelfMorphModel.php
> +    protected function newMorphInstance(array $attributes, $fillAttributes = true)
etc

2020-05-09 15:29 UTC, devcircus commented
Looks like a signature change to a public method. If so, would need to go to master.

In 7.x, causes the following:
```
Declaration of App\Models\Model::newInstance($attributes = Array, $exists = false) should be compatible with Illuminate\Database\Eloquent\Model::newInstance($attributes = Array, $exists = false, $fillAttributes = true)
```

2020-05-11 14:39 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2020-05-11 14:39 UTC, closed without merging