[6.x] Add return types to guard method
laravel/framework pull request #32772
Opened 2020-05-12 07:07 UTC by mr-feek

Rather than relying on `mixed`, we can narrow down the return type of `Auth::guard` to be a union of `Guard` and `StatefulGuard`. This is what is currently documented as the return type for `AuthManager::guard`

------
I'm considering this a bug, hence sending it to 6.x. The [Laravel Psalm Plugin](https://github.com/psalm/psalm-plugin-laravel) reports 

```
MixedMethodCall | Cannot determine the type of the object on the left hand side of this expression
```

Therefore all developers who are interested in using Psalm will also run into this warning

2020-05-12 07:11 UTC, GrahamCampbell requested changes
Please change the return doc for the actual implementation/interface too. Those must be exactly the same as the facade doc.

2020-05-12 07:13 UTC, mr-feek commented
@GrahamCampbell Forgive me if I'm misunderstanding something, but the `AuthManager::guard` method is already documented to be returning a union of `Guard` and `StatefulGuard`. https://github.com/laravel/framework/blob/6.x/src/Illuminate/Auth/AuthManager.php#L62 

Is there another place needing an update too?

Thanks for having a look!

2020-05-12 07:15 UTC, mr-feek commented
Ah, I assume you mean `Illuminate\Contracts\Auth\Factory`

2020-05-12 07:21 UTC, GrahamCampbell commented
And also to all classes that implement the interface.

2020-05-12 13:41 UTC, taylorotwell commented
Closing since this doesn't update the implementations.

2020-05-12 13:41 UTC, closed without merging

2020-05-12 16:58 UTC, mr-feek commented
Forgive me if I'm being dense 😬 I can't find any other concrete instances of this interface besides `AuthManager`, which already has this docblock. Could someone point me to the missing implementations please 🙏 

`function auth($guard = null)` in helpers.php also has the correct docblock

2020-05-12 21:12 UTC, mr-feek commented
@taylorotwell @GrahamCampbell maybe if one of you could point me in the right direction please!

2020-05-14 20:27 UTC, brysonreece commented
@taylorotwell Better documentation is still a benefit, no? Even though it may not affect any code execution, docblock clarity still seems like a plus.