[7.x] Console command test output dumping
laravel/framework pull request #32927
Opened 2020-05-21 20:14 UTC by olsgreen

A rework of my original PR #32658, this allows retrieval/dumping of a commands output after test execution and additionally automatically dumps the output of a command on expectation failure.

As noted in laravel/ideas#1656, it's currently difficult to determine the cause of console command test failures as there is no easy way to get at the output. This remedies that by adding getOutput() and dumpOutput() methods to the PendingCommand class to trigger a dump of the commands output after its execution.

An example:

    $this->artisan('inspire')
        ->expectsOutput('Life is like riding a bicycle. To keep your balance, you must keep moving.')
        ->assertExitCode(0);

will yield something similar to:

    Output "Life is like riding a bicycle. To keep your balance, you must keep moving." was not printed. The output of the command was:

    The only way to do great work is to love what you do. - Steve Jobs

    Output "Simplicity is an acquired taste. - Katharine Gerould" was not printed.
    .../framework/src/Illuminate/Testing/PendingCommand.php:254
    .../framework/src/Illuminate/Testing/PendingCommand.php:225
    .../Testing/PendingCommand.php:331
    .../MyProject/tests/CommandTestCase.php:86

Or force the dumping of the output to the console even after a successful outcome:

    $this->artisan('inspire')
        ->expectsOutput('Success is not final, failure is not fatal: it is the courage to continue that counts.')
        ->assertExitCode(0)
        ->dumpOutput();

You can also retrieve the output and then test using regular helpers allowing more complex output assertions.

    $output = $this->artisan('inspire')
        ->expectsOutput('Life is like riding a bicycle. To keep your balance, you must keep moving.')
        ->assertExitCode(0)
        ->getOutput();

    $this->assertStringContainsString('Life is like riding a bicycle.', $output);

2020-05-22 04:05 UTC, peterjaap commented
@olsgreen that looks better! Although for me, it doesn't print out the bottom 4 lines. For example, when my seeder adds 5 tasks and my test lists them, I only see the first 2 tasks;

```
   RUNS  Feature\TaskListTest
  • execute task list with task

  Tests:  5 passed, 1 pending
^ """
+----+-------------------------------------------+------------------------------------------------------------------------------------------------+--------------+----------+\n
| id | title                                     | description                                                                                    | completed_at | category |\n
+----+-------------------------------------------+------------------------------------------------------------------------------------------------+--------------+----------+\n
| 1  | A explicabo assumenda et odit.            | Cupiditate neque dignissimos et sapiente nobis velit officiis sapiente nesciunt odit.          |              | Car      |\n
| 2  | Nostrum et sint facere consequatur alias. | Fuga impedit odit cupiditate ea praesentium rerum nihil ut magni inventore eum.                |              | House    |\n

   PASS  Feature\TaskListTest
  ✓ execute task list
  ✓ execute task list with task

```

Tasks with ids 3, 4 and 5 are missing, as is the bottom border of the table.

2020-05-22 04:17 UTC, peterjaap commented
Maybe you could also `return $this;` in `dumpOutput()` so we can chain it?

```
    public function dumpOutput()
    {
        dump($this->getOutput());

        return $this;
    }
```

Allows us to do;

```
        $output = $this->artisan('inspire')
            ->assertExitCode(0)
            ->dumpOutput()
            ->getOutput();
```

In case you want to debug the output _and_ run phpunit assertions on the output later in the test.

2020-05-22 07:03 UTC, olsgreen commented
Done.

The issue with `dump()` and laravels testing command is a separate issue. Other testing helpers use it and are subject to the same problem: https://github.com/laravel/framework/blob/7ebd21193df520d78269d7abd740537a2fae889e/src/Illuminate/Testing/TestResponse.php#L1177

2020-05-22 08:24 UTC, GrahamCampbell requested changes

2020-05-22 08:24 UTC, GrahamCampbell commented on src/Illuminate/Testing/OutputRecorder.php
> +     */
missing return void doc

2020-05-22 08:24 UTC, GrahamCampbell commented on src/Illuminate/Testing/OutputRecorder.php
> +        ?int $verbosity = self::VERBOSITY_NORMAL,
don't use scala types please

2020-05-22 08:24 UTC, GrahamCampbell commented on src/Illuminate/Testing/OutputRecorder.php
> +        bool $decorated = false,
same

2020-05-22 08:24 UTC, GrahamCampbell commented on src/Illuminate/Testing/PendingCommand.php
> +        dump($this->getOutput());
where is the dump method defined?

2020-05-22 14:09 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2020-05-22 14:09 UTC, closed without merging

2020-05-22 14:38 UTC, peterjaap commented
True, this isn't a bug, and I see where you are coming from, but there are a ton of people running into this, as is shown in https://github.com/laravel/ideas/issues/1656. Imho a great addition.

2020-05-22 14:51 UTC, olsgreen commented
@taylorotwell I've got to query the boilerplate response. Closed due to the bloat additional `OutputRecorder` class? Would you be open to another PR that fixes the underlying issue of not being able to get at command output in a cleaner way? (i.e. a refactor of `PendingCommand` away from using the BufferedOutput mock and using the same SeeInOrder class as TestResponse)

2020-05-27 12:22 UTC, milosmiric commented
I would like to add to this discussion that it would be great if we could fix test dump output to show everything and not just few lines.

Scenario:

I am working on the test codes locally and I'm running them inside a shell on docker.

Test code
```php
public function testRetrieveUser(): void
    {
        // retrieve current user details
        $retrieveUserResponse = $this->actingAs($this->adminUser)->get('/api/users/' . $this->adminUser->id);

        $retrieveUserResponse->assertSuccessful();

        $retrieveUserResponse->dump();


    }
```

And here is what i get in console:

```php
RUNS  Tests\Feature\UsersManagementTest
• retrieve user
Tests:  5 passed, 3 pending
{#4297
+"id": 7
+"username": "chadd33"
+"first_name": "Howard"
+"last_name": "Torphy"
WARN  Tests\Feature\UsersManagementTest
✓ retrieve user
r create user → This test did not perform any assertions /var/www/html/tests/Feature/UsersManagementTest.php:39 
✓ example
Tests:  1 risked, 7 passed                                                                                                                                                  Time:   0.80s
```

As you can see my expectation would be to see whole response when i do `php artisan test` as recommended way of running these tests in documentation

2021-07-20 00:14 UTC, jonnylink commented
@taylorotwell respectfully, I think this is less about adding a new feature than it is about fixing a current feature that not fit for use. The assertion does not follow best practice by outputting the expected and the actual, which is what all phpunit assertions do. As it stands this assertion is more a liability than an asset.