[8.x] Add support for relative links in filesystem
laravel/framework pull request #33882
Opened 2020-08-14 19:36 UTC by MrMicky-FR

This PR add support for relative symlinks in Filesystem, simply by moving the code from StorageLinkCommand to Filesystem so it's reusable. 

By default links are not relatives so the current behavior don't change.

With this, relative links can be directly created in the framework or in an Laravel application without the need to add the same code to make relatives links outside of the StorageLinkCommand.

```php
// Before 
$target = (new \Symfony\Component\Filesystem\Filesystem())->makePathRelative($target, dirname($link));
File::link($target, $link);

// After
File::link($target, $link, true);
```

2020-08-15 09:35 UTC, driesvints commented
Might be better to move that to a new `relativeLink` method instead of adding a boolean param.

2020-08-15 17:21 UTC, MrMicky-FR commented
> Might be better to move that to a new `relativeLink` method instead of adding a boolean param.

I added a boolean to make it easier to use it with a condition (like in StorageLinkCommand) without having to add an if/else block, but if you prefer I can move it to a `relativeLink` method.

2020-08-15 22:28 UTC, GrahamCampbell commented
I think a separate method is best. It was one of Laravel's original design principles to avoid unnecessary boolean parameters, when intent can be better communicated through method names.

2020-08-16 12:35 UTC, GrahamCampbell requested changes

2020-08-16 12:35 UTC, GrahamCampbell commented on src/Illuminate/Filesystem/Filesystem.php
> +     * @param string $target
Please follow the code style of the other phpdoc.

2020-08-16 12:38 UTC, GrahamCampbell approved these changes

2020-08-17 13:31 UTC, merged