[6.x] add support for nested keys in guarded property for JSON columns.
laravel/framework pull request #34640
Opened 2020-10-02 19:03 UTC by lupinitylabs

As a follow up to #34299, here is the proposed fix for the broken mass assignment of JSON columns when using `$guarded` instead of `$fillable` on an Eloquent Model, which was introduced introduced with the security fix #33777 . Sorry for the delay...

The PR splits key names in JSON `column->path` expression notation and checks all components of the path for presence in the `$guarded` property of the Eloquent Model. Therefore, given a key name of `meta->languages->en`, `isGuarded()` will return `true` if `meta`, `meta->languages` or `meta->languages->en` are guarded.

For the recently added `isGuardableColumn()` check in #33777 , the path after the actual JSON column name is discarded beforehand, thus only `meta` will be checked for actual existence in the table column list, because anything else will of course always be considered guarded.

2020-10-02 20:05 UTC, taylorotwell commented
So let's say "meta->languages->en" is guarded. I can craft a request to insert anything else I want into meta->languages?

2020-10-02 20:19 UTC, GrahamCampbell requested changes

2020-10-02 20:19 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php
> +     * @param $key
syntax error

2020-10-02 20:38 UTC, lupinitylabs commented
> 
> 
> So let's say "meta->languages->en" is guarded. I can craft a request to insert anything else I want into meta->languages, for example "meta->languages->foobar"

Correct. This is the behavior I would expect, since `meta->languages->foobar` is not guarded. The only reason why `meta` and `meta->languages` need to be guarded is that otherwise you could do something like `->update(['meta->languages' => '{ "en": "Anything you want" }'])`, which would effectively circumvent the guarding.

2020-10-02 20:44 UTC, lupinitylabs commented on src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php
> +     * @param $key
Added the missing string type. Thanks!

2020-10-05 13:49 UTC, taylorotwell commented
It's just going to open up another security hole as I mentioned and it will get flagged with a CVE for sure. Again, I suggest using fillable and no you don't have to add every key if you just update the property manually instead of mass-assigning it.

```php
$model->attribute = $value;
$model->save();
```

2020-10-05 13:49 UTC, closed without merging