#add ability to replicate eloquent collection
laravel/framework pull request #34864
Opened 2020-10-17 02:48 UTC by ahmedabdel3al

This PR add ability replicate eloquent collection ->replicate() method.

l had situation that i want to replicate excursions with their relations and change a bit in excursion attribute  

**before replicate** 

```
Excursion::with('options','media','activities','cities')
    ->get()
    ->each(function ($excursion) {
        $replicatedExcursion = $excursion->replicate(['title_lowered']);
        $replicatedExcursion->is_active =false ;
        $excursion->save();
        $availableDates =$replicatedExcursion->availableDates->map(function($availableDate){
            return $availableDate->replicate(['is_active']);
        });
        $replicatedExcursion->availableDates()->saveMany($availableDates);
    
    });
```

```
         $availableDates =$replicatedExcursion->availableDates->map(function($availableDate){
            return $availableDate->replicate(['is_active']);
        });
        $replicatedExcursion->availableDates()->saveMany($availableDates);
```

 **After replicate** 
 ```
Excursion::with('options','media','activities','cities')
    ->get()
    ->replicate(['title_lowered'])
    ->each(function ($replicatedExcursion) {
        $replicatedExcursion->is_active =false ;
        $replicatedExcursion->save();
        $replicatedExcursion->availableDates()->saveMany($new_excursion->availableDates->replicate(['is_active']));
       
    });
```
`        $replicatedExcursion->availableDates()->saveMany($new_excursion->availableDates->replicate(['is_active']));
`

   I think writing it this way is **readable** .
 **i using replicate method as  macro**  in my current project .
  thank you

2020-10-17 05:01 UTC, timacdonald commented
@ahmedabdel3al this is probably a great use case for higher order functions. It would be possible to achieve the same thing with...

```php
$excursions->map->replicate(['title_lowered]);
```

2020-10-17 09:42 UTC, ahmedabdel3al commented
@timacdonald  i agree with you , but i think you don't have to know you should  map every times to replicate collection .

`$excursions->replicate(['title_lowered]);
`

2020-10-17 12:13 UTC, GrahamCampbell requested changes

2020-10-17 12:13 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Collection.php
> +     * @param  callable|null  $callback
invalid

2020-10-17 12:13 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Collection.php
> +            return  $model->replicate($except);
too many spaces after `return`

2020-10-17 13:51 UTC, ahmedabdel3al commented on src/Illuminate/Database/Eloquent/Collection.php
> +     * @param  callable|null  $callback
fixed

2020-10-17 13:51 UTC, ahmedabdel3al commented on src/Illuminate/Database/Eloquent/Collection.php
> +            return  $model->replicate($except);
fixed

2020-10-17 16:29 UTC, GrahamCampbell requested changes

2020-10-17 16:29 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Collection.php
> +     *  Replicates every item in the collection .
no space before the period, please

2020-10-17 16:49 UTC, ahmedabdel3al commented on src/Illuminate/Database/Eloquent/Collection.php
> +     *  Replicates every item in the collection .
fixed

2020-10-17 23:44 UTC, timacdonald commented
FYI I’m absolutely not against this idea. I love 1st class collection methods like this. I more meant in the case that it is rejected 👍

2020-10-17 23:46 UTC, timacdonald commented on src/Illuminate/Database/Eloquent/Collection.php
> +        $items = $this->map(function ($model) use ($except) {
Can we just return here? The resulting collection from the `map` should be a new instance of the Eloquent collection (assuming all the returned objects are eloquent collections), so the following `new static` is redundant I believe.

2020-10-19 13:47 UTC, taylorotwell commented
I kind of agree that you should just use higher order methods to do this... $collection->map->replicate

2020-10-19 13:47 UTC, closed without merging