multipleSpaceClean and utrim method was added into Str helper.
laravel/framework pull request #35674
Opened 2020-12-19 22:09 UTC by X-Adam

multipleSpaceClean method was added into Str helper.
The inserted method clears multiple whitespace characters in a string.

Example:
$input = 'a b c d e';
$output = Str:multipleSpaceClean($input);
echo $output; // Result: a b c d e

trim method was added into Str helper.
Trim that additionally removes slashes.

Example:
$input = "\hello world \n";
$output = Str:utrim($input);
echo $output; // Result: hello world

2020-12-19 22:14 UTC, X-Adam commented
I want my contribution, if not accepted, I will publish it as a package :).

Thanks in advance.

2020-12-19 22:28 UTC, GrahamCampbell requested changes

2020-12-19 22:28 UTC, GrahamCampbell commented on tests/Support/SupportStrTest.php
> +        $this->assertSame('a b c d e', Str::multipleSpaceClean('a b  c   d    e'));
And what about unicode whitespace characters (not just unicode non-whitespace)?

2020-12-20 22:28 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2020-12-20 22:28 UTC, closed without merging