Added functionality to check if used states of a factory collide
laravel/framework pull request #35730
Opened 2020-12-27 13:08 UTC by SuperDJ

Added functionality to prevent used states of a factory from colliding. This can be useful for factories with many states and newcomers to the codebase.

https://github.com/laravel/framework/discussions/34494
https://github.com/laravel/ideas/issues/2363

2020-12-27 21:28 UTC, GrahamCampbell requested changes

2020-12-27 21:28 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Factories/Factory.php
> +    private function checkStateCollides($newState): void
Laravel does not use the void return type. Only phpdoc.

2020-12-27 21:28 UTC, GrahamCampbell requested changes

2020-12-27 21:28 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Factories/Factory.php
> +     * @param $newState
invalid syntax

2020-12-28 01:39 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2020-12-28 01:39 UTC, closed without merging