[8.x] Improvements to Str and Stringable
laravel/framework pull request #36248
Opened 2021-02-12 22:39 UTC by thomas-alrek

I find myself using the `Str` class very much, as the various string functions in PHP can be "messy" to use. One thing that I often feel is missing when working with Laravel in my day job, is a consistent wrapper for the `explode` and `implode` methods, that also supports Collections.

This pull request adds two new static methods to `\Illuminate\Support\Str`.

**Str::split**
---
This method provides a proxy for `explode`, returning a `\Illuminate\Support\Collection` of `\Illuminate\Support\Stringable` objectss.

#### Example
```php
<?php

use Illuminate\Support\Str;

$str = 'foo,bar,baz';
$delimiter = ',';

$pieces = Str::split($str, $delimiter); // (Collection) => ['foo', 'bar', 'baz']
```

**Str::join**
---
This method provides a proxy for `implode`, taking an array or a `\Illuminate\Support\Contracts\Arrayable` and joins them back to a `\Illuminate\Support\Stringable` object.

#### Example
```php
<?php

use Illuminate\Support\Str;

$glue = ',';
$pieces = ['foo', 'bar', 'baz'];

$str = Str::join($pieces, $glue); // (Stringable) => 'foo,bar,baz'
```

It also adds a new static constructor method for `\Illuminate\Support\Stringable`

**Stringable::make**
---

#### Example
```php
<?php

use Illuminate\Support\Stringable;

$str = Stringable::make('foo'); // (Stringable) => 'foo'
```

2021-02-13 00:32 UTC, GrahamCampbell requested changes

2021-02-13 00:32 UTC, GrahamCampbell commented on src/Illuminate/Support/Str.php
> +     * @param  int  $limit
`int|null`

2021-02-13 00:32 UTC, GrahamCampbell commented on src/Illuminate/Support/Str.php
> +        $pieces = call_user_func_array('explode', $parameters);
`explode(...array_filter([$delimiter, $string, $limit]))`?

2021-02-13 00:32 UTC, GrahamCampbell commented on src/Illuminate/Support/Stringable.php
> +     *
cs

2021-02-13 05:02 UTC, derekmd commented on src/Illuminate/Support/Str.php
> +            ->map([Stringable::class, 'make']);
This could be replaced with `->mapInto(Stringable::class)` which removes the need to add a `make()` method.

2021-02-13 16:46 UTC, VeryStrongFingers commented on src/Illuminate/Support/Str.php
> +        $pieces = explode(...array_filter([$delimiter, $string, $limit]));
You should allow `$delimiter` to be falsey - might be best to avoid `array_filter()`

2021-02-13 19:11 UTC, taylorotwell commented
Why not just call them explode and implode?

2021-02-13 22:31 UTC, thomas-alrek commented
> Why not just call them explode and implode?

I thought about, but I wanted it to align with the similar methods in the Collection class, and I also find the names explode and implode very "confusing". In most other languages the similar methods are usually named split and join

2021-02-14 16:46 UTC, taylorotwell commented
Hmm, I think I'll just leave things be for now - Stringable already has an explode() and collection already has an implode.

2021-02-14 16:46 UTC, closed without merging