resolves 2548
laravel/framework pull request #36723
Opened 2021-03-23 21:34 UTC by Arkitecht

Resolves issue raised in Issue 2548 to add ability to call assertions on MailFake

2021-03-23 22:34 UTC, ahinkle commented
https://github.com/laravel/framework/pull/35430#issuecomment-740120894

2021-03-23 23:01 UTC, GrahamCampbell requested changes

2021-03-23 23:01 UTC, GrahamCampbell commented on src/Illuminate/Mail/Mailable.php
> +                $mailer = (new MailManager(app()))->mailer();
The app helper cannot be used outside of foundation.

2021-03-24 16:08 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2021-03-24 16:08 UTC, closed without merging