Add phpredis serialization and compression config support
laravel/framework pull request #36791
Opened 2021-03-28 19:28 UTC by TheLevti

This pull request allows the framework user to configure phpredis (https://github.com/phpredis/phpredis) serialization and compression options right in the config instead of the need to overwrite the service provider or a custom driver.

Supported serializers:

- NONE
- PHP
- JSON
- IGBINARY
- MSGPACK

Supported compressors:

- NONE
- LZF
- ZSTD
- LZ4 (added, but does not work until https://github.com/phpredis/phpredis/issues/1939 is resolved, tests need to be uncommented once phpredis adds the necessary adjustments).

I did here similar changes to what https://github.com/laravel/framework/pull/31262 tried to do, just without the for me not yet understandable other adjustments to some of the redis functions. Also added tests for different compression algorithms.

Note: My first attempt was to always serialize + compress the passed arguments to eval, but then later decided to let the user take care of this as we can not know what kind of lua script he wants to execute and whether all arguments are expected to be serialized/compressed. Instead I provided a helper method on the `PhpredisConnection` class that the user may use. In addition I refactored the previous phpredis lock support (https://github.com/laravel/framework/issues/36337) for these functionalities to use this new helper method.

2021-03-28 20:55 UTC, GrahamCampbell requested changes

2021-03-28 20:55 UTC, GrahamCampbell commented on tests/Redis/RedisConnectionTest.php
> +        // TODO: Uncomment after https://github.com/phpredis/phpredis/issues/1939
Marking as draft, due to this blocker.

2021-03-29 08:16 UTC, driesvints commented
Please send this in when the PR is finished and without TODO's. Thanks

2021-03-29 08:16 UTC, closed without merging

2021-03-29 18:21 UTC, TheLevti commented
Thanks, will first try to fix phpredis, if thats not possible short term, I will exclude lz4 support.

2021-11-01 10:50 UTC, TheLevti commented
> @TheLevti any news on this?

I am waiting for phpredis to release 5.3.5

2022-01-02 22:55 UTC, it-can commented
> > @TheLevti any news on this?
> 
> I am waiting for phpredis to release 5.3.5

5.3.5 is released I see https://github.com/phpredis/phpredis/releases/tag/5.3.5

2022-01-05 21:49 UTC, TheLevti commented
> > > @TheLevti any news on this?
> > 
> > 
> > I am waiting for phpredis to release 5.3.5
> 
> @TheLevti 5.3.5 is released I see https://github.com/phpredis/phpredis/releases/tag/5.3.5

Thanks for the update, will re-open my pull request soon.

2022-01-06 22:54 UTC, TheLevti commented
https://github.com/laravel/framework/pull/40282 follow up