[8.x] Laravel Maintenance Mode Cookie doesn't follow the session configurations
laravel/framework pull request #36945
Opened 2021-04-11 15:37 UTC by hicham-saddek

Fixing the Laravel MaintenanceModeBypassCookie.php missing the session information (path, domain, secure), in order to follow the application session config file.

How to reproduce:
 - New laravel installation.
 - Use `.example.com` as `session.domain` (Note: this should affect all the subdomains, in the `example.com` domain name)
 - Or you can use any other setting path, domain or secure setting.
The problem:
 The laravel cookie doesn't contain the session configuration, so when we change the laravel session configuration it is only available in the root domain name, not the subdomains.

2021-04-11 17:14 UTC, GrahamCampbell requested changes

2021-04-11 17:14 UTC, GrahamCampbell commented on src/Illuminate/Foundation/Http/MaintenanceModeBypassCookie.php
> +        ])), $expiresAt, config('session.path'), config('session.domain'), config('session.secure'));
👎 for adhoc config reading

2021-04-11 21:02 UTC, hicham-saddek commented
Does this solve the issue ?

2021-04-11 22:06 UTC, GrahamCampbell requested changes

2021-04-11 22:06 UTC, GrahamCampbell commented on src/Illuminate/Foundation/Http/MaintenanceModeBypassCookie.php
> +        ])), $expiresAt, '/', env('SESSION_DOMAIN', null));
The env helper cannot be used, ever. In production, the env files should not be loaded, in favour of config caching.

2021-04-12 08:02 UTC, hicham-saddek commented
I used the same method you guys have used inside the `VerifyCsrfToken` middleware, in order to add the configurations.

###### Example:
```php
use function config;

$config = config('sessions');

$path = $config['path'] ?? '/';
$domain = $config['domain'] ?? null;
$secure = $config['secure'] ?? null;
// And others, you may see them in the commit
```

2021-04-13 12:50 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2021-04-13 12:50 UTC, closed without merging

2021-04-14 12:41 UTC, hicham-saddek commented
@taylorotwell, actually this is not a feature that i am requesting, it is a solution for a bug that is on the laravel maintenance middleware.

The Laravel maintenance mode prevents requests from being passed into the controllers, etc by catching the cookie `laravel_maintenance`, if this cookie exists it rejects the request of the user as we are in maintenance mode. However this cookie is not set to work with wildcard domains like `{user:username}.example.com`, as it doesn't actually include the session domain configurations in the laravel maintenance cookie. so basicly what i did here is that i added the Laravel session configurations to this cookie so it can work in wildcard domains.

Example:
We Enable maintenance mode !
If a user navigates to `example.com`, what basicly they will see is the maintenance page or the 500 error page, it depends on the application.
BUT if we the user navigates to something else within the application (supposing that we work with a wildcard domain) something like `{username}.example.com` or `profile.example.com` or anything else, they would still login and use the application even tho it is still in the maintenance mode.