Update phpdoc for event listeners
laravel/framework pull request #37118
Opened 2021-04-25 13:40 UTC by emargareten

Update phpdoc for event listeners - adds `\Illuminate\Events\QueuedClosure` (https://laravel.com/docs/8.x/events#queuable-anonymous-event-listeners)

2021-04-26 08:57 UTC, GrahamCampbell requested changes

2021-04-26 08:57 UTC, GrahamCampbell commented on src/Illuminate/Contracts/Events/Dispatcher.php
> +     * @param  \Closure|\Illuminate\Events\QueuedClosure|string|array  $events
This cannot go in the contract, because the contracts repo cannot know about the events concetions.

2021-04-26 08:58 UTC, GrahamCampbell commented on src/Illuminate/Contracts/Events/Dispatcher.php
> +     * @param  \Closure|\Illuminate\Events\QueuedClosure|string|array  $events
We probably need a contract for this class, to allow us to reference it here, and in all phpdoc in this PR.

2021-04-26 09:33 UTC, driesvints commented
I agree with @GrahamCampbell. I don't think we should typehint these all over the codebase? Although I do see your point and unsure how we'd need to do this differently 🤔

2021-04-27 13:22 UTC, taylorotwell commented
Closing pending resolution of comments above.

2021-04-27 13:22 UTC, closed without merging