[8.x] Adds `whereRelationKey()` and `whereRelationKeyNot()`
laravel/framework pull request #37130
Opened 2021-04-26 20:27 UTC by DarkGhostHunter

This PR allows adds `whereRelationKey()` and `whereRelationKeyNot()` methods to the Builder for relationships.

It allows to quickly add a `whereKey()` and `whereKeyNot()` to the related model query, quickly.

## Problem

Let's say we have a `Passenger` model that has many `Tickets`. Each of the `Ticket` belongs to the `Passenger` but also an `Airline`.

We want to filter the tickets by their `Airline` they belong. To do it, we can use the query builder via the relationship method.

```php
$passenger->tickets()->whereHas('airline', function (Builder $query) use ($airline) {
    $query->where('id', $airline->id);
})->get();
```

While that sounds like not too much work, adding more relationships filters can quickly become an endless lines of anonymous functions calls. For example, if we also need to filter them by departure and destination `Airport`.

```php
$passenger->tickets()->whereHas('airline', function (Builder $query) use ($airline) {
    $query->where('id', $airline->id);
})->whereHas('departure', function (Builder $query) use ($departureAirport) {
    $query->where('id', $departureAirport->id);
})->whereHas('destination', function (Builder $query) use ($destinationAirport) {
    $query->where('id', $destinationAirport->id);
})->get();
```

## Solution

The `whereRelationKey()`  uses the power of `whereKey()` underneath to make the code above just a method call away.

```php
$passenger->tickets()->whereRelationKey('airline', $airline)->get();
```

Behind the scenes, if it's a model, it will extract the key from it so there is no need to do it manually with `$airline->id` or `$airline->getKey()`.

It also accepts multiple relations when issuing an array. In this case, we want all the tickets for a given airline, a given departure `Airport`, and destination `Airport`.

```php
$passenger->tickets()->whereRelationKey([
    'airline' => $airline,
    'departure' => $departureAirport
    'destination' => $destinationAirport,
])->get();
```

## Details

- Non breaking changes.
- It adds `whereRelationKey()` and `whereRelationKeyNot()` to the `QueriesRelationships` trait.
- adds a small helper to parse the relations if it's an `array` and the `id` its a `Model` instance.
- Test included
- Works for any relationship as long it has a primary key declared, otherwise `whereHas()` should be used.

2021-04-26 20:30 UTC, DarkGhostHunter commented
Test failed because [docker decided to go awol](https://github.com/laravel/framework/pull/37130/checks?check_run_id=2442131018#step:2:112). Can someone make a rerun?

2021-04-26 20:41 UTC, DarkGhostHunter commented
Ok, that's all folks. I hope you like it.

2021-04-27 07:47 UTC, driesvints requested changes

2021-04-27 07:47 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php
> +     * @param  $id
Types are missing from these params.

2021-04-27 07:47 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php
> +     * @param  mixed|null $id
Mixed already contains `null`.

```suggestion
     * @param  mixed  $id
```

2021-04-27 17:25 UTC, DarkGhostHunter commented
One of the things I'm not very fond of is using `whereKey()` and `whereKeyNot()` when you're issuing a Model. So I refactored the code to always get the model key.

The thing is, both of these methods have a check for `Arrayable` items. If you issue a `Model`, the model properties will be transformed to an `array`, instead of smartly getting the primary key. I could make a PR for that QoL.

2021-04-27 18:52 UTC, driesvints commented
@DarkGhostHunter Taylor will review this once he gets to it. Thanks

2021-04-27 18:56 UTC, DarkGhostHunter commented
OK. If this goes through, I'll ask if I can make both changes in one PR. 

I already checked and adding a Model check to the 'whereKey()' and 'whereKeyNot' doesn't break any test. The only think that I I would break would be the skulls of developers issuing models in these methods.

2021-04-29 18:27 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2021-04-29 18:27 UTC, closed without merging

2021-04-29 21:01 UTC, DarkGhostHunter commented
If it's gonna be delayed, can I re-issue this for 9.x then?

2021-04-29 21:28 UTC, driesvints commented
@DarkGhostHunter i don't think Taylor wants to add this atm.