[8.x] PHP 8.1 fixes
laravel/framework pull request #38404
Opened 2021-08-16 15:29 UTC by driesvints

This PR adds some additional fixes for PHP 8.1:

- More `ReturnTypeWillChange` attributes for the `SessionHandlerInterface` usages
- Bump CommonMark to prevent future failures when using `--prefer-lowest` buildswq

2021-08-16 15:40 UTC, GrahamCampbell commented
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/2829600/129590597-8b7f2b9e-840b-41c2-a198-0c8a00d64ee5.png">

2021-09-02 09:55 UTC, GrahamCampbell requested changes

2021-09-02 09:55 UTC, GrahamCampbell commented on composer.json
> +        "mockery/mockery": "1.4.x-dev",
^1.4.3

2021-09-02 09:57 UTC, driesvints commented on composer.json
> +        "mockery/mockery": "1.4.x-dev",
Great call!

2021-09-05 22:48 UTC, kylekatarnls approved these changes

2021-09-06 08:37 UTC, GrahamCampbell commented
@kylekatarnls  why have you approved a PR in a broken state?

2021-09-06 09:05 UTC, kylekatarnls commented
I would like to see `ReturnTypeWillChange` merged which should unlock the composer install for Laravel. And I think we could have 1 other PR first to add all the `#[ReturnTypeWillChange]` then the rest in a second step with conflicts fixed when ready.

2021-09-06 11:56 UTC, GrahamCampbell commented
It’s not ready yet. It’ll probably be another few weeks, at the earliest. Even if the framework code is ready, it’s dependencies are not all ready, which means it still won’t work in practice.

2021-09-06 12:45 UTC, kylekatarnls commented
I know, I just released a new fix today for Carbon compatibility with PHP 8.1 interfaces that added new return types.

2021-09-07 09:58 UTC, driesvints commented
> I would like to see ReturnTypeWillChange merged which should unlock the composer install for Laravel

I can install Laravel v9 just fine right now. Is there anything custom you're doing maybe that's preventing you to do that?

2021-09-07 15:52 UTC, GrahamCampbell commented
> Check into PDO::ATTR_STRINGIFY_FETCHES behavio

I think this is covered now. :)

2021-09-15 13:47 UTC, GrahamCampbell approved these changes

2021-09-15 14:24 UTC, nunomaduro commented
@taylorotwell I've skipped the tests that are currently failing in PHP 8.1, so we can make this pull request in a mergeble state.

2021-09-15 14:32 UTC, merged