Add nested relationships to whereRelation function
laravel/framework pull request #39064
Opened 2021-10-02 23:55 UTC by josemariagomez

This PR added the possibility to use nested relationships when using 'whereRelation' Eloquent's function, using dot notation.
Also still works with not nested relationships, so it's not a breaking change.

## How it works
```php
// Before
Company::whereHas('teams', function($query) {
  $query->whereHas('users', function($query) {
      $query->whereHas('roles', function($query) {
          $query->where('name', 'admin');
      });
  });
})->get();

// After 💅🏻
Company::whereRelation('teams.users.roles', 'name', 'admin')->get();

// Also can be used as orWhereRelation
Company::where('public', true)->orWhereRelation('teams.users', 'id', auth()->id())->get();

// Still can use this function for not nested relationships
Company::whereRelation('teams', 'id', '1')->get();
```

2021-10-04 08:20 UTC, driesvints requested changes

2021-10-04 08:20 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php
> +     * Relationship can be nested using dot notation.
Remove this second line again.

2021-10-04 08:20 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php
> +     * Relationship can be nested using dot notation.
Remove this second line again.

2021-10-04 08:20 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php
> +        return $this->when(
```suggestion
        $relations = collect(explode('.', $relation));

        return $this->when(
```

2021-10-04 08:20 UTC, driesvints commented on src/Illuminate/Database/Eloquent/Concerns/QueriesRelationships.php
> +        return $this->when(
```suggestion
        $relations = collect(explode('.', $relation));

        return $this->when(
```

2021-10-06 16:09 UTC, merged

2021-10-07 06:55 UTC, devfrey commented
Why was this merged?

1) It was already possible to used nested relations before these code changes.
2) This PR contains no tests...