[8.x] Subset in request's collect
laravel/framework pull request #39191
Opened 2021-10-13 23:18 UTC by iraldoad

This adds the ability to get a subset in request collect function.

Before
--

```php
    public function collect($key = null)
    {
        return collect($this->input($key));
    }
```

After
--
```php
    public function collect($key = null)
    {
        if (is_array($key))
            return collect($this->only($key));
        else
            return collect($this->input($key));
    }
```

fix https://github.com/laravel/framework/issues/39190

2021-10-13 23:40 UTC, GrahamCampbell requested changes
Thanks for the PR. Left a comment.

2021-10-14 03:24 UTC, BrandonSurowiec commented
It would be a good idea to add some test coverage. You can see the previous commit that added this message to give you an idea of where to add the test: https://github.com/iraldoad/framework/commit/4cb7660dc25b4a09ce2cdfff0d4195d1b4a48c70#diff-50be1df2e396478cd5abf036e618ba2a6c09c5dfcb6429d172faea92dae1c904

You could make this method a one-liner:

```php
    public function collect($key = null)
    {
        return collect(is_array($key) ? $this->only($key) : $this->input($key));
    }
```

2021-10-14 13:12 UTC, taylorotwell commented
Draft pending test coverage.

2021-10-15 14:57 UTC, merged

2021-10-15 17:04 UTC, BrandonSurowiec commented
@iraldoad Great improvement, congrats on the merge! 🥳

2021-10-16 20:34 UTC, iraldoad commented
> @iraldoad Great improvement, congrats on the merge! 🥳

Thank you very much for the suggestions and reviews. Happy to contribute to this great project.