[8.x] Add support for countables to the pluralizer
laravel/framework pull request #39641
Opened 2021-11-17 00:10 UTC by michaeldyrynda

This PR adds support for countable values to the `Str::plural` method.

In doing so, you will be able to pass anything that passes PHP's `is_countable` check i.e. arrays, objects that implement `Countable` as the second parameter of the `plural` method.

This is useful when you want to pluralize a string based on a collection returned directly from an Eloquent query or otherwise filtered collection.

2021-11-17 08:29 UTC, driesvints approved these changes

2021-11-17 11:12 UTC, nunomaduro requested changes
The pull request looks good to me. Left some feedback regarding the PHP annotations.

2021-11-17 11:12 UTC, nunomaduro commented on src/Illuminate/Support/Pluralizer.php
> +     * @param  int|array|Countable  $count
```suggestion
     * @param  int|array|\Countable  $count
```

2021-11-17 11:12 UTC, nunomaduro commented on src/Illuminate/Support/Str.php
> +     * @param  int|array|Countable  $count
```suggestion
     * @param  int|array|\Countable  $count
```

2021-11-17 11:23 UTC, nunomaduro approved these changes

2021-11-17 14:34 UTC, merged

2021-11-22 22:54 UTC, squatto commented
I'm happy to see this make it's way into the framework, it's been needed for a while. I tried adding the same thing but it was declined for some reason: https://github.com/laravel/framework/pull/34758