[9.x] Improve Collection's callable default return types
laravel/framework pull request #39805
Opened 2021-11-28 20:56 UTC by MatanYadaev

Currently, Collection methods that have a default parameter return incorrect type when the default parameter value is a closure.

The methods are:
* `Collection::first`
* `Collection::last`
* `Collection::get`
* `Collection::pull`
* `LazyCollection::first`
* `LazyCollection::last`
* `LazyCollection::get`

Code example:

```php
$users = User::get();

// `$user1` is `User|null`
$user1 = $user->get(key: 0);

// `$user2` is `User` - because of the default parameter)
$user2 = $user->get(key: 0, default: new User());

// `$user3` is `User|(Closure(): User)` - the default type isn't correct
$user3 = $user->get(key: 0, default: function () {
  return new User();
});
```

After this PR:

```php
// `$user4` is `User`
$user4 = $user->get(key: 0, default: function () {
  return new User();
});
```

2021-11-28 21:36 UTC, nunomaduro requested changes
Thank you for this pull request. Feedback that must be addressed before merging:

- Please replace `callable` by `\Closure`.
- Please adjust the types on the interface `Illuminate\Support\Enumerable'.

2021-11-28 21:36 UTC, nunomaduro commented on src/Illuminate/Collections/Collection.php
> +     * @param  TFirstDefault|(callable(): TFirstDefault)  $default
This should be a `Closure`, and not a callable.

2021-11-28 21:36 UTC, nunomaduro commented on src/Illuminate/Collections/Collection.php
> +     * @param  TGetDefault|(callable(): TGetDefault)  $default
This should be a Closure, and not a callable.

2021-11-28 21:36 UTC, nunomaduro commented on src/Illuminate/Collections/Collection.php
> +     * @param  TPullDefault|(callable(): TPullDefault)  $default
This should be a Closure, and not a callable.

2021-11-28 21:36 UTC, nunomaduro commented on src/Illuminate/Collections/Collection.php
> +     * @param  TLastDefault|(callable(): TLastDefault)  $default
This should be a Closure, and not a callable.

2021-11-28 21:36 UTC, nunomaduro commented on src/Illuminate/Collections/LazyCollection.php
> +     * @param  TFirstDefault|(callable(): TFirstDefault)  $default
This should be a Closure, and not a callable.

2021-11-28 21:36 UTC, nunomaduro commented on src/Illuminate/Collections/LazyCollection.php
> +     * @param  TGetDefault|(callable(): TGetDefault)  $default
This should be a Closure, and not a callable.

2021-11-28 21:36 UTC, nunomaduro commented on src/Illuminate/Collections/LazyCollection.php
> +     * @param  TLastDefault|(callable(): TLastDefault)  $default
This should be a Closure, and not a callable.

2021-11-28 21:49 UTC, MatanYadaev commented
@nunomaduro Thanks for the review. Done.

2021-11-28 21:54 UTC, nunomaduro approved these changes

2021-11-29 13:21 UTC, driesvints commented
Hi there, we've temporarily disabled our PostgreSQL build until we've managed to fix it. I've marked your PR as draft for now. Please rebase with master and mark this PR as ready when all tests pass again. Thanks.

2021-11-29 14:42 UTC, merged

2021-11-29 14:48 UTC, driesvints commented
@MatanYadaev you incorrectly rebased this PR, causing some commits to duplicate. Luckily this PR was squash-merged. Please be mindful when rebasing PR's to avoid this as this can cause real-havoc on projects.