[8.x] Add parent model key when upserting has many relations
laravel/framework pull request #40057
Opened 2021-12-15 15:06 UTC by mateusjunges

This is an attempt to fix #40049. However, i don't exactly know how to test this. @paras-malhotra as you are the one who introduced `upsert`, i'd appreciate your help.

2021-12-15 15:13 UTC, mateusjunges commented
Can someone restart the jobs please?
![image](https://user-images.githubusercontent.com/19756164/146212495-0eb90c27-ba7f-4244-8d9d-5311ebfcfcfb.png)

2021-12-15 17:04 UTC, Neol3108 commented on tests/Database/DatabaseEloquentHasManyTest.php
> +    public function testUpsertMethodCorrectlySetsParentModeley()
```suggestion
    public function testUpsertMethodCorrectlySetsParentModelKey()
```

2021-12-15 17:07 UTC, taylorotwell commented
Marking as draft until reviewed by @paras-malhotra  and has tests.

2021-12-15 17:07 UTC, taylorotwell commented
I'm honestly not sure support for relationship upserting has even been considered yet.

2021-12-15 21:38 UTC, GrahamCampbell requested changes

2021-12-15 21:38 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/HasMany.php
> +     * @param $uniqueBy
invalid syntax

2021-12-15 21:38 UTC, GrahamCampbell commented on src/Illuminate/Database/Eloquent/Relations/HasMany.php
> +     * @param $update
same

2021-12-15 22:07 UTC, mateusjunges commented on src/Illuminate/Database/Eloquent/Relations/HasMany.php
> +     * @param $update
@GrahamCampbell fixed, thanks!

2022-01-03 16:10 UTC, driesvints commented
Is this PR still being worked on? Otherwise it's best to close this and send it in at a later time.

2022-01-03 16:19 UTC, mateusjunges commented
@driesvints i think taylor wants a review from @paras-malhotra. For me you guys can already review it.

2022-01-07 16:14 UTC, taylorotwell commented
I basically know for certain `upsert` was never intended to be used via relationships. Only for upserting directly on an Eloquent model. 

If you are wanting to add it here, what about the other relationship types? Would those need support?

2022-01-12 03:19 UTC, taylorotwell commented
Closing pending inactivity.

2022-01-12 03:19 UTC, closed without merging

2022-02-10 11:02 UTC, kasus commented
Here is how I figured this:
```php
HasMany::macro('upsertRelated', function (array $values, $uniqueBy, $update = null) {
      data_set($values, '*.' . $this->getForeignKeyName(), $this->getParentKey());
      return $this->related->upsert($values, $uniqueBy, $update);
});
```

not proud of my english but I just wanted to prevent overriding of the QueryBuilder `upsert` function.

Also using the similar for BelongsToMany relation:
```php
BelongsToMany::macro('upsertPivot', function (array $values, $uniqueBy, $update = null) {
      data_set($values, '*.' . $this->getForeignPivotKeyName(), $this->getParent()->getKey());
      return $this->newPivotQuery()->upsert($values, $uniqueBy, $update);
});
```
I needed it mostly because `sync()` function on belongsToMany relation is not very effective with lots of pivot records and it also can't do increments and stuff like this:
```php
$user->recipes()->upsertPivot($recipes, ['recipe_id', 'user_id'], ['servings' => DB::raw('servings + values(`servings`)')]);
```

I can make a PR to core if it makes sense for framework.

2023-10-06 06:55 UTC, khsuzan commented
> Here is how I figured this:
> 
> ```
> HasMany::macro('upsertRelated', function (array $values, $uniqueBy, $update = null) {
>       data_set($values, '*.' . $this->getForeignKeyName(), $this->getParentKey());
>       return $this->related->upsert($values, $uniqueBy, $update);
> });
> ```
> 
> not proud of my english but I just wanted to prevent overriding of the QueryBuilder `upsert` function.
> 
> Also using the similar for BelongsToMany relation:
> 
> ```
> BelongsToMany::macro('upsertPivot', function (array $values, $uniqueBy, $update = null) {
>       data_set($values, '*.' . $this->getForeignPivotKeyName(), $this->getParent()->getKey());
>       return $this->newPivotQuery()->upsert($values, $uniqueBy, $update);
> });
> ```
> 
> I needed it mostly because `sync()` function on belongsToMany relation is not very effective with lots of pivot records and it also can't do increments and stuff like this:
> 
> ```
> $user->recipes()->upsertPivot($recipes, ['recipe_id', 'user_id'], ['servings' => DB::raw('servings + values(`servings`)')]);
> ```
> 
> I can make a PR to core if it makes sense for framework.

You made my day. Thanks