Add ability to supply request methods with `Arrayable` instances
laravel/framework pull request #40190
Opened 2021-12-28 21:04 UTC by stevebauman

## Problem

Currently we cannot supply `Arrayable` instances into any of the `HTTP` methods, as Guzzle will throw an exception, saying that HTTP options must be an array or string.

## Description

This PR introduces the ability to supply `Arrayable` instances into the Laravel HTTP Client for more convenient use.

This is done by simply leveraging `collect($options)->toArray()` to transform all HTTP options that are `Arrayable` to their raw array format, prior to sending them along to Guzzle.

## Usage

Using a collection for query parameters:

```php
use Illuminate\Support\Facades\Http;

$search = collect(['brand' => 'Samsung', 'color' => 'Black']);

Http::get('/products', $search);
```

Using a fluent instance for form data:

```php
use Illuminate\Support\Facades\Http;

$user = new Fluent();

$user->name = 'Steve Bauman';
$user->email = 'steve@email.com';

//...

Http::post('/users', $user);
```

The above use-cases would be more useful when their `Fluent` or `Collection` instances coming from other sources in your application, so you don't have to transform them every time you want to send a request.

## Important

I wasn't sure if I should change the `array` doc block types to `mixed`, or simply add `Arrayable` as an allowed type.

Let me know what you'd like, thanks!

---

Thanks for your time :heart:. No hard feelings on closure.

2021-12-30 20:56 UTC, taylorotwell commented
Is changing this signature a breaking change?

2021-12-30 21:10 UTC, stevebauman commented
Dang, yes it is a breaking change. PHP will throw an incompatibility exception. I don't think there's any way around it, even if we update the type to `mixed`, it still will throw an exception with someone having the `array` type declared on their extended version.

I can move this to the 9.x branch if you'd like?

2021-12-31 11:39 UTC, GrahamCampbell requested changes

2021-12-31 11:39 UTC, GrahamCampbell commented on src/Illuminate/Http/Client/PendingRequest.php
> +    public function post(string $url, $data = [])
breaking change

2021-12-31 12:49 UTC, taylorotwell commented
Yeah if we make such a change it would have to go to master I guess.

2021-12-31 12:49 UTC, closed without merging