[9.x] Fix unknown store error
laravel/framework pull request #40981
Opened 2022-02-12 19:05 UTC by imanghafoori1

Currently, when an undefined store is requested it shows in a technical error like below:
And seemingly it was intended to throw an exception for any unknown store.
It adds tests to cover "unknown driver" and  "unknown store" behaviors.

![image](https://user-images.githubusercontent.com/6961695/153724634-0a1d50da-d6a9-482b-a915-d042118fa721.png)

2022-02-12 19:09 UTC, GrahamCampbell requested changes

2022-02-12 19:25 UTC, imanghafoori1 commented on src/Illuminate/Cache/CacheManager.php
> +            return $this->app['config']["cache.stores.{$name}"] ?? null;
But the result is checked against null.
plus the read value can be anything since it is set by the user.

2022-02-12 19:27 UTC, imanghafoori1 commented on src/Illuminate/Cache/CacheManager.php
> +            return $this->app['config']["cache.stores.{$name}"] ?? null;
![image](https://user-images.githubusercontent.com/6961695/153725473-47c8303a-01b5-4d8a-85ac-2cd938920da9.png)

2022-02-12 19:29 UTC, imanghafoori1 commented on src/Illuminate/Cache/CacheManager.php
> +            return $this->app['config']["cache.stores.{$name}"] ?? null;
![image](https://user-images.githubusercontent.com/6961695/153725539-53a6e001-be7b-4b73-bc2c-9d5a8916b68a.png)

2022-02-13 17:57 UTC, imanghafoori1 commented
tests are failing for random reasons.

2022-02-14 08:26 UTC, driesvints commented
Hi, I've fixed the tests on 9.x so please rebase your PR and mark your PR as ready when tests pass. Thanks

2022-02-14 17:27 UTC, merged