[9.x] Add `mergeUnshift` helper to `Collection`
laravel/framework pull request #41507
Opened 2022-03-16 06:08 UTC by chu121su12

Add `mergeUnshift` merge passed parameter to existing collection, as opposite to `merge`. Currently there's `prepend` that prepend only a single value.

2022-03-16 11:29 UTC, nunomaduro requested changes

2022-03-16 11:29 UTC, nunomaduro commented on src/Illuminate/Collections/Collection.php
> +    public function mergeUnshift($items)
Can you add tests to types here?

https://github.com/laravel/framework/blob/9.x/types/Support/Collection.php

2022-03-16 11:29 UTC, nunomaduro commented on src/Illuminate/Collections/LazyCollection.php
> +    public function mergeUnshift($items)
Can you add tests to types here?

https://github.com/laravel/framework/blob/9.x/types/Support/LazyCollection.php

2022-03-19 22:09 UTC, taylorotwell commented
collect($newCollection)->merge($otherCollection);

2022-03-19 22:09 UTC, closed without merging