add getAllTables support for SQLite and SQLServer schema builders
laravel/framework pull request #41896
Opened 2022-04-09 08:48 UTC by Sourcefli

This PR adds support for calling `\Illuminate\Support\Facades\Schema::getAllTables()` on SQLite and SQLServer connections.

I'm returning the `name` and `type` columns to maintain consistency with what's already being returned when using the MySQL or Postgres connections.

P.S. 
This being my 1st Laravel contribution, please go easy on me if I've done something incorrectly here. 😉

2022-04-09 18:23 UTC, GrahamCampbell requested changes

2022-04-09 18:23 UTC, GrahamCampbell commented on phpunit.xml.dist
> +</phpunit>
revert

2022-04-09 18:23 UTC, GrahamCampbell commented on src/Illuminate/Database/Schema/Grammars/SQLiteGrammar.php
> +}
revert

2022-04-09 18:23 UTC, GrahamCampbell commented on src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php
> +}
revert

2022-04-09 18:23 UTC, GrahamCampbell commented on src/Illuminate/Database/Schema/SQLiteBuilder.php
> +}
revert

2022-04-09 18:23 UTC, GrahamCampbell commented on src/Illuminate/Database/Schema/SqlServerBuilder.php
> +}
revert

2022-04-09 18:23 UTC, GrahamCampbell commented on tests/Integration/Database/MySql/DatabaseMySqlSchemaBuilderAlterTableWithEnumTest.php
> +}
revert

2022-04-09 18:23 UTC, GrahamCampbell commented on tests/Integration/Database/SqlServer/DatabaseSqlServerSchemaBuilderTest.php
> +}
missing newline at eof

2022-04-09 18:23 UTC, GrahamCampbell commented on tests/Integration/Database/Sqlite/DatabaseSqliteSchemaBuilderTest.php
> +}
missing newline at eof

2022-04-09 21:46 UTC, Sourcefli commented
eof lines have been fixed. Apologies.

2022-04-12 19:53 UTC, merged

2022-04-13 13:53 UTC, taylorotwell commented
@Sourcefli 

Please fix this failing test and explain why it is failing: https://github.com/laravel/framework/runs/6003485596?check_suite_focus=true

Will give it about 24 - 48 hours to be fixed before I revert this PR. Thanks.

2022-04-13 14:27 UTC, Sourcefli commented
No problem, thanks @taylorotwell.

Strange that in the test theres a count of 7 though, being that only up to 3 tables - each with no more than 3 columns in their schema - is being used within each test... and these tests were passing when run by themselves or within their respective file's tests. My suspicion is that there's leftover tables from previous tests that ran. 
Will fix this shortly.

2022-04-14 07:53 UTC, driesvints commented
We need to revert this asap if we can't find a solution now. Every single PR to 9.x is currently failing because of this.

2022-04-14 15:37 UTC, Sourcefli commented
I found that the `DB_CONNECTION` is still `testing` when running the tests using this command:
`vendor/bin/phpunit tests/Integration/Database --verbose --exclude-group SkipMSSQL`

I was using the phpunit.xml.dist file to run these tests locally, yet came to realize that this file was ignored when running the tests using the command above. 

I have updated the `DatabaseSqlServerSchemaBuilderTest::getEnvironmentSetUp()` to use the sqlsrv connection.

2022-04-14 16:42 UTC, driesvints commented
@Sourcefli can you PR?

2022-04-15 02:37 UTC, Sourcefli commented
Ok, I've got up the fix to this PR, #41984.

I was keep pushing up changes because I had had passing tests locally, so I could only see if/when it failed after I'd made some edits then pushed again. 

Curious to know how you guys typically go about setting up multiple db connection envs when working with this test suite. I ended up jumping into the vendor folder for orchestra and updating the config/database file.

Thanks for your assistance guys 👍