[9.x] Allow jsonSerialize() to return other types
laravel/framework pull request #42133
Opened 2022-04-26 01:31 UTC by mikewudev

This PR updates `jsonSerialize()`'s return type to `mixed`, matching PHP's definition. 

## Use case

Allows models to override `jsonSerialize`, and serialize into strings rather than always having to be an JSON object.

## Example

We have a simple model, `Permission`, who's only attribute is `name`:

```php
class Permission extends Model
{
    protected $fillable = [
        'name',
    ];
}
```

When we fetch all permissions, the collection is automatically serialized into JSON objects.

### Controller

```php
class PermissionsController
{
  public function list()
  {
     return Permission::all();
  }
}
```

Would currently return

```
[
  {name: "foo"},
  {name: "bar"},
  {name: "baz"},
]
```

With this change, `Permission`, can override `jsonSerialize`, and return a `string`. 

Updated response after this PR:

```
["foo", "bar", "baz"]
```

2022-04-26 08:41 UTC, driesvints commented
Ping @X-Coder264 this is what I meant on that pr your sent in ^

2022-04-26 17:03 UTC, GrahamCampbell requested changes
This change looks wrong to me. Having an implementation return a more specific type than that required by the interface is totally OK, and actually desirable in this case. https://3v4l.org/CYkJl

2022-04-26 17:27 UTC, mike3u commented
Updated it to be a union type with `string` instead. `JsonSerializable` only specifies that the return type has to be compatible with `json_encode`, which a `string` is.

2022-04-26 20:29 UTC, dennisprudlo commented
With `array|string` it won't be possible to override `jsonSerialize` and return an integer, a float or a boolean, right? `json_encode`'s $value can have any type but a resource.

2022-04-26 21:38 UTC, driesvints commented
@X-Coder264 my ping was more about you being okay with this change?

2022-04-26 21:46 UTC, X-Coder264 commented
@driesvints There's nothing intrinsically wrong with this change. From my perspective it's a bit weird for a collection (which is just arrays on steroids) to be JSON serialized as anything else but an array. But if people want to do that I guess there's no reason from a framework perspective to block that so on that level I'm fine with the proposed change.

2022-04-27 02:02 UTC, mike3u commented
@X-Coder264 

> it's a bit weird for a collection (which is just arrays on steroids) to be JSON serialized as anything else but an array.

It's actually the Collection item's `jsonSerialize` that I'm hoping to override. The collection can (and should?) still expect an array to be returned.

I've updated it to still return an `array` for collection in: https://github.com/laravel/framework/pull/42133/commits

2022-04-27 08:04 UTC, driesvints commented
If we do this then I suggest we move to the mixed return type like the PHP interface and not bother with union types.

2022-04-27 08:28 UTC, driesvints approved these changes

2022-04-27 13:13 UTC, merged