adding support for multiple hash algorithms
laravel/framework pull request #43378
Opened 2022-07-22 21:05 UTC by medeirosinacio

Hello.

Is this modification valid?
We often need the `sha256` of the file, it would be interesting for `Filesystem` to get it.
If it is already valid, I can include it in the tests.

2022-07-22 21:56 UTC, GrahamCampbell requested changes

2022-07-22 21:56 UTC, GrahamCampbell commented on src/Illuminate/Filesystem/Filesystem.php
> +    public function hash($path, $algorithm = 'md5')
you need to add param doc for this

2022-07-22 23:56 UTC, medeirosinacio commented on src/Illuminate/Filesystem/Filesystem.php
> +    public function hash($path, $algorithm = 'md5')
right

2022-07-23 08:09 UTC, dinhquochan commented
It's compatible for 9.x

2022-07-23 21:45 UTC, medeirosinacio commented
Should I do PR for laravel 9?

2022-07-24 00:02 UTC, taylorotwell commented
Sure

2022-07-24 00:02 UTC, closed without merging