Fix/db commands
laravel/framework pull request #43635
Opened 2022-08-10 08:38 UTC by joedixon

2022-08-10 08:52 UTC, mziraki commented
@jbrooksuk @joedixon
model:show command needs this mapping too

2022-08-10 09:06 UTC, jbrooksuk approved these changes

2022-08-10 09:36 UTC, Sergiobop commented on src/Illuminate/Database/Console/DatabaseInspectionCommand.php
> +    protected function regsisterTypeMapping(AbstractPlatform $platform)
Is this a typo? regsister

2022-08-10 09:38 UTC, nunomaduro requested changes

2022-08-10 09:38 UTC, nunomaduro commented on src/Illuminate/Database/Console/DatabaseInspectionCommand.php
> +    protected function regsisterTypeMapping(AbstractPlatform $platform)
Typo here.

2022-08-10 09:38 UTC, nunomaduro commented on src/Illuminate/Database/Console/DatabaseInspectionCommand.php
> +     * @param  string  $database
This argument is not needed.

2022-08-10 09:45 UTC, joedixon commented on src/Illuminate/Database/Console/DatabaseInspectionCommand.php
> +    protected function regsisterTypeMapping(AbstractPlatform $platform)
Thank you!

2022-08-10 20:54 UTC, lupinitylabs commented
Thanks for addressing this @joedixon ! I opened a PR at #43645 for the same issue, so I guess it can be closed.

There are two things to consider concerning your implementation:

1. the issue with `enum` types only seems to exist on MySQL databases, so we probably might want register the type mapping only on MySQL platforms.
2. the issue also exists for `point` types, so a mapping for these should probably also be added.

2022-08-11 11:25 UTC, joedixon commented
Hey @lupinitylabs - thanks for bringing the additional missing mapping to my attention. I've gone ahead and added some more that we were missing support for.

I'm not sure it's worth conditionally checking the database type as if it's only an issue with, for instance, MySQL, the other database types won't be impacted anyway.

2022-08-11 14:42 UTC, lupinitylabs commented
Yes, I guess since we are just reading the structure anyways, just mapping it all to string might be fine.

2022-08-11 17:01 UTC, merged