Refactor validation closures  to arrow functions
laravel/framework pull request #44194
Opened 2022-09-18 12:22 UTC by Nothehi

Refactor `Validation` closures to arrow functions

2022-09-18 14:21 UTC, henzeb commented
Why?

2022-09-18 15:30 UTC, Nothehi commented
From PHP 7.4, We can make closure functions with the fat arrow which is now more readable, shorter, and cleaner. I thought it would be a good idea to convert these closures to arrow functions.

2022-09-19 07:18 UTC, driesvints requested changes

2022-09-19 07:18 UTC, driesvints commented on src/Illuminate/Validation/Rules/DatabaseRule.php
> +            );
```suggestion
            return implode('.', array_map(
                fn (string $part) => trim($part, '.'),
                array_filter([$model->getConnectionName(), $model->getTable()])
            ));
```

2022-09-19 14:32 UTC, taylorotwell commented
It's OK.

2022-09-19 14:32 UTC, closed without merging