Throw timeoutException instead of maxAttemptsExceededException when a job times out
laravel/framework pull request #46968
Opened 2023-05-05 11:02 UTC by PrinsFrank

Currently, both a job times out and when the max attempts are exceeded for a job the maxAttemptsExceeded exception is thrown. This maxes debugging job timeouts difficult. This PR adds a new exception that is thrown when the SIGALRM signal is fired.

2023-05-05 14:05 UTC, GrahamCampbell requested changes

2023-05-05 14:05 UTC, GrahamCampbell commented on src/Illuminate/Queue/TimeoutExceededException.php
> +class TimeoutExceededException extends RuntimeException
This could be sent to 10.x if you extended MaxAttemptsExceededException instead of RuntimeException.

2023-05-08 15:31 UTC, merged

2023-05-12 08:51 UTC, driesvints commented
@SlyDave how did this break your app?

2023-05-12 09:05 UTC, driesvints commented
I still don't understand how this breaks your app?

2023-05-15 09:48 UTC, SlyDave commented
It doesn't, as I noted, because of the TimeoutExceededException extending the MaxAttemptsExceeededException.

I incorrectly made the assumption that a new Exception was being added, that would be a breaking change, instead one was added that extends the existing one, which does stop the breaking change from occurring, but is really weird as it's utterly unrelated, and just serves to cause confusion in future. 

If one captures only MaxAttemptsExceeededException, it will capture TimeoutExceededException as well, which is _current_ behaviour but I would argue is unintended behaviour that shouldn't be preserved.