[11.x] Omit `render()` method in Blade components
laravel/framework pull request #47379
Opened 2023-06-08 16:00 UTC by ahinkle

Currently, the `render()` method is required on a blade component. ~95% of the time, I never change the `render()` method view on a rendered blade view component. In Livewire, you can omit the `render()` method, and this PR accomplishes the same action.

This will automatically attempt to resolve a view located at `components.x` and also works on nested components. Users may continue to write their own `render()` methods for complex customization.

I don't believe this is a breaking change - but I went ahead and targeted `11.x` in case developers overwrote any customization on render in the core component class.

Before:
```php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Alert extends Component
{
    public function render()
    {
        return view('components.alert');
    }
}
```

After:
```php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Alert extends Component
{
    //
}
```

Other considerations - throw a good exception message when the blade view doesn't exist (making it clear we couldn't automatically resolve the view)?

2023-06-08 18:16 UTC, milwad-dev reviewed
One problem is here!
Think you are developing a modular project, and you want to render components.
Here you can't load from another path and is a wrong change here

2023-06-08 18:39 UTC, GrahamCampbell requested changes

2023-06-08 18:39 UTC, GrahamCampbell commented on src/Illuminate/View/Component.php
> +        return view('components.'.$this->resolveViewName());
You cannot call a foundation function from the view component.

2023-06-08 18:40 UTC, ahinkle commented
@milwad-dev,

As mentioned, developers may continue to write their own render() methods for complex customization.

2023-06-08 18:58 UTC, milwad-dev commented
@ahinkle 
How can custom render function?

2023-06-08 23:09 UTC, dennisprudlo commented
You can just keep using it like you did before. Stubs were not changed, the render function will alway be there. But if you use the render function to return the default view of the component without any customizations you can remove it

2023-06-10 06:15 UTC, imerfanahmed commented
In my opinion, Omitting a render method from the developer's end might not be a good decision.
Just because it reduces the readability of code structure.
I often work with legacy code and I have to navigate and trace the view with the controller and so on, omitting render might be a nightmare for me.

2023-06-18 19:05 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2023-06-18 19:05 UTC, closed without merging