Update DatabaseQueue.php
laravel/framework pull request #47511
Opened 2023-06-20 14:42 UTC by bebo925

Fixes #47510 

When using the database driver for queues on an MSSQL connection, the PHP version on Mac specifically causes an error in DatabaseQueue.php when getting the database version.  This fix allows users to manually set the version in the database config options array.

2023-06-20 14:47 UTC, driesvints requested changes

2023-06-20 14:47 UTC, driesvints commented on src/Illuminate/Queue/DatabaseQueue.php
> +        $databaseVersion = $this->database->getConfig('options.version') ?? $this->database->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION);
Might be better to use this as an alternative should some people rely on the previous key?

```suggestion
        $databaseVersion = $this->database->getConfig('version') ?? $this->database->getConfig('options.version') ?? ?? $this->database->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION);
```

2023-06-21 23:04 UTC, taylorotwell commented
Why did you choose `options.version`? Do other queue drivers use this convention?

2023-06-22 11:40 UTC, taylorotwell commented
I honestly do not think this will fix your issue.

2023-06-22 11:40 UTC, closed without merging