Logger: format Throwable
laravel/framework pull request #47651
Opened 2023-07-04 14:10 UTC by asanikovich

## Idea
Add support to correct formatting `Throwable` while using logger

```php
$e = new RuntimeException('test');
$this->logger->error($e);
```

Log `Throwable` follow PSR because `Throwable` implements the `Stringable` interface.
```php
interface Psr\Log\LoggerInterface {
    public function log($level, string|\Stringable $message, array $context = []): void;
}
```

## For what?
Before it log message as `(string) $e`, now we use next format:
```php
$message = $e->getMessage();
$context['exception'] = `$e`; 
// which can be formatted later (by default to string, or by custom drivers (as sentry) to related format)
```
In this case, we can have the following pros:
2. support logging from exceptions from libraries that use `Psr\Log\LoggerInterface`
3. support logging exceptions with correct stack trace for Sentry (in this case there is no duplication of errors compared to  `report()`)
4. support to replace usage `report()` with logger in your code

## If you say "NO"
Please look at https://github.com/laravel/framework/pull/47654

2023-07-04 16:15 UTC, GrahamCampbell requested changes
👎 for merging this. This is incorrect, as the message is not allowed to be a throwable. This is an incorrect usage of the logger.

2023-07-04 16:16 UTC, GrahamCampbell commented
> Log Throwable follow PSR because Throwable implements the Stringable interface.

Not true. That only exists so you can do a __toString call, not so you can do other jank with objects, by type inspection.

2023-07-04 16:27 UTC, asanikovich commented
@GrahamCampbell Do you read my section "For what?" ?

1. How do you offer to handle logging errors from libraries?
2. As for me if we call `$message instanceof Throwable...`, and helps framework to work with exception throught logging - it's only advantage for people.

2023-07-04 18:56 UTC, GrahamCampbell commented
> How do you offer to handle logging errors from libraries? (with sentry driver)

Such libraries need to use the context parameter to pass the exception, just like Bugsnag does.

2023-07-04 18:57 UTC, GrahamCampbell commented
This mistake of using the exception directly in the message paramter was already made in Laravel 4 and later fixed. I am not having us go back down that route.

2023-07-04 20:19 UTC, asanikovich commented
@GrahamCampbell Ok, please look at https://github.com/laravel/framework/pull/47654

2023-07-04 22:17 UTC, GrahamCampbell commented
None of the things in for what are reasons to do this? This is just people calling our logger wrong?

2023-07-05 15:19 UTC, cidosx commented
Please write this case to ur `exception handle`, do not globally modify the behavior in framework.

2023-07-05 15:24 UTC, GrahamCampbell commented
```
$this->logger->error($e-getMessage(), ['exception' => $e]);
```

2023-07-07 08:17 UTC, driesvints commented
Thanks but this seems like a change we won't make sorry.

2023-07-07 08:17 UTC, closed without merging