Allow passing a Callable to Log::debug() (and related)
laravel/framework pull request #47995
Opened 2023-08-08 15:38 UTC by jkoop

For example, I'm looping over some data in a very convoluted way (due to nature of the problem my code solves), but it crashes when given some sort of edge-case data, so I need to debug it.

Right now I'm using this:

```php
// in my huge loop
Log::debug($lineNumber + 1 . ' of ' . count($lines));
```
However, `count()` will be run (and take CPU time) even in prod; it'd be nice if I could do this:

```php
// in my huge loop
Log::debug(fn () => $lineNumber + 1 . ' of ' . count($lines));
```
Because then, `count()` will only be run when logging.

I didn't see any tests to update.

2023-08-08 15:56 UTC, GrahamCampbell requested changes
👎 This can already be achieved by you passing an object that implements to string?

2023-08-08 16:01 UTC, jkoop commented
Lots of other things in the Laravel universe support accepting `Callable`s. Consistency and guess-ableness is nice.

Also, wouldn't I have to define a class and instantiate it? Wouldn't that be slower (CPU) than passing a function?

2023-08-08 16:49 UTC, nunomaduro requested changes

2023-08-08 17:15 UTC, GrahamCampbell commented on src/Illuminate/Log/Logger.php
> +        if (is_callable($message)) {
yeh, i agree. this is not ideal.

2023-08-08 17:15 UTC, GrahamCampbell commented on src/Illuminate/Log/Logger.php
> +        if (is_callable($message)) {
and could be a security risk.

2023-08-09 13:19 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2023-08-09 13:19 UTC, closed without merging

2023-08-11 15:56 UTC, tkoop commented on src/Illuminate/Log/Logger.php
> +        if (is_callable($message)) {
Instead of doing `if (is_callable($message))`, you could do `if($message instanceof Closure)`

Security risk gone.