Remove unneeded Return type in Docblock of Illuminate\Database\Eloquent\Builder.php->get()
laravel/framework pull request #48228
Opened 2023-08-29 12:58 UTC by FrazerFlanagan

Remove unneeded static[] from ret type in docblock of Illuminate\Database\Eloquent\Builder->get()

This function only returns a collection from L:725
```
        return $builder->getModel()->newCollection($models);

2023-08-29 13:00 UTC, GrahamCampbell requested changes

2023-08-29 13:01 UTC, merged

2023-08-29 13:01 UTC, GrahamCampbell requested changes
This PR is incomplete. There are other methods with the same bug, too.

2023-08-29 16:48 UTC, localusercamp commented
> This PR is incomplete. There are other methods with the same bug, too.

I created a discussion and issue a long time ago about this weird stuff, but nobody paid attention to them.
This must be fixed.

2023-08-29 17:33 UTC, GrahamCampbell commented
This PR has been reverted again.

2023-08-29 17:49 UTC, FrazerFlanagan commented on src/Illuminate/Database/Eloquent/Builder.php
> -     * @return \Illuminate\Database\Eloquent\Collection|static[]
So should it be 
```
@return \Illuminate\Database\Eloquent\Collection<\Illuminate\Database\Eloquent\Model>
```
?

2023-09-24 11:09 UTC, darkspock commented
Hi, leaving the static[] causes phpstan/larastan to fail, and actually is a problem. If you use get()->all(), you can not get sure get() returns a Collection...