[10.x] Validate version and variant in `Str::isUuid()`
laravel/framework pull request #48321
Opened 2023-09-06 18:08 UTC by inxilpro

Right now, `Str::isUuid()` will return `true` for UUIDs that are not RFC4122-compliant. In addition to the 8-4-4-4-12 format, UUIDs have two special characters:

- The 13th character (not counting dashes) is the "version" — which can be `1–5`
- The 17th character (not counting dashes) is the "variant" — which can be `8`, `9`, `a`, or `b`

(These special values are actually defined [by specific bits in the UUID](https://www.ietf.org/rfc/rfc4122.txt), but in practice it works out to the above rules.)

Here are two UUIDs that look valid but actually are not:

```
ff6f8cb0-c57d-11e1-cb21-0800200c9a66
                   ^ "c" is not a valid variant

ff6f8cb0-c57d-61e1-9b21-0800200c9a66
              ^ "6" is not a valid version
```

This PR updates the regular expression to account for these constraints on validity. It also accounts for the one outlier case, which is the "NIL" UUID `00000000-0000-0000-0000-000000000000`. Rather than complicating the regular expression, I've just added an additional check for this exact string, because it's the only of its kind.

2023-09-06 18:12 UTC, henzeb commented
Never looked into it, but since laravel comes with Ramsey's Uuid package, why not use it's isValid method?

2023-09-06 20:17 UTC, inxilpro commented
> Never looked into it, but since laravel comes with Ramsey's Uuid package, why not use it's isValid method? 

I took a peek and Ramsey's package has the same, more generic, expression. The [uuidjs](https://github.com/uuidjs/uuid) package uses this same approach, though.

2023-09-06 20:24 UTC, taylorotwell commented
Could this be a breaking change for UUIDs that Laravel currently generates like "ordered" UUIDs, etc.?

2023-09-06 20:36 UTC, inxilpro commented
I checked ordered uuids and they’re fine. I was 99% sure they’d be unaffected, but I also tested a few million random ordered UUIDs just in case. Are there other formats that I should double-check?

2023-09-06 20:43 UTC, taylorotwell commented
Str::uuid and Str::orderedUuid are the only Laravel UUID methods, so I don't think so.

2023-09-06 20:45 UTC, GrahamCampbell requested changes

2023-09-06 20:56 UTC, inxilpro commented on src/Illuminate/Support/Str.php
> +        if ($value === '00000000-0000-0000-0000-000000000000') {
The NIL UUID is valid per the RFC.

2023-09-07 15:24 UTC, merged

2023-09-15 11:16 UTC, frodeknutsen commented
This PR introduced a breaking change for ULIDs that are converted to UUID.

2023-09-15 11:27 UTC, driesvints commented
@frodeknutsen we've reverted this in https://github.com/laravel/framework/releases/tag/v10.23.1

2023-09-15 13:07 UTC, inxilpro commented
Gah. I was talking specifically about this PR when I tweeted this…

<img width="597" alt="image" src="https://github.com/laravel/framework/assets/21592/9d29dde5-e113-43cf-a887-8230ce5a45d2">

Theoretically this change is better per the spec, but I should have just left well enough along. Sorry about that!

2023-09-15 14:41 UTC, henzeb commented
I'd say re-add it, but use strict in some way?

2023-09-15 18:50 UTC, GrahamCampbell commented
Why not just compare against `'00000000-0000-0000-0000-000000000000'` in your own code if you need to allow that value?

2023-09-17 16:21 UTC, smares commented
> Why not just compare against `'00000000-0000-0000-0000-000000000000'` in your own code if you need to allow that value?

Why? It's a valid UUID as per https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.7