fix file race condition after view:cache and artisan up
laravel/framework pull request #48368
Opened 2023-09-12 20:37 UTC by roxik

Tic PR will fix error with file race condition after call `php artisan view:cache` and `php artisan up`.

Case `php artisan up`:

User has request, passed condition `if ($this->app->maintenance Mode()->active())` then file framework/down deleted by command and then in `file_get_contents` we have `ErrorException`.

Solution: recheck file exists

<img width="857" alt="image" src="https://github.com/laravel/framework/assets/20522721/935e510a-a45e-4223-a374-4b9fee825b32">

Case `php artisan view:cache`:

Same conditions, but instead `file_get_contents` we have `filemtime`

2023-09-12 21:27 UTC, taylorotwell commented
Please remove all textual formatting / spacing changes made to docblocks and mark as ready for review again when complete. Thanks.

2023-09-13 07:01 UTC, driesvints requested changes

2023-09-13 07:01 UTC, driesvints commented on src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php
> +     * @throws ErrorException
```suggestion
     * @throws \ErrorException
```

2023-09-13 07:01 UTC, driesvints commented on src/Illuminate/View/Compilers/Compiler.php
> +     * @throws ErrorException
```suggestion
     * @throws \ErrorException
```

2023-09-13 08:55 UTC, roxik commented
@driesvints resolved

2023-09-13 18:10 UTC, merged