[10.x] Add support `Enum` class for enum method in Blueprint
laravel/framework pull request #48427
Opened 2023-09-16 10:19 UTC by milwad-dev

Think you want to use the `enum` method with Enum class in your migration, like this:

```php
public function up(): void
{
    Schema::create('products', function (Blueprint $table) {
        $table->id();
        $table->string('title');
        $table->enum('status',  \App\ProductStatusEnum::class);
        $table->timestamps();
    });
}
```

But now throw an error!

2023-09-16 10:31 UTC, milwad-dev commented
The test failure is not about my changes!

2023-09-16 10:32 UTC, GrahamCampbell requested changes
I don't agree this is a good idea because enum classes are not immutable and maybe changed or deleted in future, breaking the migrations. Migrations should never reference constants or enums outside of themselves.

2023-09-16 10:39 UTC, milwad-dev commented
When you use an array for the `enum` method, maybe change it in the future!
This is about the design of development!
Maybe I like to use the Enum class in my migration or even my Enum class should never change!

2023-09-16 19:20 UTC, CalebDW commented
Enums in PHP and enum columns in the database are two totally different things. Database enums are difficult to work with and require migrations to create/update/delete whereas you can simply edit the Enum class in PHP and be done. 

The PHP Enum should be the source of truth and you should validate any data before you save it to the database therefore you gain nothing from a database enum---there is no reason to have both a PHP Enum and an enum database column.

2023-09-17 20:50 UTC, newtonjob commented
@CalebDW I'd argue that database enums have their benefits and there's definitely a reason to use them (together with a PHP Enum).

2023-09-17 21:14 UTC, dammy001 commented
> @CalebDW I'd argue that database enums have their benefits and there's definitely a reason to use them (together with a PHP Enum).

I would say as you add more values, advantages starts to swing away from database ENUMs. Especially if values are added after the table is already in use because you have to alter the table structure.

2023-09-17 21:18 UTC, milwad-dev commented
> > @CalebDW I'd argue that database enums have their benefits and there's definitely a reason to use them (together with a PHP Enum).
> 
> I would say as you add more values, advantages starts to swing away from database ENUMs. Especially if values are added after the table is already in use because you have to alter the table structure.

I don't take advantage of database enums, rather I add new features.
I made a repository about a shop by Laravel and used an enum database with PHP enum:

https://github.com/milwad-dev/shopline/blob/main/Modules/Product/Database/Migrations/2022_08_07_195525_create_products_table.php#L26

2023-09-18 14:55 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2023-09-18 14:55 UTC, closed without merging

2023-09-19 04:41 UTC, donnysim commented
Enums are complicated in databases, you can easily jump into a situation where updating your enum column would require a full table copy, which might look fine at first but once it grows to mils of rows is a different story, and it's the most common situation when you happen to need to change it. Just using a tiny or small int is preferred in most cases.