Increase bcrypt rounds to 12
laravel/framework pull request #48494
Opened 2023-09-21 22:16 UTC by valorin

[PHP is increasing the default bcrypt cost](https://wiki.php.net/rfc/bcrypt_cost_2023) to either 11 or 12 to keep up with increases in computing, so we should do the same within Laravel. The current default of 10 was set in PHP 11 years ago, which is no longer a suitable default.

12 appears to be the sweet spot between performance and security, [as confirmed by a member of the Hashcat team](https://phpc.social/@tychotithonus@infosec.exchange/111104389164750098). [Symfony uses a cost of 13](https://github.com/symfony/password-hasher/blob/6.3/Hasher/NativePasswordHasher.php#L36C1-L37C1), however that may be too high for some servers.

Due to the way hashing works, there are no backwards compatibility issues - older passwords with lower rounds will still be handled properly, and code that automatically rehashes passwords will upgrade them over time. It's also worth pointing out that since rounds are defined in `config/hashing.php`, existing projects won't automatically get the new rounds cost and thus won't have any performance impacts. [The RFC contains hash calculation timings](https://wiki.php.net/rfc/bcrypt_cost_2023) if you'd like more information on the impacts.

Increasing rounds to 12 in `config/hashing.php` should be a recommended upgrade step for Laravel 11 (and possibly added to the guide for 10?).

Application Skeleton PR: https://github.com/laravel/laravel/pull/6245

2023-09-21 23:03 UTC, GrahamCampbell requested changes
This change is not appropriate to make on the 10.x branch of laravel/framework.

2023-09-21 23:30 UTC, valorin commented
Why not?

2023-09-22 00:06 UTC, GrahamCampbell commented
Because this is not a bug fix or new feature. It's an unexpected change that should go in a major release, and not a minor one.

2023-09-22 00:12 UTC, roycewilliams commented
Very fair! Though one _could_ certainly argue that, given how easily bcrypt cost 10 can be cracked at scale, this change could quite reasonably be classified as a security weakness (for which the fix is simply a long overdue).

But that's just from my perspective as someone who simulates the attacker, not as a developer. 😁

2023-09-22 00:31 UTC, valorin commented
I consider this a security upgrade.

I had considered putting it `9.x`, but since it's hardcoded in the app skeleton and no one creates new apps from `9.x`, I PR'ed it 
into the `10.x` config file. I've updated the framework to match the default in the config file so there aren't two defaults.

It won't affect any existing apps either, so it shouldn't have any side effects.

2023-09-22 07:17 UTC, driesvints commented
@GrahamCampbell I don't think this is a breaking change though? The only thing that'll happen is that stronger passwords will be created. Both the `check` and `needsRehash` will still work as expected. `needsRehash` will start to return `true` as soon as it picks up an old password with the old rounds which is what you want really.

If I see it wrong definitely feel free to point that out.

2023-09-22 08:38 UTC, GrahamCampbell commented
Breaking for people directly making the class.

2023-09-22 08:40 UTC, driesvints commented
@GrahamCampbell but please explain how this would break anything?

2023-09-22 08:43 UTC, GrahamCampbell commented
`new BcryptHasher` uses a different number of rounds, before and after.

2023-09-22 08:44 UTC, driesvints commented
Again, I don't see the breaking change 😅

2023-09-22 08:47 UTC, GrahamCampbell commented
It;s the same issue as if we had a sleep method with a default of 1 second, then we changed it to 10 seconds.

2023-09-22 15:05 UTC, merged

2023-09-22 15:06 UTC, taylorotwell commented
I don't think this is really breaking? One of the benefits of bcrypt is the cost is baked into the hash so that all existing hashes continue to work.

2023-09-23 12:11 UTC, valorin commented on src/Illuminate/Hashing/BcryptHasher.php
> +    protected $rounds = 12;
It's already been merged, but this already exists with the `setRounds()` and `cost()` methods. 🙂

![image](https://github.com/laravel/framework/assets/897369/4f6fb4bd-b253-4aa8-9afb-e56db357c469)

Although perhaps the the swapping of cost and rounds is adding to some confusion?

2023-09-23 12:13 UTC, valorin commented on src/Illuminate/Hashing/BcryptHasher.php
> +    protected $rounds = 12;
Sorry, ignore my last comment - I was confused with something else.

You can easily set it outside the class. What's the use case for extending the class itself?