[10.x] Remember the job on the exception
laravel/framework pull request #48830
Opened 2023-10-27 00:55 UTC by timacdonald

When these exceptions are triggered, the will pass through the applications handlers reporting piping.

It may be common for a certain type of job to time out and be treated "special".

Currently the only way to do this is to check the error message, .e.g.,

```php
if (
    $e instanceof MaxAttemptsExceededException &&
    str_starts_with($e->getMessage(), MySpecialJob::class.' ')
) {
    //
}
```

While not the end of the world, it feels a flaky and yuck. This exposes the job on the exception.

```php
if (
    $e instanceof MaxAttemptsExceededException &&
    $e->job->getResolvedJob() instanceof MySpecialJob
) {
    //
}
```

2023-10-27 06:30 UTC, Jubeki commented on tests/Queue/QueueExceptionTest.php
> +        $this->assertSame('App\\Jobs\\UnderlyingJob has timed out.', $e->getmessage());
```suggestion
        $this->assertSame('App\\Jobs\\UnderlyingJob has timed out.', $e->getMessage());
```

2023-10-27 06:30 UTC, Jubeki commented on tests/Queue/QueueExceptionTest.php
> +        $this->assertSame('App\\Jobs\\UnderlyingJob has been attempted too many times.', $e->getmessage());
```suggestion
        $this->assertSame('App\\Jobs\\UnderlyingJob has been attempted too many times.', $e->getMessage());
```

2023-10-27 07:50 UTC, driesvints requested changes

2023-10-27 07:50 UTC, driesvints commented on src/Illuminate/Queue/MaxAttemptsExceededException.php
> +     * @var \Illuminate\Contracts\Queue\Job
Could also be `null` when third parties are using this directly without the `forJob` method.

```suggestion
     * @var \Illuminate\Contracts\Queue\Job|null
```

2023-10-27 07:52 UTC, driesvints commented
@timacdonald looks good. What are your thoughts on the job having a large payload and thus filling up logs when being reported?

2023-10-28 02:52 UTC, timacdonald commented on tests/Queue/QueueExceptionTest.php
> +        $this->assertSame('App\\Jobs\\UnderlyingJob has been attempted too many times.', $e->getmessage());
lol. thank you

2023-10-29 23:44 UTC, timacdonald commented
@driesvints my understanding is that custom properties on exceptions are ignored when reporting or logging.

I've never seen attaching a property to an exception class cause any issues.


See also: https://github.com/laravel/framework/pull/47223#issuecomment-1564092031

2023-10-30 00:09 UTC, merged

2023-10-30 10:12 UTC, driesvints commented
@timacdonald yup, you're totally right! 👍