[10.x] Ability to establish connection without using Config Repository
laravel/framework pull request #49527
Opened 2023-12-30 18:35 UTC by deleugpn

This PR is a follow-up on this comment I left on another PR: https://github.com/laravel/framework/pull/49385#issuecomment-1872542306

The following diagram helps understand the changes:

![image](https://github.com/laravel/framework/assets/9533181/b2c754ff-a6d7-4d77-933e-da7930244198)

![image](https://github.com/laravel/framework/assets/9533181/7953284f-ae0a-4507-937e-2ebd5d56c749)

If merged, this PR will allow Laravel users to establish a runtime database connection without having to first make a global runtime change to the Config repository, essentially creating an alternative decoupled to Illuminate/Config/Repository.

2024-01-01 12:59 UTC, driesvints requested changes

2024-01-01 12:59 UTC, driesvints commented on src/Illuminate/Database/DatabaseManager.php
> +     * @return ConnectionInterface
Can you use FQN everywhere?

2024-01-01 12:59 UTC, driesvints commented on src/Illuminate/Database/DatabaseManager.php
> +     * Establish a fresh connection .
```suggestion
     * Establish a fresh connection.
```

2024-01-07 15:38 UTC, taylorotwell commented
Removed `overrideUsing`... Added: `connectUsing(name, config, force: true)`

2024-01-07 15:44 UTC, merged