Add Str::Extension function for returning the extension off of a filename.
laravel/framework pull request #51543
Opened 2024-05-22 22:40 UTC by krlmrr

This would add the ability for Laravel to return the extension of a filename string passed into the extension call.

Example: 

```php 
Str::extension('test.png');

// ".png"
```

2024-05-22 22:50 UTC, crynobone requested changes
Why shouldn't this go inside `Illuminate\Filesystem\Filesystem`?

2024-05-22 22:51 UTC, krlmrr commented
> Why shouldn't this go inside `Illuminate\Filesystem\Filesystem`?

I could put it in both places, but for the need I needed it for, it would just be needed for the string.

2024-05-22 23:01 UTC, krlmrr commented
@crynobone Moved, as requested.

2024-05-22 23:13 UTC, hafezdivandari commented
But we already have `File::extension()`?

```php
use Illuminate\Support\Facades\File;

File::extension('test.png') // png
```

2024-05-22 23:20 UTC, krlmrr commented
> But we already have `File::extension()`?
> 
> ```
> use Illuminate\Support\Facades\File;
> 
> File::extension('test.png') // png
> ```

I just saw this and I agree, it doesn't exactly work for my needs. Having the Str::extension would be more beneficial in edge cases like Unit tests, or grabbing the extension before it's uploaded. I am fine with closing this PR if you think it's too niche and doesn't really need to be part of the framework.

2024-05-23 08:27 UTC, hafezdivandari commented
The path doesn't need to be existed to use `File::extension()`, it works with any string path, even fake ones, actually it calls [PHP `pathinfo` function](https://www.php.net/manual/en/function.pathinfo.php) under the hood. You may check:

https://github.com/laravel/framework/blob/0b17465ad1bb82f7e305cd2325e4a4d0e323e9f6/src/Illuminate/Filesystem/Filesystem.php#L424-L427

2024-05-23 14:27 UTC, krlmrr commented
> The path doesn't need to be existed to use `File::extension()`, it works with any string path, even fake ones, actually it calls [PHP `pathinfo` function](https://www.php.net/manual/en/function.pathinfo.php) under the hood. You may check:
> 
> https://github.com/laravel/framework/blob/0b17465ad1bb82f7e305cd2325e4a4d0e323e9f6/src/Illuminate/Filesystem/Filesystem.php#L424-L427

I am seeing that, the only difference is mine adds the "." back to the extension.

2024-05-23 15:33 UTC, ahinkle commented
Seems kinda niche and specific vs Filesystem check. What would be the reason for the framework to maintain it?

> I am seeing that, the only difference is mine adds the "." back to the extension.

```php
return '.' . File::extension('test.png'); // .png
```

2024-05-23 18:40 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

2024-05-23 18:40 UTC, closed without merging