[11.x] Update app.php config stub to match default config file
laravel/framework pull request #51729
Opened 2024-06-06 15:10 UTC by MaxGiting

I was getting errors when trying to use the new `dontMergeFrameworkConfiguration()` setting.

It was because when I published all the config files the stub file for `app.php` was missing a few array keys.

Should these stub files always match the base config files?

2024-06-07 02:39 UTC, crynobone commented
>  was getting errors when trying to use the new `dontMergeFrameworkConfiguration()` setting.

Shouldn't your `config/app.php` contain all the possible options when you wish to use `dontMergeFrameworkConfiguration()`?

2024-06-07 02:40 UTC, crynobone commented
Please create a bug report with a reproducing repository or add integration tests to verify this issue.

2024-06-07 02:41 UTC, crynobone requested changes
Please create a bug report with a reproducing repository or add integration tests to verify this issue.

2024-06-07 08:04 UTC, MaxGiting commented
> Shouldn't your `config/app.php` contain all the possible options when you wish to use `dontMergeFrameworkConfiguration()`?

Yes that is correct. `config/app.php` needs to contain all keys, but when running `php artisan config:publish --all` that is not what happens. The published config file comes from `config-stubs/app.php` which is missing some used keys.

I guess my question really is. Should the `config-stubs/app.php` contain all the default and required keys that `config/app.php` has?

2024-06-07 08:35 UTC, MaxGiting commented
@crynobone 
As suggested I have created a bug report and related example repo.
https://github.com/laravel/framework/issues/51736

2024-06-07 14:01 UTC, crynobone commented
Seems it would make more sense to publish from `config` instead of `config-stubs` when using don't merge framework configuration.

2024-06-10 09:26 UTC, crynobone commented
Submit an alternative PR #51751

2024-06-10 15:28 UTC, closed without merging