[11.x] Makes sequences work with factories
laravel/framework pull request #53143
Opened 2024-10-13 14:52 UTC by marickvantuil

Currently, sequences can only work with arrays:

```php
$users = User::factory()
  ->count(10)
  ->state(new Sequence(
      ['admin' => 'Y'],
      ['admin' => 'N'],
  ))
  ->create();
```

This works fine for simple deviations but becomes a bit limited, if in this example, being an admin actually means assigning a role, like

```php
use Spatie\Permission\Models\Role;

->hasAttached(Role::findByName('admin'))
```

The code would have to be rewritten to something like this:

```php
$users = collect();

for ($i = 0; $i < 10; $i++) {
    $users[] = User::factory()
        ->when(
            $i % 2 === 0,
            fn ($f) => $f->hasAttached(Role::findByName('admin')),
            fn ($f) => $f->hasAttached(Role::findByName('user')),
        )
        ->create();
}
```

This PR proposes an update to sequences so it can use factory methods:

```php
$users = User::factory()
    ->count(10)
    ->sequence(
        fn ($seq, $factory) => $factory->hasAttached(Role::findByName('admin')),
        fn ($seq, $factory) => $factory->hasAttached(Role::findByName('user')),
    )
    ->create();
```

---

The PR has a basic implementation of this feature and should work with `state()`, `for()` and `has()` but is not finished yet.

I'm actually looking for feedback first, whether this something that is worth adding to Laravel and worth spending more time on. The final implementation would add some more complexity than the current implementation, because for example, hooks like `afterMaking` and `afterCreating` are not yet run for each sequence:

```php
User::factory()
    ->count(2)
    ->afterMaking(fn() => dump('user afterMaking'))
    ->sequence(
      fn ($seq, $factory) => $factory->afterMaking('sequence 1 after making'),
      fn ($seq, $factory) => $factory->afterMaking('sequence 2 after making')
    )

// user afterMaking
// not run: sequence 1 after making
// user afterMaking
// not run: sequence 2 after making
```

2024-10-14 05:23 UTC, crynobone requested changes

2024-10-14 05:23 UTC, crynobone commented on src/Illuminate/Database/Eloquent/Factories/Sequence.php
> +     * @param Factory $factory The factory that the sequence is invoked from
```suggestion
     * @param  \Illuminate\Database\Eloquent\Factories\Factory  $factory
```

2024-10-14 05:23 UTC, crynobone commented on src/Illuminate/Database/Eloquent/Factories/Factory.php
> +     * @return Collection
```suggestion
     * @param  int  $index
     * @return \Illuminate\Support\Collection
```

2024-10-14 05:23 UTC, crynobone commented on src/Illuminate/Database/Eloquent/Factories/Factory.php
> +     * @return Collection
```suggestion
     * @return \Illuminate\Support\Collection
```

2024-10-14 05:23 UTC, crynobone commented on src/Illuminate/Database/Eloquent/Factories/Factory.php
>       * @return void
```suggestion
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @param  int  $index
     * @return void
```

2024-10-14 05:23 UTC, crynobone commented on src/Illuminate/Database/Eloquent/Factories/Factory.php
> +        $results->each(function ($model, int $index) {
```suggestion
        $results->each(function ($model, $index) {
```

We don't normally add strict type on closure.

2024-10-16 21:49 UTC, taylorotwell commented
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If applicable, please consider releasing your code as a package so that the community can still take advantage of your contributions!

2024-10-16 21:49 UTC, closed without merging