add support for BackedEnums to Arr helper
laravel/framework pull request #53234
Opened 2024-10-18 17:26 UTC by macbookandrew

Similar to https://github.com/laravel/framework/pull/52677, https://github.com/laravel/framework/pull/52679, and https://github.com/laravel/framework/pull/52792, using enums improves code readability, maintainability and reduces the hassle of using string values within the code itself.

This adds `BackedEnum` support to the `Arr` methods:

```php
Arr::get($roles, Role::ADMIN);
```

This PR is backward compatible and shouldn't bring any breaking changes.

2024-10-18 21:35 UTC, henzeb commented
Why not supporting unit enums as well?

2024-10-18 22:36 UTC, crynobone requested changes

2024-10-18 22:36 UTC, crynobone commented on src/Illuminate/Collections/Arr.php
> +        $key = $key instanceof BackedEnum ? $key->value : $key;
should use `Illuminate\Support\enum_value()` function

2024-10-19 08:51 UTC, siarheipashkevich commented
@macbookandrew what do you think about adding support Enums for https://laravel.com/docs/11.x/validation#complex-conditional-validation ?

2024-10-21 14:01 UTC, closed without merging