Fix code for invalid locale for number class. if provided locale is not valid throws exception
laravel/framework pull request #53318
Opened 2024-10-27 17:24 UTC by mdariftiens

Fix code for invalid locale for number class. if provided locale is not valid throws exception.

**Existing behaviour:** If locale is invalid, falback en is used.
**Updated behaviour:** if locale is invalid throws an exception as Locale is invalid.

**Note:** A test is also added.

2024-10-28 01:53 UTC, crynobone requested changes

2024-10-28 01:53 UTC, crynobone commented on src/Illuminate/Support/Number.php
> +            throw new \Exception("Locale is invalid");
Should be `InvalidArgumentException`

2024-10-28 01:53 UTC, crynobone commented on tests/Support/SupportNumberTest.php
> +        $this->expectException(\Exception::class);
Should also assert `expectExceptionMessage`

2024-10-29 14:24 UTC, taylorotwell commented
I think it's ok.

2024-10-29 14:24 UTC, closed without merging